"""Question banks — Course 01 Python Foundations (5 × 50+ questions)."""

from core import InterviewQA, Question, TopicSpec


def _q(section: str, text: str, solution: str) -> Question:
    return Question(text=text, solution=solution, section=section)


def _interview(section: str, q: str, a: str) -> InterviewQA:
    return InterviewQA(question=q, answer=a, section=section)


# ── 01 Variables, Data Types & Operators ─────────────────────────────────────

VARIABLES_QUESTIONS = [
    _q("Section 1: Types & introspection", "Create variables `a=10`, `b=3.14`, `c='hello'`, `d=True`. Print each value with its type.", "a, b, c, d = 10, 3.14, 'hello', True\nfor v in (a, b, c, d):\n    print(v, type(v))"),
    _q("Section 1: Types & introspection", "Use `isinstance` to check if `x=42` is int or float. Print both checks.", "x = 42\nprint(isinstance(x, int), isinstance(x, float))"),
    _q("Section 1: Types & introspection", "Convert string `'123'` to int, float, and bool. Print results.", "s = '123'\nprint(int(s), float(s), bool(s))"),
    _q("Section 1: Types & introspection", "What happens converting `'0'` and `''` to bool? Demonstrate with print.", "print(bool('0'), bool(''), bool(0))"),
    _q("Section 1: Types & introspection", "Create `n=None`. Check `n is None` vs `n == None`. Print both.", "n = None\nprint(n is None, n == None)"),
    _q("Section 1: Types & introspection", "Print `id()` of two variables referencing same list vs two equal lists.", "a = [1, 2]\nb = a\nc = [1, 2]\nprint(id(a) == id(b), id(a) == id(c))"),
    _q("Section 1: Types & introspection", "Use `type()` chaining: create `x=5`, then reassign `x='five'`. Print type before and after.", "x = 5\nprint(type(x))\nx = 'five'\nprint(type(x))"),
    _q("Section 1: Types & introspection", "Demonstrate integer division `//` vs true division `/` for `7/2` and `7//2`.", "print(7/2, 7//2)"),
    _q("Section 1: Types & introspection", "Compute modulo, power: `17 % 5` and `2 ** 10`.", "print(17 % 5, 2 ** 10)"),
    _q("Section 1: Types & introspection", "Use `divmod(17, 5)` and unpack quotient and remainder.", "q, r = divmod(17, 5)\nprint(q, r)"),
    _q("Section 2: Operators", "Evaluate and print: `3 + 4 * 2`, `(3+4)*2`, and operator precedence demo.", "print(3 + 4 * 2, (3 + 4) * 2)"),
    _q("Section 2: Operators", "Compare `==` vs `is` for two strings `'aiml'` created separately.", "a = 'aiml'\nb = 'ai' + 'ml'\nprint(a == b, a is b)"),
    _q("Section 2: Operators", "Use chained comparison: check if `1 < x < 10` for `x=5`.", "x = 5\nprint(1 < x < 10)"),
    _q("Section 2: Operators", "Demonstrate short-circuit: `False and print('no')` — explain via safe version.", "result = False and print('no')\nprint(result)"),
    _q("Section 2: Operators", "Use walrus operator `:=` to assign and test `n=10` in one expression inside print.", "n = 10\nprint((m := n * 2) > 15, m)"),
    _q("Section 2: Operators", "Bitwise AND/OR on `5 & 3` and `5 | 3`. Print binary with `bin()`.", "print(bin(5 & 3), bin(5 | 3))"),
    _q("Section 2: Operators", "Shift bits: `8 << 2` and `8 >> 1`.", "print(8 << 2, 8 >> 1)"),
    _q("Section 2: Operators", "Use `round(3.14159, 2)` and `round(2.675, 2)` — print both.", "print(round(3.14159, 2), round(2.675, 2))"),
    _q("Section 2: Operators", "Compute absolute value with `abs(-42)` and `pow(2,8)`.", "print(abs(-42), pow(2, 8))"),
    _q("Section 2: Operators", "Assign augmented ops: `x=10`, then `x+=5`, `x*=2`. Print final x.", "x = 10\nx += 5\nx *= 2\nprint(x)"),
    _q("Section 3: Strings", "Create multi-line string with triple quotes containing your name and course.", "bio = '''Student\nAIML Certificate'''\nprint(bio)"),
    _q("Section 3: Strings", "Slice `'Data Science'` to get `'Data'`, `'Science'`, and reverse full string.", "s = 'Data Science'\nprint(s[:4], s[5:], s[::-1])"),
    _q("Section 3: Strings", "Use f-string to print `Sales: $1234.5` formatted to 2 decimals.", "amount = 1234.5\nprint(f'Sales: ${amount:.2f}')"),
    _q("Section 3: Strings", "Split `'a,b,c,d'` on comma and join back with `'-'`.", "parts = 'a,b,c,d'.split(',')\nprint('-'.join(parts))"),
    _q("Section 3: Strings", "Strip whitespace from `'  hello  '` and convert to upper/lower.", "s = '  hello  '\nprint(s.strip().upper(), s.strip().lower())"),
    _q("Section 3: Strings", "Check if `'python'` starts with `'py'` and ends with `'on'`.", "s = 'python'\nprint(s.startswith('py'), s.endswith('on'))"),
    _q("Section 3: Strings", "Replace `'cat'` with `'dog'` in `'the cat sat'`.", "print('the cat sat'.replace('cat', 'dog'))"),
    _q("Section 3: Strings", "Find index of `'a'` in `'banana'` using `.find()` and `.index()`.", "s = 'banana'\nprint(s.find('a'), s.index('a'))"),
    _q("Section 3: Strings", "Use `in` to test substring `'data' in 'metadata'`.", "print('data' in 'metadata')"),
    _q("Section 3: Strings", "Format with `.format()`: `'{} scored {}'`.format('Alice', 99).", "print('{} scored {}'.format('Alice', 99))"),
    _q("Section 4: Casting & validation", "Safely convert user string `'42.5'` to float; handle `'bad'` with try/except.", "def safe_float(s):\n    try:\n        return float(s)\n    except ValueError:\n        return None\nprint(safe_float('42.5'), safe_float('bad'))"),
    _q("Section 4: Casting & validation", "Check if string `'12345'` is numeric using `.isdigit()`.", "s = '12345'\nprint(s.isdigit())"),
    _q("Section 4: Casting & validation", "Convert list of string numbers `['1','2','3']` to ints with list comprehension.", "print([int(x) for x in ['1', '2', '3']])"),
    _q("Section 4: Casting & validation", "Use `bool()` on `[0], [1], {}, {0}, ''`. Print all.", "for v in [0, 1, [], [1], {}, {0}, '']:\n    print(v, bool(v))"),
    _q("Section 4: Casting & validation", "Swap two variables `a=1, b=2` without temp variable.", "a, b = 1, 2\na, b = b, a\nprint(a, b)"),
    _q("Section 4: Casting & validation", "Unpack tuple `(2024, 9, 4)` into year, month, day.", "year, month, day = (2024, 9, 4)\nprint(year, month, day)"),
    _q("Section 4: Casting & validation", "Create constants PI=3.14159 (convention) and compute circle area r=5.", "PI = 3.14159\nr = 5\nprint(PI * r ** 2)"),
    _q("Section 4: Casting & validation", "Demonstrate float precision issue: `0.1 + 0.2 == 0.3` and fix with round.", "print(0.1 + 0.2 == 0.3)\nprint(round(0.1 + 0.2, 1) == 0.3)"),
    _q("Section 4: Casting & validation", "Use `complex(2,3)` and print real/imag parts.", "z = complex(2, 3)\nprint(z.real, z.imag)"),
    _q("Section 4: Casting & validation", "Convert int 255 to hex and binary strings.", "n = 255\nprint(hex(n), bin(n))"),
    _q("Section 5: Mixed challenges", "Write expression for Celsius to Fahrenheit: C=25.", "C = 25\nF = C * 9/5 + 32\nprint(F)"),
    _q("Section 5: Mixed challenges", "Compute BMI given weight=70kg height=1.75m. Print rounded to 1 decimal.", "w, h = 70, 1.75\nprint(round(w / h**2, 1))"),
    _q("Section 5: Mixed challenges", "Given `seconds=3661`, print hours, minutes, seconds using divmod.", "seconds = 3661\nm, s = divmod(seconds, 60)\nh, m = divmod(m, 60)\nprint(h, m, s)"),
    _q("Section 5: Mixed challenges", "Check leap year rule for year=2024 ( divisible by 4, except centuries unless /400).", "year = 2024\nleap = year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)\nprint(leap)"),
    _q("Section 5: Mixed challenges", "Build string `'Item: {}, Price: ${:.2f}'` for 3 products in a loop.", "products = [('Pen', 1.5), ('Book', 12.99)]\nfor name, price in products:\n    print(f'Item: {name}, Price: ${price:.2f}')"),
    _q("Section 5: Mixed challenges", "Use `ord('A')` and `chr(65)` to show ASCII mapping.", "print(ord('A'), chr(65))"),
    _q("Section 5: Mixed challenges", "Evaluate truthiness of `None or 0 or '' or 'ok'`.", "print(None or 0 or '' or 'ok')"),
    _q("Section 5: Mixed challenges", "Create variable annotations: `count: int = 0` and print annotation.", "count: int = 0\nprint(count, count.__annotations__ if hasattr(count, '__annotations__') else type(count))"),
    _q("Section 5: Mixed challenges", "Simulate `input` with variable `user_name='Alex'` and greet.", "user_name = 'Alex'\nprint(f'Hello, {name}!')"),
    _q("Section 5: Mixed challenges", "Combine types in f-string: int, float, bool in one line.", "print(f'{42=}, {3.14=}, {True=}')"),
]

VARIABLES_INTERVIEW = [
    InterviewQA("Conceptual", "Mutable vs immutable types in Python?", "**Mutable:** list, dict, set, bytearray. **Immutable:** int, float, str, tuple, frozenset, bytes. Immutable objects cannot change after creation; 'modification' creates new objects."),
    InterviewQA("Conceptual", "Difference between `==` and `is`?", "`==` compares **values** (equality). `is` compares **identity** (same object in memory). Use `is` only for singletons like `None`."),
    InterviewQA("Conceptual", "What is dynamic typing?", "Variable names bind to objects at runtime; the same name can refer to different types over time without explicit declaration."),
    InterviewQA("Conceptual", "How do you check type safely?", "Prefer `isinstance(x, int)` over `type(x) == int` because isinstance respects inheritance."),
    InterviewQA("Conceptual", "What is `None`?", "A singleton representing absence of value. Always test with `x is None`."),
    InterviewQA("Operators", "Explain operator precedence.", "Parentheses > exponent > unary > mult/div/mod > add/sub > comparisons > not > and > or. Use parentheses when unsure."),
    InterviewQA("Operators", "What is short-circuit evaluation?", "`and` stops at first falsy; `or` stops at first truthy. Side effects may not run."),
    InterviewQA("Operators", "Difference between `/` and `//`?", "`/` is true division (float). `//` is floor division toward negative infinity."),
    InterviewQA("Strings", "Are strings mutable?", "No. Methods like `.upper()` return **new** strings."),
    InterviewQA("Strings", "f-string vs .format() vs %?", "f-strings (3.6+) are fastest and most readable. `.format()` flexible for templates. `%` is legacy."),
    InterviewQA("Casting", "Why does `0.1 + 0.2 != 0.3`?", "Floating-point binary representation cannot exactly store some decimals. Use `decimal.Decimal` for money."),
    InterviewQA("Casting", "When is `bool('False')` True?", "Any non-empty string is truthy, including `'False'` and `'0'`."),
    InterviewQA("Memory", "What does `id()` return?", "CPython object address (identity). Same id means same object."),
    InterviewQA("Memory", "Copy vs reference for lists?", "Assignment copies reference. Use `.copy()` or `list()` for shallow copy."),
    InterviewQA("Practical", "Swap two variables pythonically?", "`a, b = b, a` using tuple packing/unpacking."),
    InterviewQA("Practical", "Walrus operator use case?", "Assign and use in expression: `if (n := len(data)) > 10:` avoids duplicate computation."),
    InterviewQA("Practical", "Chained comparisons?", "`a < b < c` equivalent to `a < b and b < c`, evaluates b once."),
    InterviewQA("Practical", "What is truthiness?", "Empty containers, zero numbers, None, False are falsy; most else truthy."),
    InterviewQA("Interview", "Explain `isinstance` vs `type` for subclasses.", "`isinstance(obj, Base)` True for subclasses. `type(obj) == Base` False for subclass instances."),
    InterviewQA("Interview", "Integer interning in CPython?", "Small ints (-5 to 256) may be cached; `is` may appear True for equal small ints."),
    InterviewQA("Interview", "Complex numbers in Python?", "`complex(real, imag)` with `.real`, `.imag`. Useful in signal processing."),
    InterviewQA("Interview", "What are variable annotations?", "Syntax `x: int = 0` for hints; stored in `__annotations__` on functions/modules."),
    InterviewQA("Interview", "Bytes vs str?", "`str` is Unicode text; `bytes` is raw binary. Encode/decode at I/O boundaries."),
    InterviewQA("Interview", "Floor vs truncation for negatives?", "`//` floors (-7//2 = -4). int(-7/2) truncates toward zero (-3)."),
    InterviewQA("Interview", "When use `divmod`?", "When you need quotient and remainder together — time conversions, pagination."),
    InterviewQA("Interview", "Explain augmented assignment.", "`x += 1` may call `__iadd__` in place for mutable types; not always same as `x = x + 1`."),
    InterviewQA("Interview", "Scientific notation literals?", "`1e-3` == 0.001; useful for ML learning rates."),
    InterviewQA("Interview", "Underscores in numeric literals?", "`1_000_000` readable; ignored by parser."),
    InterviewQA("Interview", "None as default argument pitfall?", "Mutable defaults shared across calls — use `None` sentinel instead."),
    InterviewQA("Interview", "How Python handles mixed-type ops?", "Follows coercion rules; int + float → float. Don't rely on implicit coercion in production."),
]

# ── 02 Control Flow & Functions ─────────────────────────────────────────────

CONTROL_FLOW_QUESTIONS = [
    _q("Section 1: if/elif/else", "Print 'pass' if score>=60 else 'fail' for score=75.", "score = 75\nprint('pass' if score >= 60 else 'fail')"),
    _q("Section 1: if/elif/else", "Classify age into child (<13), teen (<20), adult using if/elif/else.", "age = 16\nif age < 13:\n    print('child')\nelif age < 20:\n    print('teen')\nelse:\n    print('adult')"),
    _q("Section 1: if/elif/else", "Check if year is leap year using full rule.", "year = 2024\nif year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):\n    print('leap')\nelse:\n    print('not leap')"),
    _q("Section 1: if/elif/else", "Nested if: login if user=='admin' and pwd=='secret'.", "user, pwd = 'admin', 'secret'\nif user == 'admin':\n    print('ok' if pwd == 'secret' else 'bad pwd')\nelse:\n    print('unknown user')"),
    _q("Section 1: if/elif/else", "Use ternary to pick max of a,b without max().", "a, b = 3, 7\nprint(a if a > b else b)"),
    _q("Section 1: if/elif/else", "Grade letter from score: A>=90, B>=80, C>=70, else F.", "score = 85\nif score >= 90: g = 'A'\nelif score >= 80: g = 'B'\nelif score >= 70: g = 'C'\nelse: g = 'F'\nprint(g)"),
    _q("Section 1: if/elif/else", "Check if triangle sides a,b,c can form valid triangle.", "a, b, c = 3, 4, 5\nprint(a + b > c and a + c > b and b + c > a)"),
    _q("Section 1: if/elif/else", "Match sign of number: positive/negative/zero.", "n = -5\nprint('pos' if n > 0 else 'neg' if n < 0 else 'zero')"),
    _q("Section 1: if/elif/else", "Validate email has '@' and '.' after @ (simple check).", "email = 'a@b.com'\nok = '@' in email and '.' in email.split('@')[-1]\nprint(ok)"),
    _q("Section 1: if/elif/else", "Use `match/case` (3.10+) to map HTTP code 404 to 'Not Found'.", "code = 404\nmatch code:\n    case 404: print('Not Found')\n    case 500: print('Server Error')\n    case _: print('Other')"),
    _q("Section 2: Loops", "Print squares 1..10 with for loop.", "for i in range(1, 11):\n    print(i * i)"),
    _q("Section 2: Loops", "Sum list `[1,2,3,4,5]` with while loop.", "nums = [1, 2, 3, 4, 5]\ni, total = 0, 0\nwhile i < len(nums):\n    total += nums[i]\n    i += 1\nprint(total)"),
    _q("Section 2: Loops", "Print FizzBuzz 1..15.", "for i in range(1, 16):\n    if i % 15 == 0: print('FizzBuzz')\n    elif i % 3 == 0: print('Fizz')\n    elif i % 5 == 0: print('Buzz')\n    else: print(i)"),
    _q("Section 2: Loops", "Use `enumerate` on `['a','b','c']` print index and value.", "for i, v in enumerate(['a', 'b', 'c']):\n    print(i, v)"),
    _q("Section 2: Loops", "Use `zip` to combine names and scores lists.", "names = ['A', 'B']\nscores = [90, 85]\nfor n, s in zip(names, scores):\n    print(n, s)"),
    _q("Section 2: Loops", "Break when sum exceeds 10 iterating `[3,4,5,6]`.", "total = 0\nfor x in [3, 4, 5, 6]:\n    total += x\n    if total > 10:\n        break\nprint(total)"),
    _q("Section 2: Loops", "Continue skipping evens, print odds 1..10.", "for i in range(1, 11):\n    if i % 2 == 0:\n        continue\n    print(i)"),
    _q("Section 2: Loops", "Nested loop multiplication table 1..3.", "for i in range(1, 4):\n    for j in range(1, 4):\n        print(f'{i}x{j}={i*j}', end='  ')\n    print()"),
    _q("Section 2: Loops", "Loop `else`: search for 7 in list, print 'not found' in else.", "for x in [1, 2, 3]:\n    if x == 7:\n        print('found')\n        break\nelse:\n    print('not found')"),
    _q("Section 2: Loops", "Iterate dict `{'a':1,'b':2}` keys, values, items.", "d = {'a': 1, 'b': 2}\nfor k in d: print('k', k)\nfor v in d.values(): print('v', v)\nfor k, v in d.items(): print(k, v)"),
    _q("Section 3: Functions basics", "Define `add(a,b)` returning sum. Call with 3,4.", "def add(a, b):\n    return a + b\nprint(add(3, 4))"),
    _q("Section 3: Functions basics", "Function with default arg `greet(name='World')`.", "def greet(name='World'):\n    return f'Hello, {name}!'\nprint(greet(), greet('Engineer'))"),
    _q("Section 3: Functions basics", "Use *args to sum arbitrary numbers.", "def sum_all(*args):\n    return sum(args)\nprint(sum_all(1, 2, 3, 4))"),
    _q("Section 3: Functions basics", "Use **kwargs to build formatted string.", "def show(**kwargs):\n    return ', '.join(f'{k}={v}' for k, v in kwargs.items())\nprint(show(a=1, b=2))"),
    _q("Section 3: Functions basics", "Return multiple values: quotient and remainder.", "def divmod2(a, b):\n    return a // b, a % b\nprint(divmod2(17, 5))"),
    _q("Section 3: Functions basics", "Docstring: write function with docstring and print `help()`.", "def area(r):\n    \"\"\"Return circle area.\"\"\"\n    return 3.14 * r ** 2\nprint(area.__doc__)"),
    _q("Section 3: Functions basics", "Lambda to square: apply to 5.", "square = lambda x: x ** 2\nprint(square(5))"),
    _q("Section 3: Functions basics", "Nested function: outer returns inner that adds n.", "def make_adder(n):\n    def add(x):\n        return x + n\n    return add\nadd10 = make_adder(10)\nprint(add10(5))"),
    _q("Section 3: Functions basics", "Recursion: factorial of 5.", "def fact(n):\n    return 1 if n <= 1 else n * fact(n - 1)\nprint(fact(5))"),
    _q("Section 3: Functions basics", "Recursion: Fibonacci nth (simple, n=10).", "def fib(n):\n    if n <= 1:\n        return n\n    return fib(n - 1) + fib(n - 2)\nprint(fib(10))"),
    _q("Section 4: Scope & advanced", "Demonstrate local vs global with `global` keyword.", "count = 0\ndef inc():\n    global count\n    count += 1\ninc()\nprint(count)"),
    _q("Section 4: Scope & advanced", "Use `nonlocal` in nested function to modify outer x.", "def outer():\n    x = 1\n    def inner():\n        nonlocal x\n        x += 1\n    inner()\n    return x\nprint(outer())"),
    _q("Section 4: Scope & advanced", "Function annotation: `def f(x: int) -> int: return x*2`.", "def f(x: int) -> int:\n    return x * 2\nprint(f(3))"),
    _q("Section 4: Scope & advanced", "Pass function as argument: apply twice.", "def apply_twice(fn, x):\n    return fn(fn(x))\nprint(apply_twice(lambda n: n + 1, 5))"),
    _q("Section 4: Scope & advanced", "Implement linear search function returning index or -1.", "def linear_search(arr, target):\n    for i, v in enumerate(arr):\n        if v == target:\n            return i\n    return -1\nprint(linear_search([3, 1, 4], 4))"),
    _q("Section 4: Scope & advanced", "Write `is_palindrome(s)` ignoring case.", "def is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]\nprint(is_palindrome('Radar'))"),
    _q("Section 4: Scope & advanced", "Decorator: simple timer wrapper (use time.sleep demo).", "import time\ndef timer(fn):\n    def wrapper(*a, **k):\n        t0 = time.time()\n        out = fn(*a, **k)\n        print(f'{time.time()-t0:.4f}s')\n        return out\n    return wrapper\n@timer\ndef work():\n    time.sleep(0.01)\nwork()"),
    _q("Section 4: Scope & advanced", "Generator function yielding squares up to n=5.", "def squares(n):\n    for i in range(n):\n        yield i * i\nprint(list(squares(5)))"),
    _q("Section 4: Scope & advanced", "Use `map` and `filter` on list 1..10: evens squared.", "nums = list(range(1, 11))\nprint(list(map(lambda x: x**2, filter(lambda x: x % 2 == 0, nums))))"),
    _q("Section 4: Scope & advanced", "Closure pitfall: fix late-binding in loop creating lambdas.", "funcs = [(lambda x=i: x) for i in range(3)]\nprint([f() for f in funcs])"),
    _q("Section 5: Challenges", "Binary search iterative on sorted list.", "def binary_search(a, t):\n    lo, hi = 0, len(a) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if a[mid] == t: return mid\n        if a[mid] < t: lo = mid + 1\n        else: hi = mid - 1\n    return -1\nprint(binary_search([1,3,5,7], 5))"),
    _q("Section 5: Challenges", "Count vowels in string with function.", "def count_vowels(s):\n    return sum(1 for c in s.lower() if c in 'aeiou')\nprint(count_vowels('Hello'))"),
    _q("Section 5: Challenges", "Merge two sorted lists into one sorted.", "def merge(a, b):\n    i = j = 0\n    out = []\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]: out.append(a[i]); i += 1\n        else: out.append(b[j]); j += 1\n    return out + a[i:] + b[j:]\nprint(merge([1,3], [2,4]))"),
    _q("Section 5: Challenges", "Implement `min` manually for list.", "def my_min(arr):\n    m = arr[0]\n    for x in arr[1:]:\n        if x < m: m = x\n    return m\nprint(my_min([3,1,4]))"),
    _q("Section 5: Challenges", "Prime check function.", "def is_prime(n):\n    if n < 2: return False\n    for i in range(2, int(n**0.5)+1):\n        if n % i == 0: return False\n    return True\nprint(is_prime(17))"),
    _q("Section 5: Challenges", "GCD using Euclidean algorithm.", "def gcd(a, b):\n    while b:\n        a, b = b, a % b\n    return a\nprint(gcd(48, 18))"),
    _q("Section 5: Challenges", "Matrix transpose 2x3 using nested loops.", "m = [[1,2,3],[4,5,6]]\nt = [[m[r][c] for r in range(len(m))] for c in range(len(m[0]))]\nprint(t)"),
    _q("Section 5: Challenges", "Parse CSV line `'a,b,c'` into list without split (manual).", "line = 'a,b,c'\nout, cur = [], ''\nfor ch in line:\n    if ch == ',': out.append(cur); cur = ''\n    else: cur += ch\nout.append(cur)\nprint(out)"),
    _q("Section 5: Challenges", "Retry decorator pattern: call fn up to 3 times until success.", "def retry(fn, times=3):\n    for _ in range(times):\n        try:\n            return fn()\n        except Exception:\n            pass\n    raise RuntimeError('failed')\nprint(retry(lambda: 42))"),
    _q("Section 5: Challenges", "Implement `chunk_list(lst, size)` → sublists.", "def chunk_list(lst, size):\n    return [lst[i:i+size] for i in range(0, len(lst), size)]\nprint(chunk_list([1,2,3,4,5], 2))"),
]

CONTROL_FLOW_INTERVIEW = [
    InterviewQA("Control flow", "When use elif vs separate if?", "elif avoids re-checking earlier True branches; separate if allows multiple blocks to run."),
    InterviewQA("Control flow", "for vs while?", "for when iterations known/iterable; while when condition-driven."),
    InterviewQA("Control flow", "What does loop else do?", "Runs if loop completes without break — useful for search-not-found."),
    InterviewQA("Functions", "*args vs **kwargs?", "*args collects positional extras as tuple; **kwargs collects keyword extras as dict."),
    InterviewQA("Functions", "Default mutable argument bug?", "Default evaluated once; shared list mutated across calls. Use None default."),
    InterviewQA("Functions", "Lambda limitations?", "Single expression, no statements; fine for short callbacks."),
    InterviewQA("Scope", "LEGB rule?", "Local → Enclosing → Global → Built-in name lookup order."),
    InterviewQA("Scope", "global vs nonlocal?", "global binds module-level; nonlocal binds nearest enclosing (non-global) scope."),
    InterviewQA("Advanced", "Generator vs list?", "Generator lazy, memory efficient; list stores all values."),
    InterviewQA("Advanced", "What is a decorator?", "Function wrapping another to extend behavior without modifying source."),
    InterviewQA("Advanced", "Recursion limit?", "sys.getrecursionlimit(); deep recursion risks stack overflow — prefer iteration."),
    InterviewQA("Advanced", "Tail recursion in Python?", "Not optimized by CPython; iteration preferred for deep calls."),
    InterviewQA("Advanced", "First-class functions?", "Functions are objects — assign, pass, return, store in collections."),
    InterviewQA("Advanced", "map/filter vs comprehensions?", "Comprehensions more Pythonic and often faster to read."),
    InterviewQA("Advanced", "match/case purpose?", "Structural pattern matching (3.10+) — cleaner than long if/elif chains."),
    InterviewQA("Interview", "Difference return vs yield?", "return ends function; yield makes generator pausing execution."),
    InterviewQA("Interview", "Closure definition?", "Inner function remembering enclosing scope variables."),
    InterviewQA("Interview", "Late binding closure fix?", "Bind loop variable via default arg: lambda x=i: x."),
    InterviewQA("Interview", "Type hints enforced?", "No at runtime by default; use mypy/pyright for static checking."),
    InterviewQA("Interview", "Docstring conventions?", "PEP 257; first line summary; used by help() and Sphinx."),
    InterviewQA("Interview", "pass, break, continue?", "pass noop; break exit loop; continue next iteration."),
    InterviewQA("Interview", "Ternary operator syntax?", "`a if cond else b` — expression not statement."),
    InterviewQA("Interview", "Enumerate benefit?", "Provides index+value without manual counter."),
    InterviewQA("Interview", "Zip with unequal lengths?", "Stops at shortest; use itertools.zip_longest for padding."),
    InterviewQA("Interview", "any() vs all()?", "any True if one true; all True if all true — short-circuit."),
    InterviewQA("Interview", "How to reverse iterate?", "`reversed(seq)` or `range(len-1,-1,-1)` for indices."),
    InterviewQA("Interview", "Function as object attributes?", "Has __name__, __doc__, __defaults__; can setattr on functions."),
    InterviewQA("Interview", "Partial application?", "functools.partial fixes subset of arguments."),
    InterviewQA("Interview", "Memoization pattern?", "Cache results dict keyed by args — functools.lru_cache built-in."),
    InterviewQA("Interview", "When not to use recursion?", "Deep trees, performance critical paths, Python stack limits."),
]

# Add remaining course 01 topics in compact form - I'll continue in same file

DATA_STRUCTURES_QUESTIONS = [
    _q("Section 1: Lists", f"Create list 1..10. Print first 3, last 2, reverse.", "lst = list(range(1, 11))\nprint(lst[:3], lst[-2:], lst[::-1])"),
    _q("Section 1: Lists", "Append 99, extend [100,101], insert 0 at index 0.", "lst = [1, 2, 3]\nlst.append(99); lst.extend([100, 101]); lst.insert(0, 0)\nprint(lst)"),
    _q("Section 1: Lists", "Remove value 2, pop last, del index 0.", "lst = [0, 1, 2, 3]\nlst.remove(2); lst.pop(); del lst[0]\nprint(lst)"),
    _q("Section 1: Lists", "Sort descending without sort() — use sorted().", "lst = [3, 1, 4, 1, 5]\nprint(sorted(lst, reverse=True))"),
    _q("Section 1: Lists", "List comprehension: squares of evens 0..20.", "print([x*x for x in range(21) if x % 2 == 0])"),
    _q("Section 1: Lists", "Nested list 3x3 identity matrix.", "m = [[1 if i == j else 0 for j in range(3)] for i in range(3)]\nprint(m)"),
    _q("Section 1: Lists", "Flatten nested list [[1,2],[3,4]].", "nested = [[1, 2], [3, 4]]\nflat = [x for sub in nested for x in sub]\nprint(flat)"),
    _q("Section 1: Lists", "Copy list shallow vs deep for nested.", "import copy\na = [[1], [2]]\nb = a.copy()\nc = copy.deepcopy(a)\na[0][0] = 99\nprint(b, c)"),
    _q("Section 1: Lists", "Find index of 4 in list; count occurrences of 1.", "lst = [1, 4, 1, 2]\nprint(lst.index(4), lst.count(1))"),
    _q("Section 1: Lists", "Rotate list [1,2,3,4] left by 1.", "lst = [1, 2, 3, 4]\nlst = lst[1:] + lst[:1]\nprint(lst)"),
    _q("Section 2: Tuples & sets", "Create tuple, unpack, swap with tuple.", "t = (1, 2, 3)\na, b, c = t\nprint(a, b, c)"),
    _q("Section 2: Tuples & sets", "Set from list with duplicates; union/intersection.", "a = set([1, 2, 2, 3])\nb = {2, 3, 4}\nprint(a | b, a & b, a - b)"),
    _q("Section 2: Tuples & sets", "frozenset as dict key demo.", "fs = frozenset([1, 2])\nd = {fs: 'ok'}\nprint(d[fs])"),
    _q("Section 2: Tuples & sets", "Check subset/superset.", "a, b = {1, 2}, {1, 2, 3}\nprint(a.issubset(b), b.issuperset(a))"),
    _q("Section 2: Tuples & sets", "Symmetric difference of sets.", "print({1, 2, 3} ^ {3, 4})"),
    _q("Section 2: Tuples & sets", "Named tuple Point(x,y) distance from origin.", "from collections import namedtuple\nPoint = namedtuple('Point', 'x y')\np = Point(3, 4)\nprint((p.x**2 + p.y**2) ** 0.5)"),
    _q("Section 2: Tuples & sets", "Tuple unpacking with *rest.", "first, *rest = (1, 2, 3, 4)\nprint(first, rest)"),
    _q("Section 2: Tuples & sets", "Set comprehension {x%3 for x in range(10)}.", "print({x % 3 for x in range(10)})"),
    _q("Section 2: Tuples & sets", "Remove duplicates preserving order.", "def unique(seq):\n    seen = set()\n    out = []\n    for x in seq:\n        if x not in seen:\n            seen.add(x); out.append(x)\n    return out\nprint(unique([1,1,2,3,2]))"),
    _q("Section 2: Tuples & sets", "Merge two sets into sorted list.", "print(sorted({1, 2} | {2, 3}))"),
    _q("Section 3: Dictionaries", "Create dict, access, get with default.", "d = {'a': 1, 'b': 2}\nprint(d['a'], d.get('c', 0))"),
    _q("Section 3: Dictionaries", "Loop items; build reverse dict values→keys.", "d = {'a': 1, 'b': 2}\nrev = {v: k for k, v in d.items()}\nprint(rev)"),
    _q("Section 3: Dictionaries", "Merge dicts with | (3.9+) or update.", "a, b = {'x': 1}, {'y': 2}\nprint({**a, **b})"),
    _q("Section 3: Dictionaries", "defaultdict list — group items.", "from collections import defaultdict\ngroups = defaultdict(list)\nfor k, v in [('a', 1), ('a', 2), ('b', 3)]:\n    groups[k].append(v)\nprint(dict(groups))"),
    _q("Section 3: Dictionaries", "Counter on 'hello'.", "from collections import Counter\nprint(Counter('hello'))"),
    _q("Section 3: Dictionaries", "Sort dict by value descending.", "d = {'a': 3, 'b': 1, 'c': 2}\nprint(dict(sorted(d.items(), key=lambda x: x[1], reverse=True)))"),
    _q("Section 3: Dictionaries", "Dict comprehension: square keys 1..5.", "print({k: k*k for k in range(1, 6)})"),
    _q("Section 3: Dictionaries", "Pop item with default.", "d = {'a': 1}\nprint(d.pop('b', None))"),
    _q("Section 3: Dictionaries", "Setdefault to accumulate counts manually.", "counts = {}\nfor ch in 'banana':\n    counts[ch] = counts.get(ch, 0) + 1\nprint(counts)"),
    _q("Section 3: Dictionaries", "Nested dict access with .get chain safe.", "d = {'user': {'name': 'Sam'}}\nprint(d.get('user', {}).get('age', 'NA'))"),
    _q("Section 4: Comprehensions", "Dict comp filter: even squares.", "print({x: x*x for x in range(10) if x % 2 == 0})"),
    _q("Section 4: Comprehensions", "Set comp: len words > 3.", "words = ['ai', 'ml', 'data', 'science']\nprint({w for w in words if len(w) > 3})"),
    _q("Section 4: Comprehensions", "Nested list comp  multiplication table.", "print([[i*j for j in range(1, 4)] for i in range(1, 4)])"),
    _q("Section 4: Comprehensions", "Replace map/filter with comprehension.", "print([x*2 for x in range(10) if x % 2 == 0])"),
    _q("Section 4: Comprehensions", "Transpose matrix via zip.", "m = [[1,2,3],[4,5,6]]\nprint([list(row) for row in zip(*m)])"),
    _q("Section 4: Comprehensions", "Enumerate into dict.", "print({i: v for i, v in enumerate(['a', 'b'])})"),
    _q("Section 4: Comprehensions", "Filter None from list comp.", "print([x for x in [1, None, 2, None] if x is not None])"),
    _q("Section 4: Comprehensions", "Walrus in comprehension (if valid).", "data = ['', 'hi', '']\nprint([s for s in data if (t := s.strip())])"),
    _q("Section 4: Comprehensions", "Pairwise sums with zip.", "a, b = [1, 2, 3], [4, 5, 6]\nprint([x + y for x, y in zip(a, b)])"),
    _q("Section 4: Comprehensions", "Invert dict with duplicate values handling.", "d = {'a': 1, 'b': 1}\ninv = {}\nfor k, v in d.items():\n    inv.setdefault(v, []).append(k)\nprint(inv)"),
    _q("Section 5: Challenges", "Two-sum: find pair summing to target.", "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return seen[target - n], i\n        seen[n] = i\nprint(two_sum([2, 7, 11, 15], 9))"),
    _q("Section 5: Challenges", "Anagram check using Counter.", "from collections import Counter\ndef is_anagram(a, b):\n    return Counter(a.lower()) == Counter(b.lower())\nprint(is_anagram('listen', 'silent'))"),
    _q("Section 5: Challenges", "LRU cache manual OrderedDict.", "from collections import OrderedDict\nclass LRU:\n    def __init__(self, cap=2):\n        self.cap, self.od = cap, OrderedDict()\n    def get(self, k):\n        if k not in self.od: return -1\n        self.od.move_to_end(k); return self.od[k]\n    def put(self, k, v):\n        if k in self.od: self.od.move_to_end(k)\n        self.od[k] = v\n        if len(self.od) > self.cap: self.od.popitem(last=False)\nc = LRU(2); c.put(1,1); c.put(2,2); print(c.get(1))"),
    _q("Section 5: Challenges", "Stack using list push/pop.", "stack = []\nstack.append(1); stack.append(2)\nprint(stack.pop())"),
    _q("Section 5: Challenges", "Queue using collections.deque.", "from collections import deque\nq = deque([1, 2])\nq.append(3); print(q.popleft())"),
    _q("Section 5: Challenges", "Frequency top-k words.", "from collections import Counter\ntext = 'a b a c b a'\nprint(Counter(text.split()).most_common(2))"),
    _q("Section 5: Challenges", "Merge overlapping intervals.", "def merge_intervals(iv):\n    iv.sort(); out = [iv[0]]\n    for s, e in iv[1:]:\n        if s <= out[-1][1]: out[-1] = (out[-1][0], max(out[-1][1], e))\n        else: out.append((s, e))\n    return out\nprint(merge_intervals([(1,3),(2,6),(8,10)]))"),
    _q("Section 5: Challenges", "Group by key function.", "from itertools import groupby\ndata = sorted([('a',1),('a',2),('b',3)], key=lambda x: x[0])\nprint({k: [v for _, v in g] for k, g in groupby(data, key=lambda x: x[0])})"),
    _q("Section 5: Challenges", "Deep get path 'a.b.c' in nested dict.", "def deep_get(d, path, default=None):\n    for p in path.split('.'):\n        if not isinstance(d, dict): return default\n        d = d.get(p, default)\n    return d\nprint(deep_get({'a': {'b': {'c': 1}}}, 'a.b.c'))"),
    _q("Section 5: Challenges", "Rotate matrix 90 degrees.", "def rotate(m):\n    return [list(row)[::-1] for row in zip(*m)]\nprint(rotate([[1,2],[3,4]]))"),
]

DATA_STRUCTURES_INTERVIEW = [
    InterviewQA("Lists", "List vs tuple?", "List mutable, slower, more methods. Tuple immutable, hashable if elements hashable, faster."),
    InterviewQA("Lists", "Shallow vs deep copy?", "Shallow copies nested references; deep copies nested objects recursively."),
    InterviewQA("Sets", "When use set?", "Unique membership, fast O(1) average lookup, set algebra."),
    InterviewQA("Dicts", "Dict insertion order?", "Python 3.7+ preserves insertion order officially."),
    InterviewQA("Dicts", "Hashable keys requirement?", "Keys must be immutable/hashable — no list keys."),
    InterviewQA("Comprehensions", "List vs generator comp?", "[...] builds list; (...) gen exp lazy."),
    InterviewQA("Performance", " deque vs list for queue?", "deque O(1) pops from left; list O(n) pop(0)."),
    InterviewQA("Collections", "Counter use?", "Multiset counts; most_common, arithmetic."),
    InterviewQA("Collections", "defaultdict vs dict?", "defaultdict auto-creates missing keys with factory."),
    InterviewQA("Collections", "namedtuple benefit?", "Lightweight immutable records with named fields."),
    InterviewQA("Interview", "Time complexity list append?", "Amortized O(1); insert at front O(n)."),
    InterviewQA("Interview", "Dict collision handling?", "Open addressing in CPython 3.7+; hash table."),
    InterviewQA("Interview", "OrderedDict still needed?", "Rarely; dict ordered + move_to_end in OrderedDict for LRU."),
    InterviewQA("Interview", "Heapq module?", "Min-heap on list — heappush/heappop for priority queues."),
    InterviewQA("Interview", "bisect module?", "Binary search insertion in sorted lists."),
    InterviewQA("Interview", "Array module vs list?", "array stores homogeneous compact numeric types."),
    InterviewQA("Interview", "Slice assignment behavior?", "Can replace segment with different length list."),
    InterviewQA("Interview", "Tuple unpacking star?", "* captures remainder; works in py3 extended unpacking."),
    InterviewQA("Interview", "Set operations complexity?", "Average O(min(len(s), len(t))) for intersection."),
    InterviewQA("Interview", "Dict get vs try/except?", "get cleaner for missing keys; try for exceptional cases."),
    InterviewQA("Interview", "ChainMap use?", "Stack of dicts for scoped lookups without copying."),
    InterviewQA("Interview", "UserDict/UserList?", "Subclass wrappers when need to override methods cleanly."),
    InterviewQA("Interview", "Immutable dict alternative?", "types.MappingProxyType read-only view."),
    InterviewQA("Interview", "JSON serializable types?", "dict, list, str, int, float, bool, None — not set/tuple directly."),
    InterviewQA("Interview", "Big-O dict lookup?", "Average O(1), worst case O(n) under hash collisions."),
    InterviewQA("Interview", "When list comprehension too much?", "Nested deeply or side effects — use loop for clarity."),
    InterviewQA("Interview", "Sort stable?", "Python sort is stable — equal elements keep relative order."),
    InterviewQA("Interview", "key= lambda in sort?", "Computes sort key once per element — efficient pattern."),
    InterviewQA("Interview", "Reverse dict duplicate values?", "Must decide: overwrite, list values, or reject."),
    InterviewQA("Interview", "Memory view of slots?", "__slots__ reduces per-instance dict overhead in classes."),
]

OOP_QUESTIONS = [
    _q("Section 1: Classes", "Define class `Person` with __init__(name, age) and method introduce().", "class Person:\n    def __init__(self, name, age):\n        self.name, self.age = name, age\n    def introduce(self):\n        return f'I am {self.name}, {self.age}'\nprint(Person('Sam', 30).introduce())"),
    _q("Section 1: Classes", "Add class variable `species='Homo sapiens'` shared by all Person.", "class Person:\n    species = 'Homo sapiens'\n    def __init__(self, name): self.name = name\nprint(Person.species)"),
    _q("Section 1: Classes", "Implement `__str__` and `__repr__` for Person.", "class Person:\n    def __init__(self, name): self.name = name\n    def __str__(self): return self.name\n    def __repr__(self): return f'Person({self.name!r})'\np = Person('Sam')\nprint(str(p), repr(p))"),
    _q("Section 1: Classes", "Property: make `age` with getter/setter validation >=0.", "class Person:\n    def __init__(self, age): self.age = age\n    @property\n    def age(self): return self._age\n    @age.setter\n    def age(self, v):\n        if v < 0: raise ValueError('invalid')\n        self._age = v\np = Person(); p.age = 25\nprint(p.age)"),
    _q("Section 1: Classes", "classmethod `from_birth_year` alternative constructor.", "class Person:\n    def __init__(self, age): self.age = age\n    @classmethod\n    def from_birth_year(cls, year):\n        return cls(2024 - year)\nprint(Person.from_birth_year(1990).age)"),
    _q("Section 1: Classes", "staticmethod `is_adult(age)` on Person.", "class Person:\n    @staticmethod\n    def is_adult(age): return age >= 18\nprint(Person.is_adult(20))"),
    _q("Section 1: Classes", "Inheritance: Student(Person) adds student_id.", "class Person:\n    def __init__(self, name): self.name = name\nclass Student(Person):\n    def __init__(self, name, sid):\n        super().__init__(name); self.sid = sid\nprint(Student('A', 1).name)"),
    _q("Section 1: Classes", "Method overriding: Student introduce includes sid.", "class Person:\n    def introduce(self): return 'person'\nclass Student(Person):\n    def introduce(self): return f'student {self.sid}'\ns = Student(); s.sid = 42\nprint(s.introduce())"),
    _q("Section 1: Classes", "Use isinstance and issubclass checks.", "class A: pass\nclass B(A): pass\nprint(isinstance(B(), A), issubclass(B, A))"),
    _q("Section 1: Classes", "Abstract base: Animal with abstract speak using ABC.", "from abc import ABC, abstractmethod\nclass Animal(ABC):\n    @abstractmethod\n    def speak(self): ...\nclass Dog(Animal):\n    def speak(self): return 'woof'\nprint(Dog().speak())"),
    _q("Section 2: Encapsulation", "Private convention: _balance and name mangling __secret.", "class Account:\n    def __init__(self): self._balance = 0; self.__secret = 1\na = Account()\nprint(a._balance, a._Account__secret)"),
    _q("Section 2: Encapsulation", "Implement deposit/withdraw with balance check.", "class Account:\n    def __init__(self): self._balance = 0\n    def deposit(self, amt): self._balance += amt\n    def withdraw(self, amt):\n        if amt > self._balance: raise ValueError('funds')\n        self._balance -= amt\na = Account(); a.deposit(100); a.withdraw(30)\nprint(a._balance)"),
    _q("Section 2: Encapsulation", "Read-only property balance.", "class Account:\n    def __init__(self, b=0): self._balance = b\n    @property\n    def balance(self): return self._balance\na = Account(50)\nprint(a.balance)"),
    _q("Section 2: Encapsulation", "Composition: Car has Engine object.", "class Engine:\n    def start(self): return 'vroom'\nclass Car:\n    def __init__(self): self.engine = Engine()\nprint(Car().engine.start())"),
    _q("Section 2: Encapsulation", "Dataclass for Point x,y with auto __init__.", "from dataclasses import dataclass\n@dataclass\nclass Point:\n    x: float\n    y: float\nprint(Point(1, 2))"),
    _q("Section 2: Encapsulation", "Slots to restrict attributes.", "class Slim:\n    __slots__ = ('x',)\n    def __init__(self, x): self.x = x\ns = Slim(1)\nprint(s.x)"),
    _q("Section 2: Encapsulation", "Enum for Status ACTIVE/INACTIVE.", "from enum import Enum\nclass Status(Enum):\n    ACTIVE = 1\n    INACTIVE = 2\nprint(Status.ACTIVE.name)"),
    _q("Section 2: Encapsulation", "Magic __len__ on custom collection.", "class Bag:\n    def __init__(self, items): self.items = items\n    def __len__(self): return len(self.items)\nprint(len(Bag([1,2,3])))"),
    _q("Section 2: Encapsulation", "Magic __eq__ compare two Points.", "class Point:\n    def __init__(self, x, y): self.x, self.y = x, y\n    def __eq__(self, other):\n        return self.x == other.x and self.y == other.y\nprint(Point(1,2) == Point(1,2))"),
    _q("Section 2: Encapsulation", "Iterator protocol __iter__/__next__.", "class Counter:\n    def __init__(self, n): self.n, self.i = n, 0\n    def __iter__(self): return self\n    def __next__(self):\n        if self.i >= self.n: raise StopIteration\n        self.i += 1; return self.i\nprint(list(Counter(3)))"),
    _q("Section 3: Modules", "Import math and use sqrt, pi.", "import math\nprint(math.sqrt(16), math.pi)"),
    _q("Section 3: Modules", "from collections import Counter, defaultdict.", "from collections import Counter, defaultdict\nprint(Counter('aab'), defaultdict(list))"),
    _q("Section 3: Modules", "Create module-level __all__ = ['foo'] pattern demo.", "__all__ = ['foo']\ndef foo(): return 1\ndef _bar(): return 2\nprint(foo())"),
    _q("Section 3: Modules", "Use if __name__ == '__main__' in module pattern.", "def main():\n    print('module main')\nif __name__ == '__main__':\n    main()"),
    _q("Section 3: Modules", "Import with alias: import pandas as pd.", "import pandas as pd\nprint(pd.__name__)"),
    _q("Section 3: Modules", "Relative import concept — package __init__.py role.", "print('Packages group modules; __init__ runs on import')"),
    _q("Section 3: Modules", "Use pathlib.Path in module style.", "from pathlib import Path\nprint(Path('.').resolve())"),
    _q("Section 3: Modules", "Virtual env purpose — print sys.prefix.", "import sys\nprint(sys.prefix)"),
    _q("Section 3: Modules", "pip install -r requirements.txt purpose.", "print('Pin dependencies for reproducible environments')"),
    _q("Section 3: Modules", "Use functools.lru_cache on recursive fib.", "from functools import lru_cache\n@lru_cache\n\ndef fib(n):\n    return n if n < 2 else fib(n-1)+fib(n-2)\nprint(fib(30))"),
    _q("Section 4: Polymorphism", "Duck typing: classes with draw() method.", "class Circle:\n    def draw(self): return 'O'\nclass Square:\n    def draw(self): return '[]'\nfor s in [Circle(), Square()]:\n    print(s.draw())"),
    _q("Section 4: Polymorphism", "Operator overloading __add__ for Vector.", "class Vector:\n    def __init__(self, x, y): self.x, self.y = x, y\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)\nprint((Vector(1,2)+Vector(3,4)).x)"),
    _q("Section 4: Polymorphism", "Multiple inheritance MRO print.", "class A: pass\nclass B(A): pass\nclass C(A): pass\nclass D(B,C): pass\nprint(D.__mro__)"),
    _q("Section 4: Polymorphism", "Protocol/duck: file-like read().", "class Reader:\n    def read(self): return 'data'\ndef consume(f): return f.read()\nprint(consume(Reader()))"),
    _q("Section 4: Polymorphism", "Template method pattern skeleton.", "class Base:\n    def run(self):\n        self.step1(); self.step2()\n    def step1(self): print('s1')\n    def step2(self): print('s2')\nBase().run()"),
    _q("Section 4: Polymorphism", "Strategy pattern with callables.", "def add(a,b): return a+b\ndef mul(a,b): return a*b\nops = {'+': add, '*': mul}\nprint(ops['+'](2,3))"),
    _q("Section 4: Polymorphism", "Singleton pattern (simple module-level).", "class _Singleton:\n    pass\ninstance = _Singleton()\nprint(instance is instance)"),
    _q("Section 4: Polymorphism", "Factory function create_shape('circle').", "def create_shape(kind):\n    return {'circle': 'O', 'square': '[]'}[kind]\nprint(create_shape('circle'))"),
    _q("Section 4: Polymorphism", "Mixin class LoggerMixin.", "class LoggerMixin:\n    def log(self, msg): print(msg)\nclass Service(LoggerMixin):\n    pass\nService().log('ok')"),
    _q("Section 4: Polymorphism", "Compare @dataclass vs regular class boilerplate.", "from dataclasses import dataclass\n@dataclass\nclass User:\n    name: str\nprint(User('Sam'))"),
    _q("Section 5: Projects", "Design ExpenseTracker class: add, total, list.", "class ExpenseTracker:\n    def __init__(self): self.items = []\n    def add(self, amt, cat): self.items.append((amt, cat))\n    def total(self): return sum(a for a,_ in self.items)\net = ExpenseTracker(); et.add(10,'food'); et.add(5,'travel')\nprint(et.total())"),
    _q("Section 5: Projects", "Task class with priority enum and done flag.", "from enum import Enum\nclass Priority(Enum): LOW=1; HIGH=3\nclass Task:\n    def __init__(self, title, p=Priority.LOW):\n        self.title, self.p, self.done = title, p, False\nprint(Task('study', Priority.HIGH).p)"),
    _q("Section 5: Projects", "TaskManager add/complete/list_pending.", "class TaskManager:\n    def __init__(self): self.tasks = []\n    def add(self, t): self.tasks.append(t)\n    def complete(self, i): self.tasks[i].done = True\n    def pending(self): return [t for t in self.tasks if not t.done]"),
    _q("Section 5: Projects", "Serialize ExpenseTracker to dict JSON-ready.", "import json\nclass ExpenseTracker:\n    def __init__(self): self.items = []\n    def to_dict(self): return {'items': self.items}\net = ExpenseTracker(); et.items = [(1,'a')]\nprint(json.dumps(et.to_dict()))"),
    _q("Section 5: Projects", "Validate input in setter (positive amount).", "class Expense:\n    def __init__(self, amt): self.amount = amt\n    @property\n    def amount(self): return self._a\n    @amount.setter\n    def amount(self, v):\n        if v <= 0: raise ValueError\n        self._a = v\nprint(Expense(10).amount)"),
    _q("Section 5: Projects", "Unit test style assert for TaskManager.", "class Task:\n    def __init__(self): self.done = False\nclass TaskManager:\n    def __init__(self): self.tasks = []\n    def add(self, t): self.tasks.append(t)\nm = TaskManager(); m.add(Task())\nassert len(m.tasks) == 1"),
    _q("Section 5: Projects", "Use typing.List, Optional in class hints.", "from typing import List, Optional\nclass Bag:\n    items: List[int]\n    def __init__(self, items=None):\n        self.items = items or []\n    def first(self) -> Optional[int]:\n        return self.items[0] if self.items else None\nprint(Bag([1]).first())"),
    _q("Section 5: Projects", "Context manager class __enter__/__exit__.", "class Timer:\n    def __enter__(self): return self\n    def __exit__(self, *a): print('done')\nwith Timer():\n    pass"),
    _q("Section 5: Projects", "Compare inheritance vs composition for TaskManager storage.", "print('Composition: TaskManager HAS list of Task — flexible')"),
    _q("Section 5: Projects", "Design class diagram in comments for portfolio project.", "print('# ExpenseTracker -> List[Expense] ; methods: add, report')"),
    _q("Section 5: Projects", "Refactor procedural code into OOP — wrap sales summary.", "class SalesSummary:\n    def __init__(self, sales): self.sales = sales\n    def total(self): return sum(self.sales)\nprint(SalesSummary([1,2,3]).total())"),
]

OOP_INTERVIEW = [
    _interview("OOP basics", "What is a class vs object?", "A **class** is a blueprint; an **object** is an instance with its own state and behavior."),
    _interview("OOP basics", "Explain encapsulation, inheritance, polymorphism.", "Encapsulation hides internals; inheritance reuses/extends parent; polymorphism — same interface, different behavior."),
    _interview("Methods", "@classmethod vs @staticmethod?", "classmethod receives cls (alternate constructors); staticmethod is a namespaced utility without cls/self."),
    _interview("Methods", "What is `@property`?", "Controlled attribute access with getter/setter validation."),
    _interview("Design", "Composition vs inheritance?", "Prefer has-a over is-a when reuse doesn't imply subtype."),
    _interview("Design", "SOLID summary?", "SRP, OCP, Liskov substitution, Interface segregation, Dependency inversion."),
    _interview("Design", "When use dataclass?", "Reduce boilerplate for data-holding classes with auto __init__/__repr__."),
    _interview("Magic methods", "__str__ vs __repr__?", "__repr__ developer-unambiguous; __str__ user-readable."),
    _interview("Modules", "`if __name__ == '__main__'`?", "Runs only when file executed as script, not imported."),
    _interview("Patterns", "Decorator pattern in Python?", "@decorator wraps functions to add logging, timing, auth, etc."),
    _interview("Interview", "MRO?", "Method resolution order — C3 linearization for multiple inheritance."),
    _interview("Interview", "__slots__?", "Fixed attributes — saves memory, blocks arbitrary attrs."),
    _interview("Interview", "Iterator vs generator?", "Both lazy; generator uses yield syntax, simpler for streams."),
    _interview("Interview", "Abstract base classes?", "Enforce interface via @abstractmethod before instantiation."),
    _interview("Interview", "Testing classes?", "Test public methods; mock external I/O and dependencies."),
    _interview("Interview", "Type hints on methods?", "Document contracts; use mypy for static checks."),
    _interview("Interview", "Enum use case?", "Named constants — status codes, categories, safe comparisons."),
    _interview("Interview", "Context manager on class?", "Implement __enter__/__exit__ for resource cleanup."),
    _interview("Interview", "Namedtuple vs dataclass?", "namedtuple immutable; dataclass flexible defaults/mutability."),
    _interview("Interview", "Factory function pattern?", "Hide concrete class construction behind create_* API."),
    _interview("Interview", "Strategy pattern?", "Swap algorithms at runtime via shared interface."),
    _interview("Interview", "Mixin classes?", "Small reusable bases mixed into multiple subclasses."),
    _interview("Interview", "Private name mangling?", "__attr triggers _ClassName__attr — convention not security."),
    _interview("Interview", "super() in diamond inheritance?", "Follows MRO — calls next class in order, not only direct parent."),
    _interview("Interview", "Immutable objects?", "tuple, frozenset, str — safe as dict keys when hashable."),
    _interview("Interview", "Dependency injection?", "Pass dependencies into __init__ instead of hard-coding globals."),
    _interview("Interview", "Expenses/Task project OOP?", "Model domain entities as classes; separate persistence layer."),
    _interview("Interview", "When NOT to use OOP?", "Simple scripts, one-off ETL — functions may suffice."),
    _interview("Interview", "Duck typing?", "If it quacks like a duck — behavior matters, not explicit type hierarchy."),
    _interview("Interview", "Metaclass (brief)?", "Class of a class — advanced, rarely needed in DS day-to-day."),
]

FILE_IO_QUESTIONS = [
    _q("Section 1: pathlib", "List all files in repo root using Path.", "from pathlib import Path\nroot = REPO_ROOT\nprint([p.name for p in root.iterdir() if p.is_file()][:10])"),
    _q("Section 1: pathlib", "Check if DATA_DIR exists and is directory.", "print(DATA_DIR.exists(), DATA_DIR.is_dir())"),
    _q("Section 1: pathlib", "Join path to read sales CSV with Path / operator.", "p = DATA_DIR / 'AusApparalSales4thQrt2020.csv'\nprint(p.exists(), p.suffix)"),
    _q("Section 1: pathlib", "Create temp folder under subtopic if not exists.", "tmp = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp'\ntmp.mkdir(parents=True, exist_ok=True)\nprint(tmp.exists())"),
    _q("Section 1: pathlib", "Glob all *.csv in DATA_DIR.", "print(list(DATA_DIR.glob('*.csv'))[:3])"),
    _q("Section 1: pathlib", "Read text file basics with Path.read_text.", "sample = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/demo.txt'\nsample.write_text('hello aiml', encoding='utf-8')\nprint(sample.read_text(encoding='utf-8'))"),
    _q("Section 1: pathlib", "Write lines with Path.write_text.", "p = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/lines.txt'\np.write_text('line1\\nline2', encoding='utf-8')\nprint(p.read_text().splitlines())"),
    _q("Section 1: pathlib", "Get file size in bytes.", "p = DATA_DIR / 'AusApparalSales4thQrt2020.csv'\nprint(p.stat().st_size if p.exists() else 0)"),
    _q("Section 1: pathlib", "Resolve absolute path.", "print((DATA_DIR / 'loan_data.csv').resolve())"),
    _q("Section 1: pathlib", "Rename file with Path.rename.", "a = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/a.txt'\nb = a.with_name('b.txt')\na.write_text('x'); a.rename(b)\nprint(b.exists())"),
    _q("Section 2: read/write", "Open file with `with open` read mode.", "p = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/read.txt'\np.write_text('abc', encoding='utf-8')\nwith open(p, encoding='utf-8') as f:\n    print(f.read())"),
    _q("Section 2: read/write", "Read line by line into list.", "p = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/read.txt'\nwith open(p, encoding='utf-8') as f:\n    lines = f.readlines()\nprint(lines)"),
    _q("Section 2: read/write", "Append to file mode 'a'.", "p = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/log.txt'\nwith open(p, 'w', encoding='utf-8') as f: f.write('start\\n')\nwith open(p, 'a', encoding='utf-8') as f: f.write('more\\n')\nprint(p.read_text())"),
    _q("Section 2: read/write", "Write CSV manually without pandas.", "import csv\np = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/out.csv'\nwith open(p, 'w', newline='', encoding='utf-8') as f:\n    w = csv.writer(f); w.writerow(['a','b']); w.writerow([1,2])\nprint(p.read_text())"),
    _q("Section 2: read/write", "Read CSV with csv.DictReader.", "import csv\np = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/out.csv'\nwith open(p, encoding='utf-8') as f:\n    rows = list(csv.DictReader(f))\nprint(rows)"),
    _q("Section 2: read/write", "Use json.dump and json.load.", "import json\np = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/data.json'\nwith open(p, 'w', encoding='utf-8') as f: json.dump({'a': 1}, f)\nprint(json.load(open(p, encoding='utf-8')))"),
    _q("Section 2: read/write", "Pretty print JSON indent=2.", "import json\nprint(json.dumps({'x': [1,2]}, indent=2))"),
    _q("Section 2: read/write", "Read first 5 lines of large CSV without loading all.", "p = DATA_DIR / 'AusApparalSales4thQrt2020.csv'\nwith open(p, encoding='utf-8') as f:\n    for i, line in enumerate(f):\n        if i >= 5: break\n        print(line.strip())"),
    _q("Section 2: read/write", "Copy file with shutil.copy.", "import shutil\nsrc = DATA_DIR / 'loan_data.csv'\ndst = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/loan_copy.csv'\nif src.exists():\n    shutil.copy(src, dst)\n    print(dst.exists())"),
    _q("Section 2: read/write", "Delete temp file with Path.unlink.", "p = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/to_del.txt'\np.write_text('x'); p.unlink()\nprint(p.exists())"),
    _q("Section 3: pandas I/O", "Load sales CSV with pd.read_csv from DATA_DIR.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv')\nprint(df.head(2))"),
    _q("Section 3: pandas I/O", "Save dataframe head to csv index=False.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv')\nout = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/head.csv'\ndf.head(10).to_csv(out, index=False)\nprint(out.exists())"),
    _q("Section 3: pandas I/O", "Read only first 1000 rows with nrows.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', nrows=1000)\nprint(len(df))"),
    _q("Section 3: pandas I/O", "Specify dtype on read for memory.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', dtype={'State': 'category'})\nprint(df['State'].dtype)"),
    _q("Section 3: pandas I/O", "Handle parse_dates on Date column.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', parse_dates=['Date'])\nprint(df['Date'].dtype)"),
    _q("Section 3: pandas I/O", "Export to parquet if pyarrow available (try/except).", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', nrows=100)\nout = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/sample.parquet'\ntry:\n    df.to_parquet(out, index=False); print('parquet ok')\nexcept Exception as e:\n    print('skip parquet:', type(e).__name__)"),
    _q("Section 3: pandas I/O", "Read Excel if openpyxl — marketing xlsx in project optional.", "print('Use pd.read_excel(path, sheet_name=0) when xlsx available')"),
    _q("Section 3: pandas I/O", "Load HR dataset; save cleaned subset.", "df = pd.read_csv(DATA_DIR / 'HR_comma_sep.csv')\nout = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/hr_head.csv'\ndf.head(50).to_csv(out, index=False)"),
    _q("Section 3: pandas I/O", "Use compression gzip on to_csv.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', nrows=100)\nout = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/s.csv.gz'\ndf.to_csv(out, index=False, compression='gzip')\nprint(out.stat().st_size)"),
    _q("Section 3: pandas I/O", "Verify round-trip: read written csv equals head.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', nrows=5)\nout = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/rt.csv'\ndf.to_csv(out, index=False)\nprint(df.equals(pd.read_csv(out)))"),
    _q("Section 4: Exceptions", "Try/except FileNotFoundError.", "try:\n    open('no_such_file.txt')\nexcept FileNotFoundError as e:\n    print(type(e).__name__)"),
    _q("Section 4: Exceptions", "Raise ValueError with message.", "def parse_positive(x):\n    x = float(x)\n    if x <= 0: raise ValueError('must be positive')\n    return x\ntry:\n    parse_positive(-1)\nexcept ValueError as e:\n    print(e)"),
    _q("Section 4: Exceptions", "Custom exception class AppError.", "class AppError(Exception): pass\ntry:\n    raise AppError('fail')\nexcept AppError as e:\n    print(e)"),
    _q("Section 4: Exceptions", "else clause in try/except.", "try:\n    x = 1\nexcept Exception:\n    pass\nelse:\n    print('no error', x)"),
    _q("Section 4: Exceptions", "finally always runs demo.", "try:\n    x = 1\nfinally:\n    print('cleanup')"),
    _q("Section 4: Exceptions", "Chained exception raise from.", "try:\n    1/0\nexcept ZeroDivisionError as e:\n    err = e\ntry:\n    raise ValueError('bad') from err\nexcept ValueError as e:\n    print(e.__cause__)"),
    _q("Section 4: Exceptions", "Assert for development checks.", "x = [1,2,3]\nassert len(x) > 0, 'empty'\nprint('ok')"),
    _q("Section 4: Exceptions", "Logging instead of print for errors.", "import logging\nlogging.basicConfig(level=logging.INFO)\ntry:\n    1/0\nexcept ZeroDivisionError:\n    logging.exception('divide error')"),
    _q("Section 4: Exceptions", "Retry reading file 3 times.", "def read_with_retry(path, n=3):\n    for i in range(n):\n        try:\n            return Path(path).read_text(encoding='utf-8')\n        except FileNotFoundError:\n            if i == n-1: raise\nprint('pattern ok')"),
    _q("Section 4: Exceptions", "Validate CSV columns before processing.", "required = {'Date','Sales','State'}\ndf = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', nrows=1)\nmissing = required - set(df.columns)\nif missing: raise ValueError(f'missing {missing}')\nprint('columns ok')"),
    _q("Section 5: Real workflows", "Build load_dataset(name) with friendly errors.", "def load_dataset(name):\n    p = DATA_DIR / name\n    if not p.exists():\n        raise FileNotFoundError(f'Missing {name} in {DATA_DIR}')\n    return pd.read_csv(p)\nprint(load_dataset('loan_data.csv').shape)"),
    _q("Section 5: Real workflows", "Log processing steps to file.", "logp = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/run.log'\nwith open(logp, 'a', encoding='utf-8') as f:\n    f.write('loaded sales\\n')\nprint(logp.read_text())"),
    _q("Section 5: Real workflows", "Config JSON: read/write settings dict.", "import json\ncfgp = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/config.json'\ncfg = {'seed': 42, 'rows': 1000}\ncfgp.write_text(json.dumps(cfg), encoding='utf-8')\nprint(json.loads(cfgp.read_text()))"),
    _q("Section 5: Real workflows", "Walk directory tree with os.walk or Path.rglob.", "py_files = list(REPO_ROOT.rglob('practice.ipynb'))[:5]\nprint(len(py_files), 'notebooks found')"),
    _q("Section 5: Real workflows", "Environment variable for data path override.", "import os\npath = os.environ.get('AIML_DATA_DIR', str(DATA_DIR))\nprint(path)"),
    _q("Section 5: Real workflows", "Context manager for temp write then read.", "from contextlib import contextmanager\n@contextmanager\ndef temp_file(path):\n    p = Path(path); p.write_text('tmp', encoding='utf-8')\n    try: yield p\n    finally: p.unlink(missing_ok=True)\nwith temp_file(REPO_ROOT/'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/t.txt') as p:\n    print(p.read_text())"),
    _q("Section 5: Real workflows", "Merge multiple CSV chunks with concat.", "df = pd.read_csv(DATA_DIR / 'AusApparalSales4thQrt2020.csv', nrows=200)\nchunks = [df.iloc[:100], df.iloc[100:]]\nprint(pd.concat(chunks, ignore_index=True).shape)"),
    _q("Section 5: Real workflows", "Document data lineage in markdown file.", "md = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/lineage.md'\nmd.write_text('# Lineage\\nSource: datasets/shared\\n', encoding='utf-8')\nprint(md.read_text())"),
    _q("Section 5: Real workflows", "Checksum file size before/after copy.", "import shutil\nsrc = DATA_DIR / 'loan_data.csv'\ndst = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/loan2.csv'\nif src.exists():\n    shutil.copy2(src, dst)\n    print(src.stat().st_size == dst.stat().st_size)"),
    _q("Section 5: Real workflows", "Safe write: write temp then replace.", "target = REPO_ROOT / 'Course_01_Python_Foundations/05_file_io_exceptions/_tmp/safe.txt'\ntmp = target.with_suffix('.tmp')\ntmp.write_text('final', encoding='utf-8')\ntmp.replace(target)\nprint(target.read_text())"),
]

FILE_IO_INTERVIEW = [
    _interview("pathlib", "pathlib vs os.path?", "pathlib is OOP, composable with /, cross-platform."),
    _interview("Files", "Why `with open`?", "Guarantees file close on exceptions."),
    _interview("Files", "Text vs binary mode?", "Text decodes Unicode; binary for bytes/images."),
    _interview("CSV", "csv vs pandas?", "csv lightweight streaming; pandas analytics at scale."),
    _interview("JSON", "JSON types?", "dict, list, str, int, float, bool, None."),
    _interview("pandas I/O", "read_csv essentials?", "usecols, dtype, parse_dates, nrows, na_values."),
    _interview("Exceptions", "try/except/else/finally?", "else runs if no error; finally always cleanup."),
    _interview("Workflow", "DATA_DIR pattern?", "Central datasets/shared; notebooks find repo root dynamically."),
    _interview("Workflow", "Atomic writes?", "Write temp file then rename to avoid corruption."),
    _interview("Interview", "Large file strategies?", "chunksize, nrows, pyarrow, parquet, mmap."),
    _interview("Interview", "Encoding issues?", "Always specify utf-8; handle errors='replace' if needed."),
    _interview("Interview", "Git LFS?", "For files >100MB — pointer in git, blob stored separately."),
    _interview("Interview", "Pickle risks?", "Never unpickle untrusted data — RCE risk."),
    _interview("Interview", "Parquet vs CSV?", "Parquet columnar compressed typed — faster for analytics."),
    _interview("Interview", "Environment path override?", "AIML_DATA_DIR env var for CI/prod flexibility."),
    _interview("Interview", "Validate before ETL?", "Check columns, dtypes, row counts early."),
    _interview("Interview", "Logging vs print?", "Logging levels, files, production pipelines."),
    _interview("Interview", "shutil.copy2?", "Copies file + metadata."),
    _interview("Interview", "Path.rglob?", "Recursive glob from directory tree."),
    _interview("Interview", "Custom exceptions?", "Domain errors users can catch specifically."),
    _interview("Interview", "raise from?", "Chains exceptions preserving root cause."),
    _interview("Interview", "Compression gzip?", "Smaller disk, more CPU on read/write."),
    _interview("Interview", "Excel multiple sheets?", "read_excel(sheet_name=None) → dict of DataFrames."),
    _interview("Interview", "Round-trip integrity?", "Hash/checksum and assert shape dtypes after write."),
    _interview("Interview", "on_bad_lines?", "Skip or warn on malformed CSV rows (pandas)."),
    _interview("Interview", "Config JSON pattern?", "Store seed, paths, hyperparams outside code."),
    _interview("Interview", "Lineage documentation?", "Track source → transforms → output for audits."),
    _interview("Interview", "Retry on I/O?", "Transient network/disk errors — bounded retries with backoff."),
    _interview("Interview", "Contextlib suppress?", "Cleanly ignore expected exceptions in narrow scope."),
    _interview("Interview", "Home loan sample vs full?", "Sample in repo; full 158MB local/gitignored — document in README."),
]

COURSE_01_TOPICS = [
    TopicSpec(
        "Course_01_Python_Foundations/01_variables_datatypes",
        "Variables, Data Types & Operators",
        "Course 1",
        dataset=None,
        questions=VARIABLES_QUESTIONS,
        interview=VARIABLES_INTERVIEW,
    ),
    TopicSpec(
        "Course_01_Python_Foundations/02_control_flow_functions",
        "Control Flow & Functions",
        "Course 1",
        questions=CONTROL_FLOW_QUESTIONS,
        interview=CONTROL_FLOW_INTERVIEW,
    ),
    TopicSpec(
        "Course_01_Python_Foundations/03_data_structures",
        "Data Structures",
        "Course 1",
        questions=DATA_STRUCTURES_QUESTIONS,
        interview=DATA_STRUCTURES_INTERVIEW,
    ),
    TopicSpec(
        "Course_01_Python_Foundations/04_oop_modules",
        "OOP & Modules",
        "Course 1",
        extra_imports="from dataclasses import dataclass\n",
        questions=OOP_QUESTIONS,
        interview=OOP_INTERVIEW,
    ),
    TopicSpec(
        "Course_01_Python_Foundations/05_file_io_exceptions",
        "File I/O & Exceptions",
        "Course 1",
        dataset="sales",
        dataset_note="Practice reading/writing CSV, JSON, and shared datasets.",
        extra_imports="import pandas as pd\nimport json\nimport csv\nfrom pathlib import Path\n",
        questions=FILE_IO_QUESTIONS,
        interview=FILE_IO_INTERVIEW,
    ),
]
