"""
Course 2 Part 5 Q&A Banks: Data Wrangling, Visualization, and Regex/APIs
"""

C2_09_WRANGLING = [
    ("What are Hadley Wickham's three principles of Tidy Data?",
     "Tidy Data principles state: (1) Each variable must have its own column. (2) Each observation must have its own row. (3) Each type of observational unit forms a table. Tidy structure standardizes data manipulation, simplifies filtering, and aligns seamlessly with vectorization."),
    ("Differentiate between Missing Completely at Random (MCAR), Missing at Random (MAR), and Missing Not at Random (MNAR).",
     "MCAR: Missingness is entirely independent of observed and unobserved data (e.g. random sensor glitch); safe for complete-case deletion. MAR: Missingness depends systematically on other observed variables but not the missing value itself (e.g. men are less likely to report depression score, but within gender it is random); handled via multiple imputation. MNAR: Missingness depends on the unobserved value itself (e.g. wealthy individuals refusing to disclose high income); introduces non-ignorable bias."),
    ("What are the dangers of Mean Imputation for missing values?",
     "Mean imputation artificially reduces sample variance, distorts probability distributions, attenuates covariance and correlation between features, and under-estimates standard errors of regression coefficients, leading to artificially narrow confidence intervals and inflated Type I error rates."),
    ("Explain KNN Imputation and Iterative (MICE) Imputation.",
     "KNN Imputation finds the k-nearest neighbors using Euclidean distance on non-missing features and imputes the missing value as the average of neighbors. MICE (Multivariate Imputation by Chained Equations) models each missing feature as a function of all other features in an iterative round-robin cycle, capturing complex multivariate dependencies."),
    ("What is Winsorization and how does it handle extreme outliers?",
     "Winsorization caps extreme values at predefined percentiles (e.g. 1st and 99th percentiles) rather than discarding rows. Values below the 1st percentile are replaced by the 1st percentile value; values above the 99th percentile are replaced by the 99th percentile value, preserving sample size while taming extreme variance."),
    ("Explain the difference between Min-Max Normalization and Z-score Standardization.",
     "Min-Max Normalization: x_norm = (x - x_min) / (x_max - x_min), scaling values strictly to [0, 1]; highly sensitive to extreme outliers. Z-score Standardization: z = (x - μ) / σ, scaling data to zero mean and unit variance; handles unbounded distributions and assumes roughly Gaussian properties."),
    ("What is RobustScaler and when is it preferred over StandardScaler?",
     "RobustScaler centers data by subtracting the Median and scales by dividing by the Interquartile Range: x_scaled = (x - Q2) / (Q3 - Q1). Because both median and IQR are non-parametric order statistics, RobustScaler is immune to distortion by extreme outliers."),
    ("What is the Box-Cox transformation and when does it fail?",
     "The Box-Cox transformation stabilizes variance and transforms non-normal features into approximate Gaussian distributions via power parameter λ: y = (x^λ - 1) / λ for λ != 0, and ln(x) for λ = 0. It fails on negative numbers or zeros (requires x > 0). The Yeo-Johnson transformation extends Box-Cox to negative and zero values."),
    ("Explain One-Hot Encoding vs Target (Mean) Encoding for high-cardinality categorical variables.",
     "One-Hot Encoding creates a binary column per category, causing dimensionality explosion and severe sparsity on high-cardinality features (e.g. 50,000 ZIP codes). Target Encoding replaces each category with the average target value for that category, keeping dimensionality to 1 column. However, Target Encoding risks severe target leakage and overfitting unless smoothed using m-estimate or K-fold out-of-fold target encoding."),
    ("What is Target Leakage in feature preprocessing?",
     "Target leakage occurs when target information leaks into predictor features during data wrangling (e.g. calculating global target means across the entire dataset before train/test splitting, or including features like 'account_closed_date' when predicting customer churn)."),
    ("Explain string distance metrics: Levenshtein distance vs Jaro-Winkler distance.",
     "Levenshtein distance counts the minimum single-character edits (insertions, deletions, substitutions) to transform string A into string B. Jaro-Winkler measures character matching and transpositions, giving higher similarity weights to strings sharing common initial prefixes, making it ideal for deduplicating person names and addresses."),
    ("How do you perform fuzzy entity resolution and deduplication across messy datasets?",
     "Use blocking (grouping by soundex, zip code, or initial characters to reduce O(N²) comparisons) followed by approximate string matching (Levenshtein, Token Sort Ratio in rapidfuzz/fuzzywuzzy) and graph connected-components clustering to merge duplicate entities."),
    ("What is data reshaping using 'melt' vs 'pivot' in Pandas?",
     "'melt' converts wide-format data (measurements spread across multiple columns) into long tidy format (single column for variable names, single column for values). 'pivot' does the exact reverse, spreading unique values of an index into new columns."),
    ("How do you handle date/time inconsistencies across different data sources?",
     "Parse using 'pd.to_datetime(col, errors='coerce', utc=True)'. Standardize all timestamps to UTC immediately to eliminate timezone ambiguities and daylight saving time jumps. Extract cyclical features (sine/cosine of hour or day of year) for machine learning models."),
    ("What are cyclical features and why shouldn't hour-of-day be fed as raw integers (0-23)?",
     "Hours 23 (11 PM) and 0 (midnight) are contiguous in real time (distance = 1 hour), but as raw integers, their numerical distance is 23. Encoding hour as cyclical features: x_sin = sin(2π * hour / 24) and x_cos = cos(2π * hour / 24) maps time onto a continuous 2D unit circle, preserving physical temporal continuity."),
    ("What is data sanitization and whitespace trimming?",
     "Data sanitization strips invisible control characters, non-breaking spaces ('\\u00a0'), leading/trailing whitespaces ('.str.strip()'), and normalizes Unicode strings via 'unicodedata.normalize(\"NFKD\", text)' to eliminate homoglyph discrepancies."),
    ("Explain how to detect and resolve duplicate records with contradictory fields.",
     "Identify duplicates using primary candidate keys. For contradictory non-key fields: (1) apply business conflict-resolution rules (e.g. retain record with latest timestamp), (2) mark as conflicting and route to manual review, or (3) compute consensus/median values across matching entries."),
    ("What is an Isolation Forest and how does it detect anomalies during data wrangling?",
     "Isolation Forest builds ensembles of random trees that isolate individual anomalies by randomly selecting features and split values. Because anomalies are few and structurally different, they are isolated in fewer tree splits (shallow tree depth) compared to normal dense points, providing fast, non-parametric multi-dimensional outlier detection."),
    ("Explain the difference between complete-case analysis and available-case analysis.",
     "Complete-case analysis (listwise deletion) drops any row with even a single missing value, discarding valuable data and reducing sample size. Available-case analysis (pairwise deletion) calculates statistics using all rows that have data present for the specific pair of variables being analyzed, but can result in mathematically invalid non-positive-definite covariance matrices."),
    ("How does frequency encoding work for categorical features?",
     "Frequency encoding replaces each categorical value with its relative frequency (count / total_rows) in the training dataset. It is useful for tree-based models where the rarity of a category carries predictive signal."),
    ("What is the dummy variable trap and how do you avoid it?",
     "The dummy variable trap occurs when all K categories of a feature are converted into K binary columns, creating perfect linear dependence (collinearity) because the sum of all columns equals the intercept column (1). Avoid by dropping one column ('drop_first=True' in pd.get_dummies), retaining K - 1 dummy variables."),
    ("What is the difference between ordinal encoding and nominal one-hot encoding?",
     "Ordinal encoding maps ordered categories to integers that reflect natural ranking (e.g. Low=1, Medium=2, High=3). One-hot encoding creates independent binary indicator columns for unordered nominal categories (e.g. Red, Blue, Green) to prevent models from learning false numerical rank relationships."),
    ("How do you handle outliers in skewed target variables in regression models?",
     "Apply a monotonic non-linear transformation such as natural log (log1p(y) = ln(1 + y)) to compress long right tails, stabilize residual variance, and normalize error distributions. After prediction, invert using expm1(ŷ)."),
    ("Explain data binning (discretization) and its trade-offs.",
     "Binning groups continuous values into discrete intervals (e.g. age groups: 18-25, 26-35). Trade-offs: it handles non-linear relationships and tames outliers, but destroys within-bin variance, reduces statistical power, and introduces arbitrary boundary discontinuities."),
    ("What is an entity-relationship diagram (ERD) in relational data wrangling?",
     "An ERD visually models entities (tables), their attributes (columns), and relationships (one-to-one, one-to-many, many-to-many) governed by Primary Keys and Foreign Keys, ensuring relational join integrity during pipeline development."),
    ("How do you detect structural data anomalies (like trailing spaces or casing differences)?",
     "Group by lowercase/stripped strings and compare unique counts: 'df['category'].str.lower().str.strip().nunique() vs df['category'].nunique()'. If lower/stripped unique count is smaller, casing or whitespace inconsistencies exist."),
    ("Explain data validation frameworks like Great Expectations or Pydantic.",
     "These frameworks enforce automated declarative data quality test suites ('expectations') at pipeline boundaries (e.g. asserting column values are non-null, within specific ranges, or matching regex patterns), halting execution before bad data enters machine learning models."),
    ("What is the difference between forward-fill and linear interpolation for missing sensor data?",
     "Forward-fill assumes step-function dynamics (value stays flat until new reading arrives). Linear interpolation assumes continuous linear transition between known endpoints, which is more physically realistic for temperature, speed, or pressure sensors."),
    ("How do you safely split data into Train, Validation, and Test sets without data snooping?",
     "Perform the random or temporal train/test split as the FIRST step before ANY imputation, scaling, outlier removal, or feature engineering. Compute all transformation parameters (mean, std, min, max, target encodings) strictly on the Training split, and apply those frozen parameters to Validation and Test sets."),
    ("What is data lineage and why is it crucial in enterprise AI systems?",
     "Data lineage tracks the complete lifecycle of data: origin source, transformations applied, intermediate staging tables, and downstream ML models. It provides auditability, regulatory compliance (GDPR right to explanation), faster root cause debugging, and impact analysis.")
]

C2_10_VIZ = [
    ("Explain the Grammar of Graphics framework underlying Matplotlib and Seaborn.",
     "The Grammar of Graphics decomposes charts into formal semantic components: Data, Aesthetic Mappings (mapping variables to x, y, color, size, shape), Geometric Objects (geom_point, geom_bar), Scales, Coordinate Systems (Cartesian, polar), and Facets (multi-panel small multiples)."),
    ("What is the difference between Matplotlib's Object-Oriented (OO) API and 'pyplot' state-machine API?",
     "The 'pyplot' state-machine API ('plt.plot()') implicitly tracks current figure and axes, which is convenient for quick interactive notebooks but fragile in complex scripts. The Object-Oriented API ('fig, ax = plt.subplots()') explicitly references Figure and Axes objects, enabling precise multi-panel layouts, styling, and reusable plotting functions."),
    ("When should you choose a Box Plot vs a Violin Plot vs a KDE Plot?",
     "Box Plot: summarizes five-number summary and flags discrete outliers, but hides multimodal distributions. KDE Plot: visualizes continuous probability density shape and multimodality, but lacks quartile benchmarks. Violin Plot: combines box plot markers inside a mirrored KDE distribution, displaying both summary quartiles and probability density shape."),
    ("Explain the difference between a Bar Plot and a Histogram.",
     "A Bar Plot visualizes categorical variables: bars represent discrete categories, bar widths are arbitrary, and spaces separate bars. A Histogram visualizes continuous numerical distributions: the x-axis is segmented into contiguous, equal-width quantitative bins, and bars touch to reflect continuity."),
    ("What is a Heatmap and how is it used to visualize correlation matrices?",
     "A Heatmap visualizes a 2D matrix where cell values are mapped to a continuous color gradient. In correlation analysis ('sns.heatmap(df.corr(), annot=True, cmap=\"coolwarm\", vmin=-1, vmax=1)'), it immediately highlights collinear feature pairs and feature-target associations."),
    ("What are Small Multiples (Faceting) and why are they effective?",
     "Faceting ('sns.FacetGrid' or 'sns.catplot(col=\"Category\")') splits data across multiple subplots using the same scale and coordinate axes. It allows comparison of complex multivariate relationships across categories without overcrowding a single plot with overlapping visual clutter."),
    ("Explain perceptual color palettes: Diverging, Sequential, and Qualitative.",
     "Sequential: for continuous ordered data progressing from low to high (e.g. 'Blues', 'Viridis'). Diverging: for data with a meaningful critical midpoint (e.g. zero, mean) deviating in two opposing directions (e.g. 'coolwarm', 'RdBu'). Qualitative: for unordered categorical groups where colors must have equal perceptual weight and distinct hues (e.g. 'Set2', 'tab10')."),
    ("Why is the 'jet' or 'rainbow' colormap strongly discouraged in scientific visualization?",
     "Rainbow colormaps lack perceptual uniformity: non-linear changes in perceived brightness create artificial visual boundaries and false gradients that do not exist in the data, and they are completely unreadable for colorblind viewers. Use perceptually uniform colormaps like 'viridis', 'plasma', or 'magma'."),
    ("What is the Ink-to-Data Ratio (Edward Tufte's principle)?",
     "Tufte's Data-Ink ratio is the proportion of graphic ink dedicated to displaying non-redundant actual data information: Data-Ink / Total Ink. High-quality charts maximize this ratio by removing 'chartjunk' (excessive 3D effects, heavy gridlines, redundant legends, unnecessary borders)."),
    ("How do you resolve visual overplotting in scatter plots with 100,000+ points?",
     "Techniques: (1) reduce point opacity ('alpha=0.1'), (2) decrease marker size, (3) use 2D hexagonal binning ('plt.hexbin()') or 2D KDE contours, (4) use scatter plots with rasterization ('rasterized=True'), or (5) use Datashader for billion-point interactive rendering."),
    ("What is the difference between 'sns.scatterplot()' and 'sns.regplot()'?",
     "'sns.scatterplot()' plots raw data points with aesthetic encodings (hue, style, size). 'sns.regplot()' plots points, fits a linear regression trendline, and calculates a 95% bootstrap confidence interval band for the regression line."),
    ("Explain a Pairplot ('sns.pairplot') and its utility in preliminary EDA.",
     "A Pairplot creates an N x N matrix of subplots showing pairwise scatter plots for all numerical features, with univariate distributions (histograms or KDEs) on the diagonal. It rapidly exposes non-linear clusters, outliers, and collinearity across all feature pairs."),
    ("What is a Residual Plot and what visual patterns indicate model misspecification?",
     "A residual plot graphs model residuals (y - ŷ) on the y-axis against predicted values ŷ on the x-axis. A healthy linear model shows a random, symmetric cloud of points centered around zero with constant variance. U-shaped patterns indicate non-linear relationships missing from the model; funnel-shaped spreads indicate heteroscedasticity."),
    ("How do you visualize high-dimensional data (e.g. 100+ features) in 2D?",
     "Techniques: (1) t-SNE (t-Distributed Stochastic Neighbor Embedding) preserves local neighborhood structure, (2) UMAP (Uniform Manifold Approximation and Projection) preserves both local and global manifold structure with faster computation, and (3) PCA projects along top linear variance axes."),
    ("What is the difference between 'fig.savefig()' and 'plt.show()' in headless server environments?",
     "'plt.show()' requires an interactive GUI display backend (like TkAgg, Qt); on headless servers or CI/CD pipelines without X11, it crashes with display errors. 'fig.savefig()' writes image files directly to disk using non-interactive backends (like 'Agg'). Set 'matplotlib.use(\"Agg\")' at script start."),
    ("Explain how to configure secondary y-axes in Matplotlib ('ax.twinx()').",
     "'ax2 = ax.twinx()' creates a twin Axes sharing the same x-axis but maintaining an independent y-axis scale. Useful for plotting related metrics with different units simultaneously (e.g. advertising spend in USD on left axis vs conversion rate percentage on right axis)."),
    ("What is an empirical cumulative distribution function (ECDF) plot and why is it superior to histograms?",
     "An ECDF plot ('sns.ecdfplot(x)') maps every single data point to its cumulative percentile rank without binning. Unlike histograms, ECDF requires no arbitrary bin width choices, shows all data points, and allows reading percentiles and medians directly."),
    ("How does Matplotlib handle layout adjustments with 'tight_layout()' and 'constrained_layout'?",
     "'plt.tight_layout()' automatically adjusts subplot parameters and margins so that tick labels, axis titles, and subplot borders do not overlap. 'layout=\"constrained\"' in subplots provides dynamic padding optimization during resizing."),
    ("What is a JointGrid ('sns.jointplot')?",
     "A JointGrid combines a central bivariate plot (scatter plot, 2D KDE, or hexbin) with aligned marginal univariate plots (histograms/KDEs) along the top and right margins, displaying both joint relationships and individual distributions simultaneously."),
    ("How do you visualize confusion matrices effectively for multi-class classification?",
     "Use 'ConfusionMatrixDisplay.from_predictions()' or 'sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\")' with true labels on rows and predicted labels on columns. Normalize by row ('normalize=\"true\"') to display recall percentages per class, highlighting confusion between specific classes."),
    ("What is an ROC curve and Precision-Recall curve visualization?",
     "ROC curve plots True Positive Rate (Sensitivity) vs False Positive Rate (1 - Specificity) across all classification thresholds, displaying the diagonal random baseline. Precision-Recall curve plots Precision vs Recall across thresholds, showing the horizontal baseline equal to class prevalence (preferred for imbalanced data)."),
    ("Explain Andrews Curves and Parallel Coordinates for multivariate visualization.",
     "Parallel Coordinates plots each high-dimensional sample as a connected line across parallel vertical axes representing individual features. Andrews Curves transforms each sample's features into coefficients of a Fourier series, plotting smooth curves where clusters of points form closely grouped wave patterns."),
    ("How do you ensure accessibility in data visualizations for colorblind users?",
     "Use colorblind-safe palettes (e.g. 'cividis', 'colorblind' in Seaborn), combine color with secondary aesthetic channels (e.g. differing line styles '--', ':', or distinct marker shapes 'o', 's', '^'), and directly label lines/bars rather than relying solely on separate color legends."),
    ("What is a Dendrogram and how does it visualize hierarchical clustering?",
     "A Dendrogram is a tree diagram showing the taxonomic sequence of nested clusters in Agglomerative Hierarchical Clustering. The vertical axis represents the linkage distance at which clusters merge; cutting the dendrogram horizontally at a specific height yields discrete cluster assignments."),
    ("Explain the difference between static, interactive, and streaming visualizations.",
     "Static: fixed bitmap/vector files (PNG, SVG via Matplotlib). Interactive: client-side web charts supporting zooming, panning, tooltips, and filtering (Plotly, D3.js). Streaming: real-time live-updating dashboards that consume event streams via WebSockets (Grafana, Dash)."),
    ("How do you plot time-series data with missing date gaps without distorting visual continuity?",
     "Reindex the DataFrame against a complete 'pd.date_range()', then plot using explicit date objects on the x-axis so Matplotlib's DateLocator and DateFormatter scale intervals accurately according to calendar elapsed time rather than row index numbers."),
    ("What is a Waterfall Chart and where is it used in business analytics?",
     "A waterfall chart displays how an initial value (e.g. beginning quarterly revenue) increases or decreases through a sequential series of positive and negative adjustments (new sales, discounts, churn) to reach a final ending value."),
    ("How do you annotate specific points or threshold lines in Matplotlib?",
     "Use 'ax.axhline(y_val, color=\"red\", linestyle=\"--\")' for horizontal benchmark lines. Use 'ax.annotate(\"text\", xy=(x, y), xytext=(x_off, y_off), arrowprops=dict(arrowstyle=\"->\"))' to draw callout text boxes with connecting arrows pointing to key data points."),
    ("What is the difference between vector graphics (SVG/PDF) and raster graphics (PNG/JPEG) for reports?",
     "Raster graphics (PNG) store data as a fixed grid of pixels; zooming causes pixelation and blurriness. Vector graphics (SVG, PDF) store graphical shapes as mathematical vectors (lines, curves, polygons), allowing infinite crisp scaling for high-resolution print publications and responsive web displays."),
    ("How do you create customized multi-panel layouts using 'GridSpec' in Matplotlib?",
     "'matplotlib.gridspec.GridSpec(nrows, ncols)' partitions figure space into a flexible grid. Individual axes can span multiple rows and columns: 'ax1 = fig.add_subplot(gs[0, :])' (full-width top header) and 'ax2 = fig.add_subplot(gs[1, 0])' (bottom left panel).")
]

C2_11_REGEX_APIS = [
    ("Explain greedy vs non-greedy (lazy) quantifiers in regular expressions.",
     "Greedy quantifiers ('*', '+', '{m,n}') match as many characters as possible while still allowing the overall pattern to match. Adding a '?' makes them lazy/non-greedy ('*?', '+?'), matching the absolute minimum number of characters required to satisfy the expression. For example, matching '<.*>' on '<p>hello</p>' matches the full string greedily, while '<.*?>' matches just '<p>'."),
    ("What are regex Lookahead and Lookbehind assertions (Zero-Width Assertions)?",
     "Zero-width assertions match a position in text based on what follows or precedes it without consuming characters in the match result. Positive lookahead '(?=pattern)', negative lookahead '(?!pattern)', positive lookbehind '(?<=pattern)', and negative lookbehind '(?<!pattern)'. Example: '(?<=\\$)\\d+' extracts digits preceded by a dollar sign without including the '$'."),
    ("Explain the difference between 're.match()', 're.search()', and 're.findall()'.",
     "'re.match()' checks for a match ONLY at the very beginning of the string. 're.search()' scans the entire string and returns the first Match object found anywhere. 're.findall()' scans the entire string and returns all non-overlapping matches as a list of strings or tuples."),
    ("What is the purpose of 're.compile()' and when should it be used?",
     "'re.compile(pattern)' compiles a regex string into a reusable RegexObject bytecode in memory. It improves performance when the same regex is executed repeatedly across thousands or millions of text records, avoiding re-parsing and compiling overhead on every iteration."),
    ("How do capturing groups '(...)' differ from non-capturing groups '(?:...)'?",
     "Capturing groups '(...)' extract the matched substring, storing it in match groups accessible via 'match.group(1)'. Non-capturing groups '(?:...)' group expressions logically (for quantifiers or alternation) without allocating memory to capture or store the substring, improving execution speed."),
    ("What are Named Capturing Groups and how do you access them?",
     "Named capturing groups use the syntax '(?P<name>pattern)'. Extracted values can be accessed by name: 'match.group('name')' or extracted into a dictionary via 'match.groupdict()', making regex parsing code self-documenting and resilient to group reordering."),
    ("Explain regex catastrophic backtracking and how to prevent it.",
     "Catastrophic backtracking occurs when nested ambiguous quantifiers (e.g. '(a+)+$') evaluate against non-matching strings (e.g. 'aaaaaX'). The engine explores an exponential number of combinatorial paths (O(2^N)), freezing the CPU (ReDoS attack). Prevent by using atomic grouping, possessive quantifiers, or avoiding nested variable-length quantifiers."),
    ("What is RESTful API architecture and what are its core architectural constraints?",
     "REST (Representational State Transfer) constraints: (1) Client-Server separation, (2) Statelessness (no client session state stored on server), (3) Cacheability, (4) Uniform Interface (resource identification via URIs, self-descriptive messages), (5) Layered System (proxies, load balancers), and (6) Code-on-Demand (optional)."),
    ("Explain the standard HTTP request methods and their idempotency.",
     "GET: retrieves a resource (safe, idempotent). POST: creates a new subordinate resource (neither safe nor idempotent). PUT: creates or completely replaces a resource (idempotent). PATCH: partially updates a resource (non-idempotent by default). DELETE: removes a resource (idempotent). Idempotent means multiple identical requests produce the same server state as a single request."),
    ("Differentiate between HTTP status code ranges: 2xx, 3xx, 4xx, and 5xx.",
     "2xx: Success (200 OK, 201 Created, 204 No Content). 3xx: Redirection (301 Moved Permanently, 304 Not Modified). 4xx: Client Error (400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 429 Too Many Requests). 5xx: Server Error (500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable)."),
    ("What is the difference between 401 Unauthorized and 403 Forbidden?",
     "401 Unauthorized means authentication is required and has failed or has not yet been provided (missing/invalid credentials/token). 403 Forbidden means the server understands the client's identity (authenticated), but the client lacks permission/authorization to access the requested resource."),
    ("How do API Rate Limiting algorithms work (Token Bucket vs Leaky Bucket)?",
     "Token Bucket: tokens are added to a bucket at a constant rate up to capacity; each request consumes a token, allowing bursts of requests up to bucket capacity. Leaky Bucket: requests enter a FIFO queue and leak out at a strictly constant rate, smoothing traffic and enforcing rigid throughput limits."),
    ("What is Exponential Backoff with Jitter in API client pipelines?",
     "When an API returns 429 (Rate Limit) or 503 (Unavailable), exponential backoff doubles the wait time between successive retry attempts (e.g. 1s, 2s, 4s, 8s). Adding random 'jitter' (random noise to wait time) desynchronizes retries from concurrent client threads, preventing the 'Thundering Herd' problem on the server."),
    ("Explain OAuth 2.0 authorization framework and Bearer Tokens.",
     "OAuth 2.0 delegates user authorization to a third-party service without sharing user passwords. An authorization server issues a short-lived Bearer Token (access token). The client sends this token in the HTTP Authorization header ('Authorization: Bearer <token>') to access protected API endpoints."),
    ("What is JWT (JSON Web Token) and what are its three components?",
     "JWT is a compact, URL-safe, digitally signed token consisting of three Base64URL-encoded parts separated by dots: Header (algorithm & token type), Payload (claims: user id, roles, expiration time 'exp'), and Signature (cryptographic HMAC-SHA256 or RSA signature verifying payload integrity)."),
    ("Explain the difference between 'json.loads()' and 'json.load()'.",
     "'json.loads(str)' parses a JSON formatted string into a Python dictionary/list. 'json.load(fp)' reads from a file pointer or stream directly, parsing the stream without loading the entire raw file into memory as a separate string."),
    ("What causes a JSONDecodeError and how do you handle it defensively?",
     "JSONDecodeError occurs when parsing malformed JSON (trailing commas, single quotes instead of double quotes, unquoted keys, truncated streams). Handle via 'try-except json.JSONDecodeError' and sanitize using regex or libraries like 'json5'."),
    ("How does pagination work in REST APIs (Offset-based vs Cursor-based)?",
     "Offset-based ('?page=2&limit=50') uses SQL OFFSET; it is simple but suffers from performance degradation on large tables (O(N) database scans) and produces duplicate or skipped items if rows are inserted between page queries. Cursor-based ('?cursor=eyJpZCI6MTB9') uses indexed sequential IDs, guaranteeing O(1) database lookups and stable pagination across concurrent writes."),
    ("What are Webhooks and how do they differ from polling APIs?",
     "Polling repeatedly queries an API at regular intervals to check for updates, wasting bandwidth and incurring latency. Webhooks are event-driven HTTP push notifications: the server sends an asynchronous HTTP POST request to the client's designated webhook URL the moment an event occurs."),
    ("Explain GraphQL and how it solves Over-fetching and Under-fetching.",
     "REST APIs often return fixed payloads with redundant fields (over-fetching) or require multiple chained API calls to assemble related resources (under-fetching). GraphQL provides a single endpoint where clients submit structured queries requesting the exact fields and nested relationships needed, returned in a single predictable response."),
    ("How do you stream large JSON responses from an API without exhausting memory in Python?",
     "Use the 'requests' library with 'stream=True': 'response = requests.get(url, stream=True)'. Process chunks iteratively using 'response.iter_lines()' or use 'ijson' (iterative JSON parser) to parse nested JSON elements as a stream of Python objects without loading the multi-gigabyte file into RAM."),
    ("What is CORS (Cross-Origin Resource Sharing) and why does it exist?",
     "CORS is a browser security mechanism that restricts web applications running at one origin from requesting resources from a different origin. Servers declare allowed origins, methods, and headers via HTTP response headers ('Access-Control-Allow-Origin: *') to prevent malicious cross-site data theft."),
    ("What is API Idempotency-Key and why is it essential for payment and mutation APIs?",
     "An Idempotency-Key is a unique client-generated UUID sent in headers ('Idempotency-Key: uuid'). If a network timeout occurs and the client retries the request, the server detects the key, skips re-executing the financial charge or mutation, and returns the cached response of the original operation."),
    ("How do you handle API authentication using session cookies vs API tokens?",
     "Session cookies are stored automatically by browsers and sent on every request; vulnerable to Cross-Site Request Forgery (CSRF). API tokens (Bearer/JWT) are stored in client application state and sent explicitly in Authorization headers, immune to CSRF and suitable for stateless mobile and microservice architectures."),
    ("What is the difference between synchronous and asynchronous HTTP requests in Python?",
     "Synchronous libraries ('requests', 'urllib') block the execution thread until the server responds, limiting throughput to 1 request at a time per thread. Asynchronous libraries ('aiohttp', 'httpx') use Python's 'asyncio' event loop to dispatch thousands of concurrent non-blocking HTTP requests across a single thread."),
    ("Explain how to validate API request and response schemas using Pydantic.",
     "Pydantic models define expected fields, types, and constraints via Python type annotations. Calling 'MyModel.model_validate(json_data)' parses the input, coerces compatible types, and raises structured 'ValidationError' exceptions if required fields are missing or types are violated."),
    ("What are query parameters vs path parameters in REST URLs?",
     "Path parameters identify a specific hierarchical resource: '/users/{user_id}/orders/{order_id}'. Query parameters filter, sort, or paginate that resource collection: '/users?role=admin&sort=created_at&limit=10'."),
    ("What is OpenAPI (Swagger) specification?",
     "OpenAPI is a machine-readable JSON/YAML standard for describing RESTful APIs. It documents endpoints, request parameters, response schemas, and authentication methods, enabling automatic interactive documentation generation, client SDK generation, and mock servers."),
    ("How do you sanitize text before passing it to Regex engines to prevent ReDoS?",
     "Use 're.escape(user_string)' to escape all special regex metacharacters (*, +, ?, ^, $, (, ), [, ], {, }, |, \\) when incorporating untrusted user input into regex patterns, preventing pattern injection and catastrophic backtracking attacks."),
    ("What is gRPC and how does it compare to REST/JSON APIs?",
     "gRPC is a high-performance RPC framework developed by Google. It uses Protocol Buffers (compact binary serialization) over HTTP/2 (multiplexed streaming, header compression) instead of plain-text JSON over HTTP/1.1. It is 5x–10x faster and strictly typed, making it standard for internal microservices.")
]

print("Course 2 Part 5 banks loaded successfully.")
