"""
Course 2 Q&A Bank: 11 Subtopics x 30 High-Yield Interview Questions
"""

C2_01_INTRO = [
    ("Explain the complete Data Science lifecycle (CRISP-DM phases).",
     "CRISP-DM consists of 6 iterative phases: (1) Business Understanding (defining KPIs, problem formulation), (2) Data Understanding (collection, EDA, identifying data quality issues), (3) Data Preparation (cleaning, feature engineering, imputation, normalization), (4) Modeling (selecting algorithms, training, tuning), (5) Evaluation (assessing against business metrics and statistical benchmarks), and (6) Deployment (monitoring data drift, serving predictions via API or batch pipelines)."),
    ("Differentiate between Descriptive, Diagnostic, Predictive, and Prescriptive analytics.",
     "Descriptive: 'What happened?' (e.g. historical sales dashboards). Diagnostic: 'Why did it happen?' (e.g. root cause analysis, correlation breakdowns). Predictive: 'What is likely to happen?' (e.g. churn forecasting, demand prediction models). Prescriptive: 'What action should we take?' (e.g. price optimization algorithms, automated inventory reordering)."),
    ("What is the difference between structured, semi-structured, and unstructured data?",
     "Structured data has a strict, predefined tabular schema (e.g. SQL relational databases, CSV files). Semi-structured data possesses organizational markers without a rigid tabular schema (e.g. JSON documents, XML, NoSQL documents). Unstructured data lacks any conceptual schema (e.g. raw text, audio files, video streams, medical imaging scans)."),
    ("Explain the difference between a population and a sample in data analysis.",
     "A population is the entire universe of entities or observations of interest (e.g. all 100 million retail transactions in a year). A sample is a representative subset drawn from that population. Statistical inference uses sample statistics (mean x̄, variance s²) to estimate unobservable true population parameters (μ, σ²)."),
    ("What are confounding variables and how do they lead to spurious correlations?",
     "A confounding variable is an external variable that correlates with both the independent variable and the dependent variable, creating a misleading statistical association. Classic example: ice cream sales correlate with drowning deaths; the confounding variable is summer temperature. Solved via randomized controlled trials (RCTs), stratification, or multivariate regression control."),
    ("Explain Simpson's Paradox with a practical data science example.",
     "Simpson's Paradox occurs when a statistical trend appears in several distinct subgroups of data but reverses or disappears when the groups are combined. For example, Treatment A may have higher cure rates than Treatment B in both mild and severe patient cohorts, but Treatment B looks better overall because it was disproportionately administered to patients with mild illness."),
    ("What is Data Leakage in a machine learning pipeline?",
     "Data leakage occurs when information from the target variable or future test data is inadvertently introduced into the training process. Examples include: scaling the entire dataset before train/test splitting, including features calculated after the target event occurs, or leaking duplicate user records across train and test splits."),
    ("How do observational studies differ from randomized experiments (A/B testing)?",
     "In observational studies, researchers record data without intervening, which exposes findings to confounding bias and selection effects. In randomized experiments (A/B testing), subjects are randomly assigned to treatment and control groups, balancing observed and unobserved confounders and establishing true causal relationships."),
    ("What is the difference between quantitative and qualitative data types?",
     "Quantitative data represents numerical measurements and counts: discrete (integer counts like website visits) and continuous (infinitely divisible measurements like height or latency). Qualitative data represents categorical labels: nominal (unordered categories like gender or state) and ordinal (ranked categories like customer rating: Low, Medium, High)."),
    ("Explain the concept of exploratory data analysis (EDA) and its primary goals.",
     "EDA is an investigative approach to examine datasets before formal modeling. Primary goals: uncover underlying structure, identify data hygiene anomalies (missing values, typos, outliers), test fundamental statistical assumptions (normality, collinearity), and generate feature engineering hypotheses."),
    ("What are key dimensions of Data Quality in enterprise analytics?",
     "Key dimensions include: Accuracy (correct real-world representation), Completeness (absence of missing fields), Consistency (uniform values across systems), Timeliness (data freshness and latency), Validity (adherence to business schemas and regex formats), and Uniqueness (absence of duplicated records)."),
    ("What is the difference between Batch processing and Stream processing?",
     "Batch processing collects and processes high volumes of data in scheduled periodic chunks (e.g. nightly ETL running via Apache Spark). Stream processing continuously ingests, transforms, and analyzes individual events in real-time with sub-second latency (e.g. Apache Kafka, Flink)."),
    ("Explain the difference between ETL (Extract-Transform-Load) and ELT (Extract-Load-Transform).",
     "ETL transforms data on a specialized staging server before loading it into the data warehouse, common with legacy systems and sensitive PII masking. ELT loads raw data directly into high-scale modern cloud data lakes/warehouses (Snowflake, BigQuery) and performs distributed SQL transformations inside the warehouse."),
    ("What is survivor bias in data collection?",
     "Survivor bias occurs when an analysis focuses only on entities that passed a selection process while overlooking those that failed. Classic example: analyzing armor on returning WWII aircraft (the undamaged areas were where shot-down planes were hit) or studying only successful startup founders."),
    ("How do you design a robust data dictionary for a business dataset?",
     "A data dictionary documents: Column Name, Data Type, Nullability, Description/Business Meaning, Unit of Measure, Acceptable Value Range/Enumeration, Primary/Foreign Key relationships, and Upstream Data Source/Owner."),
    ("What is the difference between internal validity and external validity?",
     "Internal validity assesses whether the experimental design eliminates alternative explanations and confounders within the test sample. External validity assesses whether experimental findings generalize to broader populations, external environments, and future timeframes."),
    ("What is cross-sectional data vs time-series data vs panel data?",
     "Cross-sectional data captures multiple subjects at a single point in time (e.g. customer survey in Dec). Time-series data captures a single entity tracked over sequential intervals (e.g. daily Apple stock price). Panel (longitudinal) data captures multiple entities tracked repeatedly across multiple time periods."),
    ("What is the role of reproducible research in data science?",
     "Reproducibility ensures independent practitioners can execute the exact code and pipeline on the raw data to achieve identical analytical results. Achieved via virtual environments (Docker, venv), seed fixing (np.random.seed), deterministic ETL scripts, and version-controlled data/models (DVC, Git)."),
    ("Explain the GIGO (Garbage In, Garbage Out) principle in AI/ML.",
     "GIGO dictates that no matter how complex, deep, or state-of-the-art an algorithm is, feeding it noisy, biased, uncleaned, or mislabeled training data inevitably produces invalid, unreliable, and biased predictions in production."),
    ("What is selection bias and how can it skew data analysis?",
     "Selection bias occurs when the sample data is systematically non-representative of the target population due to flawed sampling procedures (e.g. voluntary online polls over-representing extreme opinions). It skews effect sizes and undermines model generalization."),
    ("How does correlation differ from causation?",
     "Correlation measures the statistical strength and direction of linear association between two variables. Causation implies that changing variable X directly produces a change in variable Y. Correlation can exist without causation due to coincidental trends, reverse causation, or confounding third variables."),
    ("What is an outlier and what are common strategies to handle it?",
     "An outlier is an observation that deviates substantially from the overall pattern of data. Strategies: (1) verify if it's a data entry error, (2) winsorize/cap values at 1st and 99th percentiles, (3) log-transform skewed features, (4) use robust estimators (median, Huber loss), or (5) isolate via algorithms like Isolation Forest."),
    ("What is the purpose of hypothesis testing in business analytics?",
     "Hypothesis testing provides a mathematical framework to determine whether an observed business metric change (e.g. +5% conversion on a redesigned checkout) is statistically significant or merely an artifact of random sampling noise."),
    ("Explain the concept of statistical power.",
     "Statistical power (1 - β) is the probability that a statistical test will correctly reject a false null hypothesis (i.e. detecting a true effect when one exists). High power depends on larger sample sizes, larger true effect sizes, and lower background variance."),
    ("What is a KPI (Key Performance Indicator) and what makes a good KPI?",
     "A KPI is a quantifiable metric reflecting the core business objectives of an enterprise. A strong KPI is: Aligned with strategic goals, Actionable, Measurable without ambiguity, Interpretable by stakeholders, and resistant to gaming (Goodhart's Law)."),
    ("Explain Goodhart's Law in metrics and machine learning.",
     "'When a measure becomes a target, it ceases to be a good measure.' When employees or models are incentivized strictly to optimize a proxy metric, they find degenerate shortcuts that hit the metric while violating underlying business intentions."),
    ("What is data drift vs concept drift?",
     "Data drift (covariate shift) occurs when the input feature distribution P(X) changes over time while the relationship to the target P(Y|X) remains constant. Concept drift occurs when the true relationship between features and target P(Y|X) changes (e.g. consumer spending patterns post-pandemic)."),
    ("What is an executive summary and how do you present technical findings to non-technical leaders?",
     "An executive summary highlights the core business context, the key finding/quantified financial impact, and actionable recommendations. Avoid technical jargon, emphasize ROI/risk reduction, and support conclusions with intuitive visualizations."),
    ("What is privacy-preserving data analysis and what does PII mean?",
     "PII (Personally Identifiable Information) includes data that identifies an individual (SSN, email, phone, IP). Privacy-preserving techniques include: anonymization, pseudonymization, k-anonymity, differential privacy, and hashing."),
    ("How do you evaluate whether a business problem should be solved with ML vs simple heuristics?",
     "Use rule-based heuristics if the logic is deterministic, rules are easily maintained, data is sparse, or strict auditability is required. Use Machine Learning when patterns are too complex for human rules, relationships are non-linear, high-dimensional data is available, and predictions scale across millions of instances.")
]

C2_02_PYTHON_DS = [
    ("Why is vectorization in NumPy/Pandas faster than pure Python for-loops?",
     "Vectorization delegates array computations to pre-compiled C/Fortran routines that operate on contiguous memory buffers, leveraging hardware-level SIMD (Single Instruction, Multiple Data) CPU vector registers and eliminating Python bytecode interpretation, dynamic type checking, and reference counting per element."),
    ("Explain the memory difference between a Python list and a NumPy array.",
     "A Python list stores references (pointers) to disparate PyObject instances on the heap, incurring 28+ bytes per integer and destroying CPU L1/L2 cache locality. A NumPy array stores raw binary data contiguously in a single contiguous memory block with uniform data types, maximizing memory efficiency and cache hits."),
    ("What are NumPy Universal Functions (ufuncs)?",
     "Ufuncs are vectorized wrappers around functions that operate element-wise on ndarrays in compiled C code, supporting broadcasting, type casting, and reduction operations (e.g. np.add.reduce())."),
    ("How does broadcasting allow operations on arrays of differing shapes?",
     "Broadcasting stretches smaller dimensions to match larger dimensions without copying data if, starting from trailing dimensions: (1) dimensions are equal, or (2) one of the dimensions is 1."),
    ("What is the difference between an in-place operation and returning a new array in Pandas/NumPy?",
     "In-place operations ('inplace=True' or 'arr += 1') modify the existing memory buffer directly, saving memory allocation. Returning a new array leaves the original intact and allocates a separate block of memory, which is safer for functional immutability."),
    ("Explain method chaining in Pandas and why it is used.",
     "Method chaining combines multiple data transformations in a single fluent expression (e.g. 'df.query().assign().groupby().mean()'), improving readability, avoiding intermediate variable pollution, and simplifying debugging."),
    ("What is the difference between 'apply()' and vectorized Pandas operations?",
     "Vectorized Pandas operations (built on C/NumPy) process arrays in compiled code. 'apply()' iterates over rows/columns in Python bytecode, executing a Python function call per row/column and running 10x–100x slower."),
    ("How do categorical data types in Pandas optimize memory?",
     "Categorical types replace repetitive string objects with integer codes referencing a small dictionary of unique categories. For low-cardinality string columns (e.g. State, Department), this can reduce memory usage by 80–90%."),
    ("What is the difference between shallow copy and deep copy in Pandas?",
     "'df.copy(deep=False)' copies DataFrame indices and structure but shares underlying data buffers. 'df.copy(deep=True)' creates an independent copy of both structure and data."),
    ("How does Pandas handle datetime operations and time series resampling?",
     "Pandas converts date strings to 64-bit nanosecond integers ('datetime64[ns]'). The 'dt' accessor provides vectorized date arithmetic, and '.resample()' enables frequency conversion (e.g. daily to monthly aggregation)."),
    ("Explain the difference between 'merge()', 'join()', and 'concat()' in Pandas.",
     "'merge()' performs relational SQL-like joins on arbitrary columns. 'join()' joins DataFrames primarily on their indices. 'concat()' stacks DataFrames along an axis (0 for rows, 1 for columns)."),
    ("How does Pandas resolve missing values ('None', 'np.nan', 'pd.NA')?",
     "'np.nan' is a float representing IEEE 754 NaN. In older Pandas, integer columns with missing values were forced to float64. Modern Pandas introduces 'pd.NA' and nullable data types (Int64, boolean, string) to preserve true types."),
    ("What is multi-indexing (hierarchical indexing) in Pandas?",
     "Multi-indexing allows DataFrames and Series to maintain multiple index levels along rows or columns, enabling representation of higher-dimensional data in 2D tabular form."),
    ("What is the purpose of 'df.itertuples()' over 'df.iterrows()'?",
     "'df.itertuples()' yields namedtuples directly in C, running significantly faster than 'df.iterrows()', which creates a Series object per row and does not preserve data types."),
    ("Explain memory-efficient techniques for reading massive CSV files in Pandas.",
     "Techniques: specify 'usecols' to load only required columns, explicitly declare 'dtype' (e.g. downcasting float64 to float32), use 'pd.read_csv(chunksize=...)' to stream rows in batches, or convert files to Parquet."),
    ("Why is Parquet preferred over CSV for data science storage?",
     "Parquet is a columnar, compressed binary format supporting schema enforcement, dictionary encoding, and column projection/predicate pushdown, making reads 5x–10x faster and reducing storage size by up to 80%."),
    ("What is the difference between filtering with boolean masking vs 'df.query()'?",
     "Boolean masking evaluates Python expressions in memory. 'df.query()' uses NumExpr under the hood to compile string expressions into multithreaded C code without allocating intermediate boolean array buffers."),
    ("How do you detect and fix memory leaks in long-running Python data pipelines?",
     "Use 'tracemalloc' to track memory allocations across code lines, 'gc.collect()' to force garbage collection of cyclic references, avoid appending to global lists, and delete unneeded large DataFrames using 'del df'."),
    ("What is the difference between 'map()', 'applymap()' (now 'map()'), and 'transform()' in Pandas?",
     "'map()' applies element-wise mapping on a Series. 'map()' on a DataFrame operates on every element. 'transform()' inside groupby returns an aligned Series of the same length as the original DataFrame."),
    ("How does multiprocessing in Python differ from multithreading for data tasks?",
     "Due to the GIL, multithreading runs on a single core and is effective only for I/O-bound tasks (API calls, disk reads). Multiprocessing spawns separate OS processes with independent GILs, enabling true multicore parallel execution for CPU-heavy data transformations."),
    ("What is Joblib and how is it used in data science?",
     "Joblib provides lightweight pipelining, disk-based caching of function results ('joblib.Memory'), and transparent parallel loops ('Parallel(n_jobs=-1)') for embarrassing parallel tasks like cross-validation."),
    ("Explain the difference between 'dropna()' and 'fillna()'.",
     "'dropna()' removes rows or columns containing missing values. 'fillna()' imputes missing values using constants, summary statistics (mean, median), or propagation methods ('ffill', 'bfill')."),
    ("How do you handle duplicate rows in Pandas?",
     "Use 'df.duplicated(subset=..., keep='first')' to locate duplicates, and 'df.drop_duplicates(subset=..., keep='first')' to eliminate duplicate rows."),
    ("What is method chaining with '.pipe()' in Pandas?",
     "'.pipe(func, *args, **kwargs)' applies custom functions to the entire DataFrame in a chain, enabling clean functional data cleaning pipelines without nested function calls."),
    ("What are the advantages of PyArrow backend in Pandas 2.0+?",
     "Pandas 2.0+ integrates Apache Arrow for in-memory column buffers, offering faster string operations, standardized null handling, shared zero-copy memory between languages, and reduced RAM usage."),
    ("Explain how string methods work in Pandas via the '.str' accessor.",
     "The '.str' accessor exposes vectorized string operations (e.g. .str.lower(), .str.contains(), .str.extract()) that execute across an entire Series while handling missing values safely."),
    ("What is the difference between 'qcut()' and 'cut()' in Pandas?",
     "'cut()' divides data into equal-width bins based on value range. 'qcut()' divides data into equal-frequency quantiles (e.g. quartiles, deciles) based on sample distribution."),
    ("How do you profile code performance in Jupyter notebooks?",
     "Use magic commands: '%time' for single execution time, '%timeit' for averaged benchmark runs, '%prun' for cProfile function call profiler, and '%%memit' for peak memory usage."),
    ("What is the difference between Series and 1D NumPy arrays?",
     "A Series is a labeled 1D NumPy array wrapped with an explicit index and optional name, enabling automatic data alignment during mathematical operations."),
    ("What is defensive programming in data engineering?",
     "Defensive programming anticipates corrupted inputs by enforcing strict schema validation (using Pydantic, Great Expectations), assertion checks on row counts, handling missing files gracefully, and logging execution metrics.")
]

print("Course 2 Q&A banks loaded successfully.")
