"""
Course 1 Q&A Bank: 5 Subtopics x 30 High-Yield Interview Questions
"""

C1_01_VARS = [
    ("Explain the difference between mutable and immutable objects in Python.",
     "Mutable objects (e.g. lists, dicts, sets) can be altered in-place after creation without changing their memory address (id()). Immutable objects (e.g. ints, floats, strings, tuples, frozensets) cannot be changed; any operation that modifies them instantiates a new object in memory."),
    ("How does CPython handle memory management and garbage collection?",
     "CPython primarily relies on reference counting: every object tracks how many references point to it. When the count drops to zero, its memory is immediately deallocated. To detect self-referential reference cycles (e.g. list A contains list B and vice versa), Python supplements reference counting with a generational cyclic garbage collector."),
    ("Explain the difference between the '==' operator and the 'is' keyword.",
     "'==' checks for value equality by invoking the object's __eq__() method (e.g. [1, 2] == [1, 2] is True). 'is' checks for object identity (memory address equality: id(a) == id(b)). Use 'is' strictly for singletons like 'None', 'True', and 'False'."),
    ("What is dynamic typing and duck typing in Python?",
     "Dynamic typing means variable types are checked at runtime rather than compile-time; a variable name is just a pointer that can bind to any object. Duck typing is the principle: 'If it walks like a duck and quacks like a duck, it's a duck'—code checks whether an object provides the required methods or attributes rather than checking its explicit class inheritance."),
    ("What are Python's interned strings and small integer caching?",
     "CPython pre-allocates and caches small integers between -5 and 256 at startup, so all references to 42 share the same memory location. String interning automatically caches string literals that look like Python identifiers to allow O(1) pointer comparison instead of O(N) character-by-character comparison."),
    ("Explain how Python floating-point precision works and why 0.1 + 0.2 != 0.3.",
     "Python floats are implemented as 64-bit IEEE 754 double-precision binary numbers. Fractions with denominators that are not powers of two (like 1/10 and 1/5) cannot be represented exactly in binary and produce repeating fractions. The resulting tiny rounding discrepancy causes 0.1 + 0.2 to evaluate to 0.30000000000000004. Use the decimal.Decimal class or math.isclose() for exact financial or scientific calculations."),
    ("What is the Walrus operator (:=) and when should it be used?",
     "The Walrus operator (assignment expression) allows assigning a value to a variable within an expression itself. For example: while (chunk := file.read(8192)): process(chunk). It eliminates duplicate function calls and verbose variable declarations before loops or if-conditions."),
    ("Explain the difference between deepcopy and shallow copy.",
     "A shallow copy (copy.copy) constructs a new collection object and inserts references to the original child objects. A deep copy (copy.deepcopy) recursively creates duplicate copies of every object found inside the original compound object, completely decoupling the clone from the original."),
    ("What are the advantages of using namedtuple or dataclass over standard tuples/dictionaries?",
     "Namedtuples provide lightweight, immutable tuple structures with human-readable dot notation access without dictionary memory overhead. Dataclasses (@dataclass) auto-generate boilerplate dunder methods (__init__, __repr__, __eq__) for mutable structured classes with native type hints, default values, and optional immutability (frozen=True)."),
    ("Why is type(x) == int generally discouraged compared to isinstance(x, int)?",
     "isinstance(x, int) respects object-oriented inheritance: it returns True for instances of subclasses derived from int (such as bool). type(x) == int checks exact identity and fails if the variable is an instance of a subclass, breaking polymorphism."),
    ("How does string concatenation using '+' in a loop compare to ''.join()?",
     "Strings are immutable. Using '+' in a loop re-allocates a new string buffer and copies all characters on every iteration, scaling as O(N^2) time. ''.join(list_of_strings) pre-calculates the total string length, allocates a single memory buffer, and copies characters in O(N) linear time."),
    ("What happens under the hood when you unpack variables like 'a, *b, c = [1, 2, 3, 4, 5]'?",
     "Extended iterable unpacking assigns the first element to 'a' (1), the last element to 'c' (5), and collects all intermediate elements into a standard Python list assigned to 'b' ([2, 3, 4])."),
    ("What is the difference between bytes and bytearray?",
     "bytes is an immutable sequence of integers in the range 0 <= x < 256. bytearray is a mutable counterpart that allows in-place modifications, appending, and slicing, making it much more efficient for binary I/O, socket streaming, and audio/image buffers."),
    ("What are Python's bitwise operators and when are they used in AI/ML?",
     "Bitwise operators include & (AND), | (OR), ^ (XOR), ~ (NOT), << (left shift), and >> (right shift). In AI/ML and Pandas/NumPy, & and | are overloaded to perform element-wise boolean masking on arrays and DataFrames where Python's standard 'and'/'or' keywords would fail."),
    ("How does Python represent arbitrarily large integers without integer overflow?",
     "Unlike C/C++ which use fixed 32-bit or 64-bit words, Python 3 integers are arbitrary-precision objects ('bignums'). CPython allocates a variable array of 30-bit digits on the heap, dynamically expanding memory as numbers grow, preventing integer overflow at the cost of slight speed."),
    ("Explain the concept of variable scoping and the LEGB rule.",
     "Python resolves variable names following the LEGB hierarchy: Local (inside the current function), Enclosing (in enclosing functions for nested closures), Global (module level), and Built-in (pre-defined Python names like len, range). Use 'global' to rebind module variables and 'nonlocal' to rebind enclosing closure variables."),
    ("What is an Iterable vs an Iterator?",
     "An Iterable is any object implementing __iter__() that returns an iterator (e.g. lists, dicts, tuples, strings). An Iterator is an object with state implementing __next__() which returns the next item in sequence and raises StopIteration when exhausted."),
    ("How does the 'hash()' function work and what makes an object hashable?",
     "An object is hashable if it has a hash value that never changes during its lifetime (implements __hash__()) and can be compared to other objects (implements __eq__()). All immutable built-in types (int, float, str, tuple with hashable items) are hashable; mutable types (list, dict, set) are unhashable."),
    ("What is None in Python and how is it represented in memory?",
     "None is a singleton object of type NoneType used to signify the absence of a value or default return value of functions. Because only one instance exists across the Python process, you should always check identity using 'x is None' rather than 'x == None'."),
    ("Why should default function arguments never be mutable objects like 'def func(x=[])'?",
     "Default parameter expressions are evaluated once when the function definition is executed, not each time the function is called. If the default is a mutable list or dictionary, mutations persist across all future function invocations across the program."),
    ("How do you properly implement an optional mutable default argument in Python?",
     "Set the default parameter to None: 'def func(x=None): if x is None: x = []'. This ensures a new, fresh list is instantiated on every call where no argument is passed."),
    ("What is the difference between 'del variable' and deleting an object?",
     "'del x' deletes the name binding 'x' from the current namespace and decrements the reference count of the object it pointed to. It does not directly delete the object itself; the garbage collector frees the object only when its reference count reaches zero."),
    ("Explain Python's slice syntax [start:stop:step] and negative indexing.",
     "Slice extraction extracts elements from 'start' up to but not including 'stop', incrementing index by 'step'. Negative indices count backward from the end of the sequence (-1 is the last item). 'arr[::-1]' creates a reversed copy of the sequence."),
    ("What is the difference between str() and repr()?",
     "str() returns an informal, readable string representation intended for human end users. repr() returns an unambiguous, formal string representation typically valid Python code that could recreate the object, primarily used for debugging and logging."),
    ("What is a closure in Python and why is it useful?",
     "A closure is a nested function that retains access to variables from its enclosing lexical scope even after the outer function has finished executing. Closures enable data hiding, factory functions, and function decorators."),
    ("How do format strings (f-strings) differ from str.format() and % formatting?",
     "f-strings (introduced in Python 3.6) are evaluated at runtime directly as expressions rather than parsed through constant string lookups. They are faster, more readable, support arbitrary Python expressions inside {}, and format inline specifiers like f'{val:.2f}'."),
    ("What is the purpose of the 'pass' statement in Python?",
     "'pass' is a null operation (no-op). It serves as a syntactic placeholder in blocks where Python grammar requires a statement (such as empty functions, classes, or exception blocks) but no action is needed."),
    ("What are dunder (double underscore) methods in Python?",
     "Dunder methods (magic methods like __init__, __len__, __getitem__, __call__) allow custom classes to hook into Python's core protocols and operators, enabling object-oriented operator overloading, context managers, and iteration."),
    ("Explain the difference between 'sys.getsizeof()' and actual memory consumption.",
     "sys.getsizeof() returns the memory footprint allocated directly by the container object itself in bytes, excluding the memory of objects referenced inside the container. To calculate true recursive memory, one must recursively traverse all referenced child objects."),
    ("What is the purpose of '__slots__' in a Python class?",
     "By default, Python instances store instance attributes in a dynamic dictionary (__dict__). Defining __slots__ = ('x', 'y') replaces __dict__ with a fixed-size compact array, drastically reducing memory usage when creating millions of small objects and preventing dynamic attribute creation.")
]

C1_02_CONTROL = [
    ("How does short-circuit evaluation work with 'and' and 'or' operators?",
     "Python evaluates logical expressions from left to right and stops as soon as the outcome is determined. In 'A and B', if A is falsy, Python returns A immediately without evaluating B. In 'A or B', if A is truthy, Python returns A immediately without evaluating B. This enables safe guards like: 'user and user.is_authenticated'."),
    ("Explain the difference between 'break', 'continue', and 'pass'.",
     "'break' terminates the nearest enclosing loop immediately. 'continue' skips the remainder of the current loop iteration and proceeds to the next iteration. 'pass' is a null statement that does nothing and acts as a syntactic placeholder."),
    ("How does the 'else' block behave in 'for' and 'while' loops?",
     "The 'else' block attached to a loop executes only if the loop completes all iterations naturally without encountering a 'break' statement. It is commonly used for search loops to execute fallback logic when no match is found."),
    ("What are first-class functions in Python?",
     "Functions in Python are first-class objects: they can be assigned to variables, passed as arguments to other functions, returned from other functions, and stored in data structures like lists and dictionaries."),
    ("Explain the mechanics of a Python decorator.",
     "A decorator is a callable that takes a function as input, extends or modifies its behavior via an internal wrapper function, and returns the modified function. Syntactic sugar '@my_decorator' above 'def foo()' is equivalent to 'foo = my_decorator(foo)'."),
    ("Why should you use 'functools.wraps' inside custom decorators?",
     "When a wrapper function replaces the original function, metadata such as the function name (__name__), docstring (__doc__), and signature are replaced by the wrapper's metadata. '@functools.wraps(fn)' copies this metadata back to the wrapper, preserving introspection and debugging integrity."),
    ("What are *args and **kwargs in function definitions?",
     "*args collects variable-length non-keyword positional arguments into a tuple. **kwargs collects arbitrary keyword arguments into a dictionary. They allow functions to accept dynamic signatures and pass arguments cleanly down to underlying APIs."),
    ("Explain keyword-only arguments and how to enforce them.",
     "Arguments defined after an asterisk ('*') in a function signature must be passed as keyword arguments: 'def query(sql, *, timeout=30)'. This prevents callers from accidentally passing positional values to sensitive options, improving readability."),
    ("What is the difference between a generator function and a regular function?",
     "A regular function runs to completion and returns a single value via 'return', destroying its stack frame. A generator function contains 'yield'; when called, it returns a generator iterator object that pauses execution state, yielding values lazily on-demand with O(1) memory."),
    ("Explain the 'yield from' expression introduced in Python 3.3.",
     "'yield from iterable' delegates generation directly to a sub-generator or iterable, transparently yielding all values and establishing a bi-directional communication channel for .send(), .throw(), and .close() between caller and sub-generator."),
    ("What is a lambda function and what are its architectural limitations?",
     "A lambda is an anonymous, single-expression inline function: 'lambda x, y: x + y'. Limitations include: it can only contain a single expression (no multi-line statements, loops, or assignments), cannot have type annotations, and can degrade stack trace readability."),
    ("How does Python's structural pattern matching (match-case) work?",
     "Introduced in Python 3.10, 'match subject: case pattern:' allows matching on literal values, types, sequence structures, and object attributes with optional guards (if conditions). Unlike C switch statements, it unpacks and binds variables directly from complex nested structures."),
    ("What causes a RecursionError in Python and how do you check the recursion limit?",
     "A RecursionError occurs when recursive calls exceed the interpreter's maximum stack depth (typically 1000 frames in CPython) to protect against C stack overflow. Checked via 'sys.getrecursionlimit()' and adjusted via 'sys.setrecursionlimit(n)'."),
    ("Explain tail-call optimization and does Python support it?",
     "Tail-call optimization (TCO) allows a function's stack frame to be reused if the recursive call is the very last operation. Python deliberately does NOT support TCO to preserve complete stack traces for accurate debugging and profiling (as stated by Guido van Rossum)."),
    ("What is the difference between 'global' and 'nonlocal' keywords?",
     "'global var' tells Python that assignments to 'var' modify the module-level global variable. 'nonlocal var' tells Python to rebind a variable in the nearest enclosing non-global scope (essential for closures modifying state in outer functions)."),
    ("How does 'functools.lru_cache' work and what are its requirements?",
     "lru_cache wraps a function with a Least-Recently-Used memoization cache, storing results of expensive function calls. Requirements: all arguments passed to the cached function must be hashable because cache keys are generated from argument tuples."),
    ("Explain higher-order functions with examples (map, filter, reduce).",
     "A higher-order function takes one or more functions as arguments or returns a function. 'map(fn, seq)' applies fn to each element; 'filter(pred, seq)' retains elements where pred is True; 'functools.reduce(fn, seq)' accumulates elements pairwise into a single result."),
    ("Why are list comprehensions generally preferred over map() and filter() in modern Python?",
     "List comprehensions are more idiomatic, readable, support simultaneous filtering and mapping without nested lambda calls, and execute faster in CPython because they avoid function call overhead for every element."),
    ("What is function currying and partial function application?",
     "Currying translates a function callable with N arguments into a chain of N functions that each take one argument. Partial application ('functools.partial(fn, *fixed_args)') pre-fills a subset of arguments, creating a new callable with a simpler signature."),
    ("What is the difference between passing arguments by value vs by reference in Python?",
     "Python uses 'pass-by-object-reference' (or 'pass-by-assignment'). The function receives a copy of the reference to the object. If the object is mutable (like a list), mutating it in-place reflects in the caller; if you rebind the variable name ('x = 10'), the caller's binding remains unaffected."),
    ("How do generator expressions differ from list comprehensions?",
     "List comprehensions '[x*2 for x in data]' allocate the entire list in memory immediately. Generator expressions '(x*2 for x in data)' produce items lazily one at a time using O(1) memory, making them ideal for processing gigabyte-scale datasets or infinite streams."),
    ("What is a pure function and why is it desirable in data pipelines?",
     "A pure function produces the same output for identical inputs and causes zero observable side effects (no mutation of global state, no disk/network I/O). Pure functions are easy to unit test, refactor, memoize, and parallelize across CPU cores."),
    ("How does 'zip()' work and what happens with mismatched sequence lengths?",
     "'zip(a, b)' pairs corresponding elements from iterables into tuples until the shortest iterable is exhausted. To iterate until the longest sequence completes without truncating, use 'itertools.zip_longest(*iterables, fillvalue=None)'."),
    ("Explain 'enumerate(iterable, start=0)' and why it replaces manual index tracking.",
     "'enumerate' yields (index, item) pairs directly in C, eliminating the need to manually initialize, increment, and index arrays ('arr[i]'), which prevents off-by-one errors and improves execution speed."),
    ("What are function annotations / type hints and do they enforce types at runtime?",
     "Type hints (e.g. 'def add(x: int, y: int) -> int:') document expected types and enable static analysis by tools like MyPy, IDE autocompletion, and Pydantic validation. They do NOT enforce type safety at runtime by default; Python remains dynamically typed."),
    ("How do you inspect a function's parameters and annotations programmatically?",
     "Using the 'inspect' module: 'inspect.signature(fn)' returns a Signature object containing parameter names, default values, and annotations, allowing runtime validation and dependency injection frameworks to bind arguments dynamically."),
    ("What is the difference between 'any()' and 'all()' built-in functions?",
     "'any(iterable)' returns True if at least one element evaluates to truthy, short-circuiting on the first True. 'all(iterable)' returns True only if every element is truthy, short-circuiting on the first False. Both handle empty iterables according to formal logic (all([]) is True, any([]) is False)."),
    ("What is variable shadowing in Python?",
     "Variable shadowing occurs when a variable declared within an inner scope (such as a local function variable) shares the same name as a variable in an outer scope, temporarily overriding access to the outer variable within that inner scope."),
    ("Explain the 'itertools' module and name 3 high-performance iterators.",
     "'itertools' provides memory-efficient building blocks for iterators written in C. Key examples: 'count()' (infinite sequence), 'cycle()' (repeats an iterable indefinitely), 'chain()' (flattens multiple iterables sequentially), and 'combinations()'/'permutations()' (combinatorial generators)."),
    ("How does Python handle default positional argument ordering in function signatures?",
     "Positional arguments without default values must precede arguments with default values. Defining 'def func(a=1, b):' raises a SyntaxError: non-default argument follows default argument.")
]

C1_03_STRUCTURES = [
    ("Explain the internal memory layout of a Python list.",
     "A Python list is a dynamic contiguous array of pointers (references) to objects stored elsewhere on the heap, not a linked list or contiguous block of raw values. When resized, CPython over-allocates memory geometrically (0, 4, 8, 16, 24, 32...) to ensure appending achieves O(1) amortized time complexity."),
    ("What is the time complexity of common list operations: append, insert(0), pop(), pop(0), and index search?",
     "append() is O(1) amortized; pop() from end is O(1); insert(0) and pop(0) are O(N) because every existing pointer must be shifted in memory; in-operator linear search ('x in my_list') is O(N)."),
    ("Why is 'collections.deque' preferred over list for queue/FIFO operations?",
     "deque (double-ended queue) is implemented as a doubly linked list of fixed-size memory blocks. Appending and popping from either end ('appendleft()', 'popleft()') is strictly O(1) time complexity, whereas list.pop(0) requires shifting all N elements (O(N))."),
    ("How does a Python dictionary achieve O(1) average lookup time?",
     "Python dictionaries use a hash table. When inserting a key-value pair, Python computes hash(key) to determine an index in an underlying sparse array. If no collision occurs, lookup and insertion take O(1) time. In Python 3.7+, dicts use a compact array representation that preserves insertion order while reducing memory by ~25%."),
    ("How does CPython resolve hash collisions in dictionaries?",
     "CPython uses open addressing with a pseudo-random probing sequence: index = (5*index + 1 + perturb) >> 5. This probing sequence visits all slots in the table systematically without the severe clustering typical of simple linear probing."),
    ("What happens if you insert a mutable object as a dictionary key or set element?",
     "Python raises a TypeError: unhashable type. Dictionary keys and set elements must implement __hash__() and __eq__() so their hash remains constant; mutating a key in-place would alter its hash code, making it impossible to locate in the hash table bucket."),
    ("Explain the differences between sets and lists.",
     "Sets contain unique, unordered, hashable elements implemented via hash tables, providing O(1) average membership tests ('x in s'). Lists maintain insertion order, allow duplicates, store arbitrary mutable/immutable objects, but require O(N) linear time for membership checks."),
    ("What mathematical set operations are natively supported in Python?",
     "Union ('s1 | s2' or s1.union(s2)), Intersection ('s1 & s2'), Difference ('s1 - s2'), Symmetric Difference ('s1 ^ s2' elements in either but not both), and subset/superset checks ('s1 <= s2')."),
    ("What is a 'collections.defaultdict' and how does it prevent KeyError?",
     "defaultdict is a subclass of dict that overrides __missing__(key). When a requested key is missing, it calls the factory callable provided during instantiation (e.g. int, list, set) to generate and insert a default value automatically without throwing a KeyError."),
    ("What is 'collections.Counter' and how is it used in data science?",
     "Counter is a dict subclass designed for counting hashable elements. It maps items to their integer frequencies and provides convenience methods like 'most_common(k)' which uses a heap to retrieve top-k elements in O(N log k) time."),
    ("Explain how 'heapq' works in Python and what heap invariant it maintains.",
     "The 'heapq' module implements binary min-heaps over standard Python lists where heap[0] is always the smallest element (invariant: heap[k] <= heap[2*k+1] and heap[k] <= heap[2*k+2]). Pushing and popping take O(log N) time, making it ideal for priority queues and Dijkstra's algorithm."),
    ("What is the difference between sorting with 'list.sort()' and the 'sorted()' built-in?",
     "'list.sort()' sorts the list in-place and returns None, modifying the original object with zero extra memory allocation. 'sorted(iterable)' accepts any iterable and returns a new sorted list, leaving the original sequence unchanged."),
    ("What sorting algorithm does Python use and what is its time complexity?",
     "Python uses Timsort (an adaptive stable merge/insertion sort hybrid). It achieves O(N log N) worst-case and average-case time complexity, but drops to O(N) linear time on data that is already sorted or partially sorted, with O(N) space complexity."),
    ("What does it mean that Python's sorting algorithm is 'stable'?",
     "A sorting algorithm is stable if elements with identical sort keys retain their original relative order in the sorted output. This allows multi-level sorting by sorting sequentially on secondary keys and then primary keys."),
    ("Explain the 'key' argument in 'sorted()' or 'max()'.",
     "The 'key' parameter accepts a single-argument callable applied to each element before comparison (e.g. 'sorted(students, key=lambda s: s['gpa'])'). The key function is called exactly once per element (unlike old cmp functions called O(N log N) times), maximizing speed."),
    ("How does the 'bisect' module work and what is its time complexity?",
     "The 'bisect' module provides binary search algorithms for sorted sequences: 'bisect_left()' and 'bisect_right()' locate insertion points in O(log N) time, while 'insort()' inserts items maintaining sorted order in O(N) time due to underlying array shifting."),
    ("What is a tuple and why should you use it instead of a list when data is static?",
     "A tuple is an immutable sequence of fixed length. Tuples consume less memory than lists because they do not require over-allocation for growth, are hashable (can be used as dict keys or set members), and convey architectural intent that the collection is read-only."),
    ("Explain list slicing and whether it creates a copy or a view.",
     "In standard Python, list slicing ('sub = my_list[1:5]') creates a brand-new shallow copy of the specified pointer slice. Mutating the sublist does not affect the original list. In contrast, NumPy array slicing creates a view sharing the same memory buffer."),
    ("How do dictionary views ('keys()', 'values()', 'items()') behave in Python 3?",
     "Dictionary views provide dynamic, read-only windows into the dictionary's current state: if the underlying dictionary is modified, the views reflect those changes immediately. 'dict.keys()' and 'dict.items()' support set-like operations (union, intersection)."),
    ("What is an OrderedDict and is it still necessary in Python 3.7+?",
     "Since Python 3.7, standard dicts are guaranteed to maintain insertion order. However, 'collections.OrderedDict' remains useful because it provides order-sensitive equality comparisons and specialized methods like 'move_to_end(key, last=True)' and 'popitem(last=False)' (O(1) FIFO popping)."),
    ("What is a 'frozenset' and when should it be used?",
     "A frozenset is an immutable, hashable version of a set. Because it cannot be modified after creation, it can be used as a dictionary key or nested as an element within another set (enabling sets of sets)."),
    ("How do you merge two dictionaries in Python 3.9+?",
     "Using the merge union operator: 'merged = dict1 | dict2'. To update in-place, use the update operator: 'dict1 |= dict2'. Keys in dict2 overwrite keys in dict1 if collisions occur."),
    ("Explain dictionary comprehension with an example.",
     "Dict comprehension constructs a new dictionary concisely: '{k: v for k, v in iterable if condition}'. For example, inverting a dictionary: '{v: k for k, v in original.items()}' assuming all values are unique and hashable."),
    ("What is the time complexity of checking membership in a list vs a set?",
     "'x in my_list' is O(N) because Python must scan elements sequentially until a match is found. 'x in my_set' is O(1) on average because Python computes hash(x) and jumps directly to the corresponding hash bucket."),
    ("How does memory allocation differ between a list of 1,000,000 integers in Python vs a NumPy array?",
     "A Python list of 1,000,000 ints stores 1,000,000 8-byte pointers pointing to separate 28-byte PyObject integer structs scattered across memory (~36 MB total). A NumPy 64-bit integer array stores 1,000,000 raw 8-byte binary integers contiguously in a single 8 MB buffer (~4.5x smaller, cache-coherent)."),
    ("What is 'collections.ChainMap' and how does it resolve lookups?",
     "ChainMap groups multiple dictionaries into a single logical view without copying data. Lookups search each underlying mapping sequentially and return the value from the first dictionary containing the key. Ideal for managing scoped configuration (CLI args > env vars > defaults)."),
    ("How do you remove duplicates from a list while preserving element order?",
     "In Python 3.7+, use 'list(dict.fromkeys(my_list))'. It runs in O(N) time and preserves insertion order because standard dictionaries are insertion-ordered and deduplicate keys automatically."),
    ("Explain shallow copy vs deep copy in the context of nested lists: '[[0]*3]*3'.",
     "'[[0]*3]*3' creates an outer list containing three references to the EXACT SAME inner list. Modifying matrix[0][0] = 1 will mutate all three rows simultaneously. The correct idiom is '[[0]*3 for _ in range(3)]', which instantiates three distinct inner list objects."),
    ("What is the difference between 'my_list.clear()' and 'my_list = []'?",
     "'my_list.clear()' mutates the existing list object in-place, clearing all elements; any other variables referencing that same list will see the cleared list. 'my_list = []' creates a new empty list and rebinds the name, leaving other references to the original list untouched."),
    ("How does Python implement hash tables to prevent Denial of Service (HashDoS) attacks?",
     "Python uses SipHash with a randomized secret salt generated per process startup. This prevents malicious actors from crafting pre-computed collision inputs that force dictionary operations from O(1) down to O(N^2) worst-case degradation.")
]

C1_04_OOP = [
    ("What is the difference between a class and an instance in Python?",
     "A class is a blueprint or prototype defining attributes, methods, and behaviors. An instance is a concrete realization of that class in memory created by calling the class constructor. Multiple instances maintain their own unique instance namespaces while sharing class-level attributes."),
    ("Explain the difference between '__new__' and '__init__'.",
     "'__new__' is a static method responsible for creating and returning a new instance of the class in memory (object allocation). '__init__' is an instance method called immediately after '__new__' to initialize instance attributes (object initialization). Override '__new__' for singletons or subclassing immutable types like tuple."),
    ("What is the Method Resolution Order (MRO) and what algorithm determines it?",
     "MRO is the linear sequence of classes Python searches when looking up a method or attribute in multiple inheritance hierarchies. CPython calculates MRO using the C3 Linearization algorithm, which guarantees monotonicity and preserves local precedence order. View it with 'Class.mro()'."),
    ("What does 'super()' do and why should you avoid hardcoding parent class names?",
     "'super()' returns a proxy object delegating method calls to the next class in the instance's MRO sequence. Using 'super().method()' avoids hardcoded class references, guarantees proper cooperative multiple inheritance in diamond hierarchies, and prevents diamond methods from running multiple times."),
    ("Explain the difference between '@classmethod', '@staticmethod', and regular instance methods.",
     "Instance methods take 'self' as their first argument, binding to specific instances and accessing instance state. '@classmethod' takes 'cls' as its first argument, binding to the class itself and commonly used as alternative constructors. '@staticmethod' takes neither 'self' nor 'cls', functioning as a plain function namespaced within the class."),
    ("What are property decorators ('@property', '@prop.setter') and why are they used?",
     "Properties implement the descriptor protocol, allowing method calls to be accessed with attribute syntax ('obj.price'). They allow adding validation, lazy computation, or deprecation warnings to existing attributes without breaking existing public API contracts."),
    ("What is the Python Descriptor Protocol?",
     "A descriptor is an object attribute that overrides default attribute access behavior by implementing one or more of '__get__()', '__set__()', or '__delete__()'. Descriptors power properties, classmethods, staticmethods, and ORM fields (like Django/SQLAlchemy models)."),
    ("Explain Abstract Base Classes (ABCs) and how they enforce interface contracts.",
     "Defined via the 'abc' module ('from abc import ABC, abstractmethod'), ABCs define interfaces that derived subclasses MUST implement. Attempting to instantiate a subclass that has not implemented all '@abstractmethod' methods raises a TypeError at instantiation time."),
    ("What is the difference between '__getattr__' and '__getattribute__'?",
     "'__getattribute__' is invoked unconditionally for EVERY attribute access on an instance. '__getattr__' is a fallback invoked ONLY if the attribute was not found through normal lookup (__dict__, class hierarchy). Overriding '__getattribute__' carelessly causes infinite recursion unless routed through 'super().__getattribute__()'."),
    ("What are dunder methods '__str__' and '__repr__'?",
     "'__str__' returns a user-friendly, human-readable string representation (invoked by print() and str()). '__repr__' returns an unambiguous, formal representation useful for developers and debugging (invoked by repr() and interactive REPL). Good rule: '__repr__' should ideally be executable Python code."),
    ("How do you make a custom Python class support indexing ('obj[i]') and slicing?",
     "Implement the '__getitem__(self, key)' and '__setitem__(self, key, value)' dunder methods. When slicing is used, Python passes a slice object ('slice(start, stop, step)') as the key parameter."),
    ("What does '__call__' do in a Python class?",
     "Implementing '__call__(self, *args, **kwargs)' allows instances of the class to be invoked directly like functions ('obj(x)'). This is commonly used to create stateful callable objects, custom ML layer estimators, and parameterized decorators."),
    ("How do you make an instance hashable and comparable for use in sets or dict keys?",
     "Implement '__hash__(self)' to return an integer hash and '__eq__(self, other)' to compare equality. Crucially, the attributes contributing to the hash must remain immutable after initialization."),
    ("What is the purpose of 'hasattr()', 'getattr()', and 'setattr()'?",
     "These built-in reflection functions allow dynamic attribute inspection and manipulation at runtime. 'getattr(obj, 'name', default)' retrieves attributes dynamically; 'hasattr(obj, 'name')' checks existence; 'setattr(obj, 'name', val)' assigns values dynamically."),
    ("What is the difference between class attributes and instance attributes?",
     "Class attributes are defined directly inside the class body and shared across all instances. Instance attributes are bound to specific instances (typically inside '__init__') via 'self.attr'. Mutating a class attribute via an instance creates a new shadowing instance attribute rather than modifying the shared class attribute."),
    ("Explain the concept of operator overloading with an example.",
     "Operator overloading allows custom classes to define how native Python operators (+, -, *, ==, <) behave on their instances by implementing corresponding dunder methods (e.g. '__add__' for +, '__sub__' for -, '__mul__' for *, '__lt__' for <)."),
    ("What is multiple inheritance and what is the 'Diamond Problem'?",
     "Multiple inheritance allows a class to inherit from more than one parent. The Diamond Problem occurs when class D inherits from B and C, both of which inherit from A. If B and C override a method from A, ambiguity arises about which method D should execute. Python resolves this deterministically using C3 Linearization (MRO)."),
    ("How does Python implement encapsulation and private attributes?",
     "Python relies on conventions rather than strict compiler enforcement. A single leading underscore ('_attr') indicates a private/internal attribute by convention. A double leading underscore ('__attr') triggers name mangling, transforming the name to '_ClassName__attr' to prevent accidental overrides in subclasses."),
    ("What is the purpose of '__slots__' in optimizing OOP applications?",
     "By default, Python stores instance attributes in a dynamic '__dict__'. '__slots__' restricts attributes to a predefined set and stores them in a compact C-level array. This eliminates '__dict__' overhead, saving up to 40-50% RAM when creating millions of small model instances or feature nodes."),
    ("Explain the difference between composition and inheritance. Why is composition often favored?",
     "Inheritance ('is-a' relationship) tightly couples subclasses to parent implementation details. Composition ('has-a' relationship) builds complex objects by assembling independent, decoupled components. Composition provides greater flexibility, prevents fragile base class problems, and makes testing simpler via dependency injection."),
    ("What is a metaclass in Python?",
     "A metaclass is the 'class of a class'—it defines how classes themselves are constructed, instantiated, and validated. Just as an object is an instance of a class, a class is an instance of a metaclass (by default, 'type'). Metaclasses intercept class creation to enforce schemas (e.g. in ORMs like Django and Pydantic)."),
    ("How does 'type()' function as both an introspection tool and a class factory?",
     "When called with one argument, 'type(obj)' returns the class of obj. When called with three arguments, 'type(name, bases, dict)' dynamically creates and returns a brand-new class at runtime with the specified name, parent classes, and attribute dictionary."),
    ("What is duck typing and how does 'collections.abc' facilitate it?",
     "Duck typing prioritizes capability over class inheritance. 'collections.abc' provides abstract protocols (like Mapping, Sequence, Iterable). Using 'isinstance(obj, collections.abc.Mapping)' checks whether an object adheres to dictionary protocols without forcing it to inherit from dict."),
    ("What happens when an exception is raised inside an '__init__' method?",
     "The object's initialization fails, and the exception propagates upward. The partially initialized instance is not bound to the caller's target variable, and its reference count drops to zero, triggering garbage collection and calling '__del__' if '__new__' completed."),
    ("What is the purpose of '__del__' and why is it tricky to use?",
     "'__del__' is a finalizer called when an instance is about to be destroyed by the garbage collector. It is tricky because the exact timing of garbage collection is non-deterministic, exceptions raised inside '__del__' are ignored and printed to stderr, and circular references can delay cleanup."),
    ("How do Python packages and modules differ?",
     "A module is a single Python source file (e.g. 'utils.py') containing code. A package is a directory containing multiple modules and sub-packages. Prior to Python 3.3, a package required an '__init__.py' file; Python 3.3+ introduced namespace packages that do not strictly require '__init__.py'."),
    ("What is the purpose of 'if __name__ == \"__main__\":'?",
     "Every module in Python has a built-in '__name__' attribute. When a file is run directly from the command line, Python sets '__name__ = \"__main__\"'. When imported by another script, '__name__' equals the module name. This guard prevents test or execution code from running automatically upon import."),
    ("How does Python's import system resolve modules via 'sys.path'?",
     "When an 'import foo' statement executes, Python searches directories in 'sys.path' in order: (1) the current script's directory, (2) PYTHONPATH environment variable directories, (3) standard library directories, and (4) third-party site-packages. It caches imported modules in 'sys.modules'."),
    ("What is a circular import in Python and how do you resolve it?",
     "A circular import occurs when module A imports module B, which in turn imports module A before module A has finished initializing. Resolutions: (1) refactor shared dependencies into a third module C, (2) move the import statement inside the specific function that uses it, or (3) import the module itself rather than specific symbols."),
    ("Explain the difference between absolute imports and relative imports.",
     "Absolute imports specify the full path from the project's root directory ('from mypkg.subpkg import module'). Relative imports use leading dots to navigate from the current module's location ('.module' for same directory, '..module' for parent directory), making packages relocatable.")
]

C1_05_FILES = [
    ("Explain how Python's 'with' statement works and what methods a context manager must implement.",
     "The 'with' statement manages resource allocation and cleanup automatically. A context manager must implement '__enter__()' (executed upon entering the block; its return value binds to the 'as' target) and '__exit__(exc_type, exc_val, exc_tb)' (executed upon exit, guaranteeing cleanup even if exceptions occur)."),
    ("How can you suppress exceptions using a context manager?",
     "In the '__exit__' method, returning True signals to Python that the exception has been handled and suppressed, preventing it from propagating. Returning False or None allows the exception to propagate normally. The standard library provides 'contextlib.suppress(*exceptions)' for this purpose."),
    ("What is 'contextlib.contextmanager' and how does it turn a generator into a context manager?",
     "'@contextlib.contextmanager' is a decorator that converts a generator function with a single 'yield' into a context manager. Code before the 'yield' executes as '__enter__'; the yielded value binds to 'as'; code in a 'finally' block after 'yield' executes as '__exit__'."),
    ("Explain the difference between 'pathlib.Path' and 'os.path'.",
     "'os.path' treats paths as raw strings and requires clunky function chaining ('os.path.join(os.path.dirname(p), \"f.txt\")'). 'pathlib.Path' provides an object-oriented API where paths are first-class objects with operator overloading (e.g. 'Path(\"/root\") / \"sub\" / \"file.txt\"'), cross-platform normalization, and built-in file operations (.read_text(), .exists())."),
    ("What is the difference between opening a file in 'r', 'w', 'a', and 'x' modes?",
     "'r' opens for reading (raises FileNotFoundError if missing). 'w' opens for writing, truncating existing content or creating a new file. 'a' opens for appending at the end of the file. 'x' opens for exclusive creation, failing with FileExistsError if the file already exists."),
    ("Why should binary files (images, pickled models, audio) always be opened in 'rb' or 'wb' mode?",
     "In text mode ('r'/'w'), Python translates newline characters (e.g. converting CRLF '\\r\\n' to LF '\\n' on Windows) and decodes bytes into Unicode strings using system encoding. Binary mode ('rb'/'wb') disables newline translation and encoding, reading and writing raw byte streams untouched."),
    ("How does file buffering work in Python and how can you control it?",
     "Python buffers file I/O to minimize expensive kernel syscalls. You can control buffering via the 'buffering' argument in open(): 0 disables buffering (binary only), 1 enables line buffering (text only), and >1 specifies buffer size in bytes. Use 'flush()' to force writing buffer contents to disk."),
    ("Explain the difference between 'read()', 'readline()', and 'readlines()'.",
     "'read(n)' reads up to n bytes/characters (or the entire file if n is omitted, risking memory exhaustion on large files). 'readline()' reads a single line up to the newline. 'readlines()' reads all lines into a Python list in memory. To stream large files efficiently, iterate over the file object directly: 'for line in f:'."),
    ("How do 'tell()' and 'seek()' work in file handling?",
     "'f.tell()' returns the current cursor position in bytes from the start of the file. 'f.seek(offset, whence)' moves the cursor: whence=0 (default) measures from file start, whence=1 measures from current position, whence=2 measures from file end."),
    ("What is the difference between catching 'Exception' vs 'BaseException'?",
     "'Exception' is the base class for all non-system-exiting exceptions. 'BaseException' is the root class for everything, including 'SystemExit', 'KeyboardInterrupt', and 'GeneratorExit'. Catching 'BaseException' prevents the user from terminating the program via Ctrl+C, which is usually poor practice."),
    ("Explain the full syntax of a 'try-except-else-finally' block.",
     "'try' runs guarded code. 'except' handles specified exceptions. 'else' runs ONLY if no exceptions were raised in the try block (ideal for code that shouldn't be protected by the except handler). 'finally' ALWAYS executes regardless of whether exceptions were raised, caught, or unhandled, making it essential for resource cleanup."),
    ("What is exception chaining ('raise ... from ...')?",
     "Exception chaining explicitly links a newly raised exception to an original underlying cause: 'raise CustomError(\"Failed\") from orig_err'. Python populates '__cause__' and prints 'The above exception was the direct cause of the following exception', preserving the complete diagnostic traceback."),
    ("How do you create a custom exception in Python?",
     "Define a class that inherits from 'Exception' (or a domain-specific subclass): 'class ModelTrainingError(Exception): pass'. Custom exceptions allow callers to catch specific error conditions precisely without catching unrelated general exceptions."),
    ("What is the 'csv' module and why shouldn't you parse CSVs using line.split(',')?",
     "The 'csv' module handles quote escaping, embedded commas inside quotes (e.g. \"Dallas, TX\"), multiline fields, and custom delimiters via 'csv.reader' and 'csv.DictReader'. Splitting on raw commas naive splits embedded quoted commas, corrupting tabular data."),
    ("Explain 'json.load()' vs 'json.loads()' and 'json.dump()' vs 'json.dumps()'.",
     "Methods without 's' operate on file streams/descriptors: 'load(f)' reads from a file, 'dump(obj, f)' writes to a file. Methods with 's' operate on strings: 'loads(s)' parses a JSON string, 'dumps(obj)' serializes an object into a JSON string."),
    ("What causes a TypeError: Object of type X is not JSON serializable, and how do you fix it?",
     "JSON natively supports only dicts, lists, strings, numbers, booleans, and None. Non-standard types (like NumPy arrays, Pandas DataFrames, datetime, UUID) raise TypeError. Fixed by passing a custom serializer function to 'default=my_serializer' in 'json.dumps()' (e.g. converting numpy arrays via .tolist())."),
    ("What is file locking and why is it important in multi-process AI pipelines?",
     "File locking prevents race conditions and corrupted writes when multiple worker processes read/write the same file concurrently. In Unix, 'fcntl.flock(f, fcntl.LOCK_EX)' provides advisory file locking."),
    ("Explain the difference between 'shutil.copy()' and 'shutil.copy2()'.",
     "'shutil.copy()' copies the file content and permissions. 'shutil.copy2()' copies content, permissions, and preserves complete file metadata including access and modification timestamps."),
    ("What is an atomic file write and how do you implement it?",
     "An atomic write ensures that a file is either completely written or completely untouched if the process crashes mid-write. Implemented by writing data to a temporary file on the same filesystem (e.g. 'tempfile.NamedTemporaryFile') and then atomically renaming it over the destination using 'os.replace()'."),
    ("How does memory-mapped file I/O ('mmap') work in Python?",
     "The 'mmap' module maps a file directly into the process's virtual address space, allowing files to be read and modified as if they were in-memory bytearrays. The OS loads pages lazily from disk on demand, enabling high-performance processing of multi-gigabyte datasets without loading the entire file into RAM."),
    ("What is the purpose of the 'tempfile' module?",
     "'tempfile' securely creates temporary files and directories with unique names in the OS temporary directory (e.g. /tmp), preventing symlink race attacks and ensuring automatic deletion on close with 'NamedTemporaryFile(delete=True)'."),
    ("How do you recursively search for files matching a pattern using 'pathlib'?",
     "Use 'Path.rglob(pattern)': e.g., 'list(Path('.').rglob('*.parquet'))' recursively yields all Parquet files throughout all nested subdirectories efficiently."),
    ("What is the difference between 'os.remove()' and 'shutil.rmtree()'?",
     "'os.remove(path)' deletes a single file (raises IsADirectoryError on folders). 'shutil.rmtree(path)' recursively deletes an entire directory tree and all its nested files and subfolders."),
    ("What is standard I/O redirection in Python and how do you redirect stdout?",
     "Python routes print statements to 'sys.stdout'. You can redirect it programmatically by reassigning 'sys.stdout = open(\"log.txt\", \"w\")' or using the context manager 'contextlib.redirect_stdout(target_stream)'."),
    ("Explain the difference between 'IOError', 'OSError', and 'FileNotFoundError'.",
     "In Python 3.3+, 'IOError' and 'OSError' were unified under 'OSError'. 'FileNotFoundError' is a specific built-in subclass of 'OSError' raised when a requested file or directory path does not exist on the filesystem."),
    ("How do you ensure proper UTF-8 encoding when opening files across different operating systems?",
     "Always specify 'encoding=\"utf-8\"' explicitly in 'open(filename, \"r\", encoding=\"utf-8\")'. If omitted, Python defaults to the OS-dependent locale (e.g. Windows often defaults to 'cp1252'), leading to UnicodeDecodeError when encountering non-ASCII characters."),
    ("What is the difference between 'pickle' and 'json' for serialization?",
     "'pickle' is a Python-specific binary protocol capable of serializing almost any arbitrary Python object (functions, classes, lambda closures, custom ML models). 'json' is a human-readable, cross-language plain-text standard. Crucially, unpickling untrusted data is insecure and can execute arbitrary shellcode."),
    ("Why should you avoid using bare 'except:' clauses?",
     "A bare 'except:' catches ALL exceptions, including 'KeyboardInterrupt' (preventing graceful exit via Ctrl+C) and 'SystemExit'. It also masks programming bugs like 'NameError' or 'TypoError', making debugging painful. Always catch specific exceptions or 'except Exception:'."),
    ("How does 'traceback.format_exc()' help in production logging?",
     "'traceback.format_exc()' captures the complete multi-frame stack trace as a string without crashing the application, allowing background worker daemons to log complete diagnostic traces to monitoring systems like Datadog or Sentry."),
    ("What is the 'io.StringIO' and 'io.BytesIO' module used for?",
     "'io.StringIO' and 'io.BytesIO' provide in-memory stream buffers that implement the standard file interface (read, write, seek, getvalue). They are widely used in unit testing to mock file I/O and in web services to generate in-memory PDFs, images, or CSV exports without touching physical disk.")
]

print("Course 1 Q&A banks loaded successfully.")
