"""
Course 2 Part 2 Q&A Banks: NumPy, Linear Algebra, Stats, Prob, Adv Stats, Pandas, Wrangling, Viz, Regex/APIs
"""

C2_03_NUMPY = [
    ("Explain NumPy array broadcasting rules with mathematical conditions.",
     "Two dimensions are compatible for broadcasting when: (1) they are equal, or (2) one of them is 1. Starting from the trailing (rightmost) dimensions, NumPy compares dimensions. A dimension of size 1 is virtually stretched to match the other array's shape without allocating extra memory."),
    ("What are NumPy strides and how do they determine memory indexing?",
     "Strides are tuples of bytes to step in each dimension when moving to the next element. For a 2D float64 array of shape (M, N), row stride is N*8 bytes, and column stride is 8 bytes. Transposing an array simply swaps the strides without copying underlying memory buffer."),
    ("Explain the difference between C-contiguous and Fortran-contiguous array memory layouts.",
     "C-contiguous (row-major) stores row elements consecutively in memory; advancing row index requires a large jump in memory address. Fortran-contiguous (column-major) stores column elements consecutively. C-contiguous aligns with C/Python indexing; Fortran with BLAS/Fortran libraries."),
    ("What is the difference between a view and a copy in NumPy?",
     "A view shares the exact same data buffer as the original array (checked via arr.base is not None); modifying a view mutates the original. A copy allocates an entirely new independent memory buffer."),
    ("How does basic slicing differ from advanced (fancy) indexing in NumPy?",
     "Basic slicing (e.g. arr[1:5, ::2]) ALWAYS returns a view. Advanced indexing (indexing with integer arrays, lists, or boolean masks like arr[[0, 2]]) ALWAYS returns a copy."),
    ("Explain the difference between 'np.dot()', 'np.matmul()', and the '@' operator.",
     "'np.dot()' performs matrix multiplication for 2D arrays but calculates inner products for higher-dimensional tensors. 'np.matmul()' and '@' treat higher dimensions as batches of 2D matrices, which is essential for deep learning mini-batch tensor multiplications."),
    ("What are universal functions (ufuncs) in NumPy?",
     "Ufuncs are vectorized functions operating element-wise in compiled C, supporting broadcasting, type casting, and reduction methods like np.add.reduce() and np.add.accumulate()."),
    ("Explain how boolean masking works in NumPy and how to combine masks.",
     "Boolean masking evaluates element-wise conditions, returning a boolean array of identical shape. Combine multiple conditions using bitwise operators (& for AND, | for OR, ~ for NOT), wrapping each condition in parentheses: '(arr > 0) & (arr < 10)'."),
    ("What is the difference between 'np.concatenate()', 'np.stack()', 'np.vstack()', and 'np.hstack()'?",
     "'np.concatenate()' joins existing arrays along an existing axis. 'np.stack()' joins arrays along a NEW axis. 'np.vstack()' stacks along vertical row axis (axis 0). 'np.hstack()' stacks along horizontal column axis (axis 1)."),
    ("What does 'np.vectorize' do and is it truly as fast as C-level vectorization?",
     "'np.vectorize' is a convenience wrapper providing a vectorized interface over a Python function. It does NOT compile Python code into C or accelerate execution; it simply runs a Python for-loop internally."),
    ("How does NumPy handle floating-point special values: 'np.nan', 'np.inf', and '-np.inf'?",
     "They adhere to IEEE 754 standards. 'np.nan' represents Not-a-Number (np.nan == np.nan evaluates to False; use np.isnan()). Arithmetic with nan results in nan. 'np.inf' represents positive infinity from division by zero."),
    ("What is 'np.where()' and how does its three-argument form work?",
     "'np.where(condition, x, y)' is a vectorized ternary operator: where condition is True, yield x; where False, yield y. When called with only condition, it returns the indices where condition is True."),
    ("Explain the concept of memory alignment and SIMD operations in NumPy.",
     "Modern CPUs use SIMD (Single Instruction, Multiple Data) instructions (AVX2, AVX-512) to execute mathematical operations on 4 to 8 floating-point numbers simultaneously in parallel hardware registers. NumPy contiguous memory buffers align with cache lines to maximize SIMD throughput."),
    ("What is 'np.einsum()' and why is it powerful in linear algebra and machine learning?",
     "Einstein summation ('np.einsum') computes complex tensor contractions, matrix multiplications, traces, and batched dot products using index notation (e.g. 'ik,kj->ij' for matrix multiplication) without allocating large intermediate memory arrays."),
    ("How do you find unique elements and their counts in a NumPy array?",
     "Use 'np.unique(arr, return_counts=True)'. It sorts the array and returns unique values and their frequencies in O(N log N) time."),
    ("What is the difference between 'arr.reshape()' and 'arr.resize()'?",
     "'arr.reshape()' returns a new view with the requested shape if compatible with total elements (or raises ValueError). 'arr.resize()' modifies the array in-place, truncating or padding with zeros if size changes."),
    ("How does 'np.pad()' work in computer vision and signal processing?",
     "'np.pad()' pads array boundaries with constants, reflection, or edge replication, widely used in convolutional layers to maintain spatial dimensions across image borders."),
    ("What is structured array in NumPy?",
     "A structured array allows defining compound datatypes (like C structs) with named fields of differing types (e.g. ('age', 'i4'), ('salary', 'f8')) stored contiguously in memory."),
    ("Explain 'np.argsort()' and how it is used in ranking algorithms.",
     "'np.argsort()' returns the indices that would sort an array along a given axis, essential for ranking top-k predictions, nearest neighbors, and sorting parallel arrays simultaneously."),
    ("How do you compute pairwise Euclidean distance matrix using NumPy broadcasting without for-loops?",
     "Given matrix X of shape (N, D), expand dimensions: 'diff = X[:, np.newaxis, :] - X[np.newaxis, :, :]' (shape N, N, D). The distance matrix is 'np.sqrt(np.sum(diff**2, axis=-1))'."),
    ("What is 'np.clip()' and when is it used in deep learning?",
     "'np.clip(arr, a_min, a_max)' constrains values within an interval. In deep learning, gradient clipping prevents exploding gradients, and probability clipping (e.g. clip to [1e-15, 1-1e-15]) prevents log(0) in cross-entropy loss."),
    ("How does 'np.tile()' differ from 'np.repeat()'?",
     "'np.repeat()' repeats individual elements consecutively ('[1, 2]' -> '[1, 1, 2, 2]'). 'np.tile()' replicates the entire array structure ('[1, 2]' -> '[1, 2, 1, 2]')."),
    ("Explain 'np.argmax()' along an axis in classification models.",
     "'np.argmax(arr, axis=1)' returns the column index containing the maximum predicted probability for each sample row, converting probability distributions into discrete class label predictions."),
    ("What is memory leakage in NumPy arrays due to small views of huge arrays?",
     "If you create a tiny slice from a massive 10 GB array ('small = huge[:5]'), the small view holds a reference to the entire 10 GB buffer ('small.base is huge'), preventing the 10 GB array from being garbage-collected. Fixed by forcing a copy: 'small = huge[:5].copy()'."),
    ("How do you perform element-wise random sampling in NumPy?",
     "Use the modern 'np.random.default_rng()' generator: '.integers()' for discrete uniform, '.random()' for continuous [0, 1), and '.normal(mean, std, size)' for Gaussian sampling."),
    ("What is 'np.bincount()' and why is it preferred over np.unique for counting non-negative integers?",
     "'np.bincount(arr)' counts occurrences of each integer value from 0 up to max(arr) directly using an index-based bucket array, running in O(N) linear time compared to O(N log N) for np.unique."),
    ("How does 'np.memmap' handle datasets larger than physical RAM?",
     "'np.memmap' maps large binary files on disk directly into an ndarray view; the operating system page cache transparently loads slices into RAM on-demand, enabling manipulation of terabyte-scale tensors without Out-Of-Memory errors."),
    ("What is the difference between 'np.percentile()' and 'np.quantile()'?",
     "'np.percentile()' takes percentages in the range [0, 100]. 'np.quantile()' takes probabilities in the range [0, 1]. Both compute sample percentiles using linear interpolation."),
    ("How do you invert a square matrix in NumPy and when should you avoid it?",
     "Invert using 'np.linalg.inv(A)'. In production, never invert matrices to solve Ax = b; solving 'np.linalg.solve(A, b)' using LU or Cholesky decomposition is twice as fast and mathematically much more numerically stable."),
    ("What is condition number of a matrix ('np.linalg.cond')?",
     "The condition number measures how sensitive linear systems are to small errors in input data. A high condition number (ill-conditioned matrix) indicates that tiny perturbations in features produce huge fluctuations in linear regression weights.")
]

C2_04_LINALG = [
    ("What is the geometric meaning of the dot product between two vectors?",
     "The dot product u · v = ||u|| ||v|| cos(θ). Geometrically, it measures the length of the projection of vector u onto vector v scaled by the length of v. If the vectors are orthogonal (θ = 90°), the dot product is zero; if collinear, it is maximized."),
    ("Explain the difference between Euclidean Distance and Cosine Similarity.",
     "Euclidean distance measures the straight-line spatial distance between points in coordinate space, sensitive to vector magnitude. Cosine similarity measures the cosine of the angle between vectors, normalizing for magnitude: cos(θ) = (u · v) / (||u|| ||v||). In text embeddings and RAG, cosine similarity is preferred because document length should not bias semantic relevance."),
    ("What is linear independence of a set of vectors?",
     "A set of vectors {v1, ..., vn} is linearly independent if the only linear combination that sums to the zero vector is the trivial solution where all coefficients are zero (c1*v1 + ... + cn*vn = 0 implies c1 = ... = cn = 0). If one vector can be written as a linear combination of others, the set is linearly dependent."),
    ("What is the Rank of a matrix and why does it matter in machine learning?",
     "The rank of a matrix is the maximum number of linearly independent row or column vectors. In feature matrices (N x D), if rank < D, features exhibit multicollinearity (redundant dimensions), making (X^T X) non-invertible in Ordinary Least Squares."),
    ("Explain the geometric meaning of a matrix determinant.",
     "The determinant det(A) represents the factor by which the linear transformation A scales area (in 2D) or volume (in higher dimensions). If det(A) = 0, the transformation collapses dimensions onto a lower subspace, meaning the matrix is singular and cannot be inverted."),
    ("What are Eigenvalues and Eigenvectors?",
     "For a square matrix A, an eigenvector v is a non-zero vector whose direction is unchanged by the transformation A, only scaled by a scalar factor λ (the eigenvalue): A v = λ v. In PCA, eigenvectors of the covariance matrix represent principal axes of maximum variance."),
    ("Explain Principal Component Analysis (PCA) from a linear algebra perspective.",
     "PCA computes the covariance matrix of centered data X^T X / (N-1), finds its orthogonal eigenvectors and eigenvalues via eigendecomposition, and projects the data onto the eigenvectors associated with the largest eigenvalues, maximizing preserved variance while minimizing reconstruction error."),
    ("What is Singular Value Decomposition (SVD)?",
     "SVD factors any real M x N matrix A into three matrices: A = U Σ V^T, where U (M x M) and V (N x N) are orthogonal matrices whose columns are left- and right-singular vectors, and Σ (M x N) is a diagonal matrix containing non-negative singular values ordered by magnitude."),
    ("How does Truncated SVD perform dimensionality reduction and latent semantic analysis (LSA)?",
     "Truncated SVD approximates matrix A by retaining only the top-k singular values and vectors: A_k = U_k Σ_k V_k^T. According to the Eckart-Young-Mirsky theorem, A_k is the optimal rank-k approximation that minimizes the Frobenius norm error ||A - A_k||_F."),
    ("What is the Moore-Penrose Pseudoinverse and when is it used?",
     "The pseudoinverse A^+ generalizes matrix inversion to non-square or singular matrices: A^+ = (A^T A)^(-1) A^T. In linear regression, it yields the minimum-norm least-squares solution: w = A^+ y."),
    ("Explain the Gram-Schmidt process and QR Decomposition.",
     "Gram-Schmidt converts a set of linearly independent vectors into an orthonormal basis. QR decomposition factors a matrix A into an orthogonal matrix Q (Q^T Q = I) and an upper triangular matrix R (A = Q R), providing high numerical stability when solving least-squares problems."),
    ("What is a positive semi-definite (PSD) matrix and why are covariance matrices PSD?",
     "A symmetric matrix A is positive semi-definite if x^T A x >= 0 for all non-zero vectors x. Covariance matrices are always PSD because x^T (X^T X) x = ||X x||^2 >= 0, guaranteeing that variance is always non-negative and all eigenvalues are >= 0."),
    ("Explain the difference between L1 (Manhattan) norm and L2 (Euclidean) norm mathematically.",
     "The L1 norm ||x||_1 = sum(|x_i|) sums absolute values, producing diamond-shaped unit contours. The L2 norm ||x||_2 = sqrt(sum(x_i^2)) computes straight-line distance, producing spherical unit contours."),
    ("Why does L1 regularization (Lasso) induce feature sparsity while L2 (Ridge) does not?",
     "The L1 diamond constraint boundary has sharp corners located exactly on coordinate axes. When the elliptical loss contour of regression touches the L1 boundary, it is most likely to hit a corner, forcing coefficients to exactly zero. The smooth L2 sphere touches contours at non-zero points, shrinking weights without zeroing them."),
    ("What is an Orthogonal Matrix and what are its computational benefits?",
     "A square matrix Q is orthogonal if Q^T Q = Q Q^T = I, meaning its transpose equals its inverse (Q^(-1) = Q^T). Orthogonal transformations preserve vector lengths, angles, and distances (isometries), preventing numerical instability and gradient explosion."),
    ("Explain the Trace of a matrix and its invariant properties.",
     "The trace tr(A) is the sum of diagonal elements. It equals the sum of eigenvalues: tr(A) = sum(λ_i). It is invariant under cyclic permutations: tr(ABC) = tr(BCA) = tr(CAB) and invariant under basis transformations."),
    ("What is the spectral theorem for symmetric matrices?",
     "The spectral theorem states that any real symmetric matrix A can be diagonalized by an orthogonal matrix Q of its eigenvectors: A = Q Λ Q^T, where Λ is a diagonal matrix of real eigenvalues. This guarantees that real symmetric matrices always have real eigenvalues and orthogonal eigenvectors."),
    ("How does matrix projection onto a subspace work in linear regression?",
     "Given feature matrix X, the projection matrix (hat matrix) H = X (X^T X)^(-1) X^T projects the target vector y orthogonally onto the column space of X, producing predicted values ŷ = H y such that the residual vector e = y - ŷ is orthogonal to the column space."),
    ("What is the Kernel Trick in Support Vector Machines (SVM)?",
     "The kernel trick computes inner products in a high-dimensional feature space without explicitly calculating coordinates in that space: K(x, z) = <φ(x), φ(z)>. Mercer's theorem guarantees that any positive semi-definite kernel function corresponds to an inner product in some Hilbert space."),
    ("What is the condition number of a matrix and how does it affect gradient descent?",
     "The condition number κ(A) = λ_max / λ_min of the Hessian matrix measures curvature anisotropy. A high condition number creates an elongated, ravine-like loss surface where gradient descent oscillates wildly perpendicular to the valley, requiring momentum or second-order methods."),
    ("Explain Cholesky Decomposition and its role in Gaussian processes.",
     "Cholesky decomposition factors a symmetric positive-definite matrix A into A = L L^T, where L is a lower triangular matrix. It requires half the FLOPs of LU decomposition and is widely used for sampling multivariate normal distributions and Gaussian process regression."),
    ("What is a basis of a vector space?",
     "A basis is a linearly independent subset of vectors that spans the entire vector space, meaning every vector in the space can be uniquely represented as a linear combination of basis vectors. The number of vectors in a basis equals the dimension of the space."),
    ("Explain the Null Space (Kernel) of a matrix.",
     "The null space Null(A) is the set of all vectors x such that A x = 0. According to the Rank-Nullity theorem: Rank(A) + Nullity(A) = Number of Columns of A."),
    ("What is the Frobenius norm of a matrix?",
     "The Frobenius norm ||A||_F = sqrt(sum_i sum_j |a_ij|^2) is the Euclidean norm applied to all matrix elements flattened. It equals the square root of the sum of squared singular values: sqrt(sum(σ_i^2))."),
    ("What is matrix factorization and how does it power recommendation systems (Collaborative Filtering)?",
     "Matrix factorization decomposes a sparse user-item interaction matrix R (M x N) into low-rank latent feature matrices P (M x K) and Q (N x K) such that R ≈ P Q^T. The latent factors capture hidden user tastes and item attributes."),
    ("Explain cosine distance vs cosine similarity.",
     "Cosine similarity ranges from -1 to 1 (or 0 to 1 for non-negative vectors). Cosine distance is defined as: Distance = 1 - Cosine Similarity. Note: Cosine distance is not a strict mathematical metric because it does not satisfy the triangle inequality."),
    ("What is an affine transformation?",
     "An affine transformation is a linear mapping followed by a translation: f(x) = A x + b. It preserves points, straight lines, and planes (e.g. rotation, scaling, shearing, translation), represented in homogeneous coordinates as a single matrix multiplication."),
    ("How does batch matrix multiplication work in attention layers of Transformers?",
     "In multi-head attention with batch size B, heads H, sequence length S, and head dimension D, queries Q and keys K have shape (B, H, S, D). Batched matrix multiplication 'Q @ K.swapaxes(-1, -2)' computes attention score matrices of shape (B, H, S, S) in parallel."),
    ("What is the Cayley-Hamilton theorem?",
     "The Cayley-Hamilton theorem states that every square matrix satisfies its own characteristic equation: p(A) = det(A - λ I) = 0. It allows high powers of matrices to be expressed as polynomials of degree less than N."),
    ("Why is numerical precision critical when computing matrix inversions in data science?",
     "Floating-point rounding errors in floating-point operations can accumulate rapidly in ill-conditioned matrices, producing inverted matrices with garbage coefficients. Always use stable factorizations (QR, SVD, Cholesky) or regularized inverses ((X^T X + λ I)^(-1)).")
]

print("Course 2 Part 2 banks loaded successfully.")
