"""
Course 3 Q&A Bank: 5 Subtopics x 30 High-Yield Interview Questions
"""

C3_01_FE = [
    ("Explain the difference between Filter, Wrapper, and Embedded feature selection methods.",
     "Filter methods evaluate individual feature relevance using statistical scores independent of model algorithms (e.g. Pearson correlation, Chi-Square, ANOVA F-test, Mutual Information); very fast, but ignore feature interactions. Wrapper methods search feature subsets by training and evaluating an ML model repeatedly (e.g. Recursive Feature Elimination RFE, Forward/Backward Stepwise); captures interactions, but computationally expensive and risks overfitting. Embedded methods perform feature selection during model training as part of the objective function (e.g. L1 Lasso penalty, Random Forest feature importance)."),
    ("Why does L1 Regularization (Lasso) produce sparse feature weights while L2 (Ridge) does not?",
     "The mathematical constraint region for L1 is an L1-ball (a diamond with sharp vertices situated on coordinate axes), whereas L2 is an L2-ball (a smooth hypersphere). When the elliptical contours of the Ordinary Least Squares loss expand, they are geometrically most likely to intersect the L1 diamond at a corner vertex where one or more feature weights are exactly zero."),
    ("Explain Target (Mean) Encoding and how to prevent target leakage.",
     "Target encoding replaces each categorical level with the mean of the continuous or binary target variable for that category. Target leakage occurs if calculated globally across all training samples, leading to extreme overfitting. Mitigate using Out-Of-Fold (K-fold) target encoding, adding smoothing parameters (m-estimate blending category mean with global prior mean), or injecting Gaussian noise."),
    ("How does Mutual Information differ from Pearson Correlation for feature selection?",
     "Pearson correlation measures only linear relationships (r = 0 for Y = X² centered at 0). Mutual Information is an information-theoretic metric based on entropy: I(X; Y) = H(X) + H(Y) - H(X, Y). It quantifies any relationship—linear, quadratic, sinusoidal, or non-linear—and does not assume normality."),
    ("What is the Box-Cox transformation and when does Yeo-Johnson replace it?",
     "Box-Cox transforms skewed continuous variables into Gaussian shapes via power parameter λ: (x^λ - 1)/λ. It requires strictly positive values (x > 0). The Yeo-Johnson transformation extends the Box-Cox power formulation to accommodate zero and negative values."),
    ("Explain Polynomial Features and Interaction Terms. What are the risks of high-degree expansions?",
     "Interaction terms (x1 * x2) model joint multiplicative effects. Polynomial expansions (x1², x2²) capture non-linear curvature in linear models. Expanding to degree d on p features causes combinatorial dimensionality explosion (O(p^d)), leading to severe collinearity, memory bottlenecks, and extreme overfitting unless constrained by strong L1/L2 penalties."),
    ("How do you handle cyclic features like hour of day (0-23) or month of year (1-12)?",
     "Transform each cyclic feature into two continuous orthogonal trigonometric coordinates: x_sin = sin(2π * val / period) and x_cos = cos(2π * val / period). This projects time onto a continuous 2D unit circle where hour 23 and hour 0 are mathematically adjacent (distance = 1 hour)."),
    ("What is the difference between Min-Max Scaler and Standard Scaler? When does StandardScaler fail?",
     "MinMaxScaler scales data to [0, 1] using min and max values, preserving exact zero values in sparse matrices but severely compressing normal ranges if extreme outliers exist. StandardScaler scales to zero mean and unit variance. StandardScaler fails when features exhibit extreme outliers or multi-modal heavy tails, where RobustScaler (median and IQR) is preferred."),
    ("What is High Cardinality in categorical features and what are three robust strategies to handle it?",
     "High cardinality occurs when a categorical feature has hundreds or thousands of unique levels (e.g. user IDs, postal codes). Strategies: (1) Target Encoding with regularization, (2) Frequency/Count Encoding, (3) Grouping rare categories into an 'Other' bucket based on a threshold (e.g. < 1% frequency), and (4) Entity Embeddings learned via neural networks."),
    ("Explain Principal Component Analysis (PCA) as an unsupervised feature extraction method.",
     "PCA projects high-dimensional centered data onto orthogonal linear axes (principal components) that sequentially maximize retained variance. The first principal component aligns with the eigenvector of the covariance matrix having the largest eigenvalue. PCA eliminates collinearity and compresses dimensions, but sacrifices raw feature interpretability."),
    ("What is Data Leakage during feature engineering and how do you prevent it?",
     "Data leakage occurs when information from outside the training dataset (such as validation/test sets or future data) contaminates the feature transformation pipeline (e.g. scaling before train/test splitting, computing global target statistics, using future timestamps). Prevent by fitting transformers strictly on training folds and using Scikit-learn Pipeline objects."),
    ("How do you encode ordinal categorical variables correctly?",
     "Map ordinal categories to integers that reflect their natural domain hierarchy (e.g. {'Low': 1, 'Medium': 2, 'High': 3, 'Critical': 4}). Never use nominal One-Hot Encoding for ordinal data if the intrinsic ranking provides predictive ordering signal."),
    ("What is Recursive Feature Elimination (RFE)?",
     "RFE is a greedy wrapper feature selection algorithm that trains a model, ranks features by their coefficients or feature importances, removes the weakest feature(s), and retrains the model iteratively until a target number of features remains. Cross-validated RFE (RFECV) automatically finds the optimal feature count."),
    ("Explain Variance Thresholding for feature selection.",
     "Variance thresholding is a baseline filter method that removes all features whose sample variance fails to exceed a specified threshold. For binary features, thresholding removes constant or near-constant features (e.g. p * (1 - p) < 0.01 where >99% of values are 0)."),
    ("What is Weight of Evidence (WoE) and Information Value (IV) in credit risk modeling?",
     "In binary classification, WoE = ln(% Non-Events / % Events) within a binned feature bucket. Information Value IV = sum((% Non-Events - % Events) * WoE). IV evaluates overall predictive strength: IV < 0.02 is unpredictive, 0.1-0.3 is medium, and >0.5 warrants caution for suspicious leakage."),
    ("How do you extract features from raw text data without deep learning?",
     "Classical techniques: (1) Bag-of-Words (CountVectorizer) counting token frequencies, (2) TF-IDF (Term Frequency-Inverse Document Frequency) penalizing common corpus words, and (3) N-grams (bi-grams, tri-grams) to capture local word order and phrase idioms."),
    ("What is TF-IDF mathematically?",
     "TF(t, d) = count of term t in document d. IDF(t) = ln((1 + N) / (1 + DF(t))) + 1, where N is total documents and DF(t) is documents containing term t. TF-IDF(t, d) = TF(t, d) * IDF(t). High TF-IDF indicates words that are frequent in a specific document but rare across the broader corpus."),
    ("How do you extract features from time-series timestamps?",
     "Extract calendar components: year, month, day of week, day of month, hour, is_weekend, is_holiday, quarter. Compute lag features (y_{t-1}, y_{t-7}), rolling window statistics (7-day rolling mean, rolling standard deviation), and exponential moving averages."),
    ("What are Lag Features and Rolling Statistics in time-series feature engineering?",
     "Lag features shift historical values backward in time: lag_k = y_{t-k}, providing immediate temporal context. Rolling statistics compute aggregate metrics (mean, min, max, volatility) over sliding past windows [t-w, t-1], smoothing short-term noise and capturing trend dynamics."),
    ("Explain the difference between Label Encoding and One-Hot Encoding.",
     "Label Encoding assigns arbitrary integers (0, 1, 2...) to categories; if applied to nominal features in linear or distance-based models, the model falsely assumes numerical ranking (2 > 1). One-Hot Encoding creates K binary indicator columns, preserving nominal independence at the cost of expanding dimensionality."),
    ("What is the Dummy Variable Trap?",
     "When K categories are encoded into K one-hot columns, the sum of all columns equals 1, creating perfect multicollinearity with the regression intercept. Avoid by dropping one category ('drop_first=True'), leaving K - 1 dummy variables."),
    ("How do tree-based models handle non-scaled features compared to distance-based algorithms?",
     "Decision trees and ensemble methods (Random Forest, XGBoost) are invariant to monotonic feature scaling because split points depend strictly on feature ordering, not magnitude. Distance-based algorithms (KNN, SVM, K-Means) and gradient-based models (Neural Networks, Logistic Regression) are heavily distorted unless all features are standardized to identical scales."),
    ("What is Quantile Transformer and when should it be applied?",
     "QuantileTransformer maps feature empirical distributions to a uniform or normal distribution using cumulative distribution functions. It smooths out multi-modal distributions and dampens extreme outliers, but distorts linear correlations between features."),
    ("How do you extract domain-specific features from geospatial coordinates (latitude, longitude)?",
     "Compute Haversine distance to key landmarks (city center, airport, coastline), segment into spatial grid cells (Uber H3, geohashes), or calculate local density of amenities using spatial KD-Trees."),
    ("Explain feature binarization and thresholding.",
     "Feature binarization maps continuous numerical features to boolean values based on a domain threshold (e.g. converting income to is_high_income = income > 100k). It simplifies models and captures sharp cliff-edge behavioral shifts."),
    ("What is the curse of dimensionality in feature engineering?",
     "As the number of features D grows, the volume of feature space grows exponentially, causing sample data points to become extremely sparse. Distances between all points converge to equal values (Euclidean distance metric breakdown), increasing model variance and risk of overfitting."),
    ("How do you detect and remove collinear features automatically in a pipeline?",
     "Compute correlation matrix or Variance Inflation Factor (VIF). Iteratively remove features with VIF > 10, or use hierarchical clustering on correlation distance (1 - |r|) to group collinear features and select one representative feature per cluster."),
    ("What is Feature Cross in tabular modeling?",
     "A feature cross combines two or more categorical features into a single composite feature (e.g. crossing 'Device_Type=Mobile' with 'Country=IN' to form 'Mobile_IN'). It allows linear models to learn non-linear interactions without polynomial expansion."),
    ("Explain Discretization (Binning) and why it helps linear models learn non-linear relationships.",
     "Discretization converts continuous variables into discrete categorical bins (e.g. age groups). One-hot encoding the resulting bins allows linear models to assign independent weights to each interval, fitting step-function approximations to non-linear relationships."),
    ("What are automated feature engineering frameworks like Featuretools (Deep Feature Synthesis)?",
     "Frameworks like Featuretools automatically build complex feature representations by applying relational aggregations (sum, mean, max) and transformations across multiple connected relational database tables along Foreign Key relationships.")
]

C3_02_CLUSTERING = [
    ("Explain the step-by-step algorithm of K-Means clustering.",
     "1. Initialize K cluster centroids (randomly or via K-Means++). 2. Assignment Step: assign each data point to its closest centroid based on squared Euclidean distance. 3. Update Step: recompute each centroid as the arithmetic mean of all data points assigned to that cluster. 4. Repeat Steps 2 and 3 until centroid positions converge (shift < tolerance) or max iterations is reached."),
    ("What is K-Means++ initialization and why is it superior to random initialization?",
     "Standard random initialization often converges to poor local minima with high inertia. K-Means++ picks the first centroid uniformly at random, then samples subsequent centroids with probability proportional to the squared distance D(x)² from the closest already chosen centroid. This disperses initial centroids across data space, providing O(log K) competitive approximation to the optimal clustering."),
    ("Explain the difference between Inertia (WCSS) and Silhouette Score.",
     "Inertia (Within-Cluster Sum of Squares) measures cluster compactness: sum of squared distances from points to their assigned centroid; it monotonically decreases toward 0 as K approaches N. Silhouette Score s = (b - a) / max(a, b) balances compactness a (mean intra-cluster distance) with separation b (mean distance to nearest neighboring cluster), bounded in [-1, 1]."),
    ("How does the Elbow Method determine the optimal number of clusters K?",
     "Plot Inertia (WCSS) on the y-axis against K on the x-axis. As K increases, inertia drops rapidly at first, then flattens. The 'elbow' point represents the optimal trade-off where adding further clusters yields diminishing marginal gains in compactness."),
    ("What are the primary assumptions and limitations of K-Means clustering?",
     "Assumptions: spherical clusters of roughly equal variance and size, linearly separable boundaries. Limitations: sensitive to initial centroid placement, fails on non-convex arbitrary geometries (interlocking rings, crescent moons), heavily corrupted by outliers, and requires pre-specifying K."),
    ("Explain DBSCAN (Density-Based Spatial Clustering of Applications with Noise).",
     "DBSCAN groups points based on local density without specifying K. It requires two parameters: epsilon (ε, neighborhood radius) and min_samples. A point is a Core point if at least min_samples lie within radius ε. Core points within ε connect into dense clusters. Border points lie within ε of a Core point. Outliers/Noise points have < min_samples within ε and are left unassigned (-1)."),
    ("What are the advantages of DBSCAN over K-Means?",
     "DBSCAN does not require pre-specifying cluster count K, detects clusters of arbitrary non-convex shapes, automatically isolates and flags outliers/noise points, and is robust to initialization."),
    ("When does DBSCAN fail?",
     "DBSCAN struggles with datasets containing clusters of varying densities (a single fixed ε cannot capture both dense and sparse clusters simultaneously) and high-dimensional data where the curse of dimensionality makes distances uniform."),
    ("Explain HDBSCAN (Hierarchical Density-Based Spatial Clustering).",
     "HDBSCAN extends DBSCAN by building a cluster hierarchy across varying epsilon thresholds and extracting the most stable persistent clusters using mutual reachability distance and minimum spanning trees, eliminating the sensitive global ε parameter."),
    ("What is Hierarchical Agglomerative Clustering (HAC)?",
     "HAC is a bottom-up hierarchical method: starts with each sample in its own individual cluster, then iteratively merges the two closest clusters according to a linkage criterion until all points belong to a single root cluster, visualized as a Dendrogram."),
    ("Explain Linkage Criteria in Hierarchical Clustering: Single, Complete, Average, and Ward.",
     "Single Linkage: minimum distance between any point in cluster A and any point in B (prone to chaining artifacts). Complete Linkage: maximum distance between points in A and B (produces compact, equal-diameter clusters). Average Linkage: average distance between all pairs. Ward's Linkage: minimizes the increase in total within-cluster variance upon merging, producing well-separated spherical clusters."),
    ("What is a Dendrogram and how do you determine cluster cutoffs?",
     "A Dendrogram is a tree diagram displaying the sequence of cluster merges and their linkage distances. To extract clusters, draw a horizontal line across the dendrogram at a chosen height; the number of vertical lines intersected equals the number of extracted clusters. Cutting across the largest vertical gap without horizontal cross-branches identifies natural clustering."),
    ("Explain Gaussian Mixture Models (GMM) and Soft Clustering.",
     "GMM assumes data is generated from a mixture of K Gaussian distributions with parameters (mean μ_k, covariance Σ_k, mixing weight π_k). Unlike K-Means hard assignments, GMM assigns soft posterior probabilities P(cluster k | x) to each point, capturing elliptical clusters with varying orientations and variances."),
    ("How does the Expectation-Maximization (EM) algorithm train a GMM?",
     "E-step: computes the posterior probability (responsibility) that each Gaussian component generated each data point given current parameters. M-step: updates means, covariance matrices, and mixing weights by maximizing expected log-likelihood weighted by responsibilities. Repeats until log-likelihood converges."),
    ("What is the difference between K-Means and GMM?",
     "K-Means is a special case of GMM where all covariance matrices are constrained to be isotropic and equal (Σ_k = σ² I) as σ -> 0, producing hard assignments and spherical boundaries. GMM allows full covariance matrices, soft probabilistic assignments, and anisotropic elliptical shapes."),
    ("What is Davies-Bouldin Index for evaluating clustering?",
     "Davies-Bouldin Index measures the average similarity between each cluster and its most similar cluster, where similarity is the ratio of within-cluster dispersion to between-cluster separation: R_ij = (s_i + s_j) / d(c_i, c_j). Lower values indicate better clustering (compact, well-separated clusters)."),
    ("What is Calinski-Harabasz Index (Variance Ratio Criterion)?",
     "Calinski-Harabasz is the ratio of between-cluster dispersion to within-cluster dispersion: CH = (SS_B / (K - 1)) / (SS_W / (N - K)). Higher scores indicate distinct, well-separated, compact clusters."),
    ("How do you cluster high-dimensional data effectively?",
     "Apply dimensionality reduction first (PCA, UMAP, t-SNE) to mitigate distance metric collapse caused by the curse of dimensionality, or use cosine distance/spectral clustering."),
    ("Explain Spectral Clustering and when it is used.",
     "Spectral clustering constructs an affinity graph between data points, computes the Graph Laplacian matrix L = D - W, performs eigendecomposition to project data into the low-dimensional subspace spanned by the bottom eigenvectors, and runs K-Means in that subspace. It excels at identifying non-convex, interconnected manifolds."),
    ("What is Mean Shift clustering?",
     "Mean Shift is a centroid-based non-parametric algorithm that places kernel density windows over data and iteratively shifts centroids toward regions of maximum density gradient (modes) until convergence. Number of clusters is determined automatically by bandwidth parameter."),
    ("What is Affinity Propagation?",
     "Affinity Propagation clusters data by passing messages ('responsibility' and 'availability') between pairs of data points until an optimal set of representative exemplars emerges. It does not require specifying K but scales as O(N²), limiting it to small datasets."),
    ("How does feature scaling impact distance-based clustering algorithms?",
     "Because Euclidean distance is sum of squared coordinate differences, unscaled features with large numerical magnitudes (e.g. Income: 100,000) completely dominate features with small numerical ranges (e.g. Age: 30), rendering the smaller feature irrelevant. Scaling is mandatory."),
    ("What is the difference between Extrinsic and Intrinsic clustering evaluation metrics?",
     "Intrinsic metrics evaluate cluster quality using the geometry of data points without ground truth labels (Silhouette Score, Inertia, Davies-Bouldin). Extrinsic metrics compare discovered clusters against known ground truth class labels (Adjusted Rand Index ARI, Normalized Mutual Information NMI, V-Measure)."),
    ("Explain Adjusted Rand Index (ARI).",
     "ARI measures similarity between predicted clusters and true class assignments by counting pairwise agreements and disagreements, adjusted for chance: ARI = (Index - Expected Index) / (Max Index - Expected Index). 1 indicates identical clustering; 0 indicates random labeling."),
    ("What is Biclustering (Co-clustering)?",
     "Biclustering simultaneously clusters both rows (samples) and columns (features) of a data matrix, discovering sub-matrices of correlated behaviors (widely used in gene expression analysis and collaborative filtering recommendations)."),
    ("Explain OPTICS (Ordering Points To Identify the Clustering Structure).",
     "OPTICS addresses DBSCAN's inability to detect clusters of varying density by ordering points based on core distance and reachability distance, producing a reachability plot that reveals clusters of arbitrary densities at multiple scales."),
    ("How do you handle categorical variables in clustering (K-Modes and K-Prototypes)?",
     "Standard K-Means cannot compute mathematical means on categories. K-Modes uses simple matching dissimilarity for categories and updates cluster modes (most frequent values). K-Prototypes integrates Euclidean distance for numeric features and matching dissimilarity for categorical features."),
    ("What is the difference between hard clustering and soft (fuzzy) clustering?",
     "Hard clustering (K-Means, DBSCAN) assigns each point exclusively to exactly one cluster. Soft clustering (GMM, Fuzzy C-Means) assigns membership probabilities or degrees of belonging across all clusters, allowing points on boundaries to belong partially to multiple clusters."),
    ("How do you cluster streaming real-time data?",
     "Use streaming algorithms like Mini-Batch K-Means (updates centroids incrementally using online mini-batch gradient descent) or CluStream (maintains micro-clusters in real-time, performing macro-clustering on demand)."),
    ("What is Cluster Profiling and how do you interpret cluster results for business stakeholders?",
     "Cluster profiling calculates summary statistics (mean, median, mode) of original unscaled features per cluster, contrasts cluster averages against population baselines, and builds persona archetypes (e.g. 'High-Frequency Low-Basket Shoppers') to drive targeted business strategy.")
]

C3_03_CLASSIFICATION = [
    ("Explain Logistic Regression and derive the Sigmoid function.",
     "Logistic Regression models the probability of a binary outcome y in {0, 1} given features x: P(y=1|x) = σ(w^T x). The Sigmoid function σ(z) = 1 / (1 + e^(-z)) maps unbounded linear real values z in (-inf, +inf) strictly into probabilities in [0, 1]. Its derivative has the elegant form σ'(z) = σ(z)(1 - σ(z))."),
    ("What is Binary Cross-Entropy (Log Loss) and why is Mean Squared Error (MSE) not used for logistic regression?",
     "Binary Cross-Entropy Loss: L(w) = - [y ln(ŷ) + (1 - y) ln(1 - ŷ)]. When combined with the Sigmoid activation, cross-entropy produces a smooth convex optimization surface with non-vanishing gradients. Using MSE with Sigmoid produces a highly non-convex loss surface with numerous poor local minima and flat saddle regions where gradients vanish."),
    ("How do Decision Trees choose the best split point (Gini Impurity vs Information Gain)?",
     "At each candidate split, the tree evaluates reduction in impurity. Gini Impurity: G = 1 - sum(p_i²). Information Gain = Entropy(parent) - sum((N_child/N_parent) * Entropy(child)), where Entropy = - sum(p_i log2(p_i)). The split that maximizes impurity reduction across children is selected."),
    ("What is the difference between Bagging and Boosting?",
     "Bagging (Bootstrap Aggregating): trains independent, deep, high-variance base estimators in parallel on random bootstrap subsets of data and averages predictions, reducing variance. Boosting: trains shallow, high-bias base estimators sequentially, where each successive estimator is trained to correct the residual errors made by preceding estimators, primarily reducing bias."),
    ("Explain Random Forest and how Feature Bagging decorrelates trees.",
     "Random Forest combines bootstrap sampling (data bagging) with feature bagging: at each candidate split in every individual tree, only a random subset of features (typically sqrt(p) for classification) is considered. This prevents dominant features from dictating every tree split, decorrelating tree predictions and drastically reducing ensemble variance."),
    ("What is Out-Of-Bag (OOB) error in Random Forest?",
     "Because bootstrap sampling samples with replacement, ~36.8% of training samples (1 - 1/N)^N ≈ 1/e are excluded from each individual tree's training set. The OOB error evaluates each sample using only trees that did not include that sample during training, providing an unbiased validation estimate without separate cross-validation."),
    ("Explain AdaBoost (Adaptive Boosting) and how sample weights are updated.",
     "AdaBoost trains sequential decision stumps. Misclassified training instances have their sample weights increased, forcing subsequent stumps to concentrate on difficult edge cases. The final model is a weighted majority vote where tree weights depend on their individual accuracy: α_m = 0.5 * ln((1 - err_m) / err_m)."),
    ("How does Gradient Boosting differ from AdaBoost?",
     "AdaBoost minimizes exponential loss by adjusting sample instance weights. Gradient Boosting minimizes any differentiable loss function (e.g. cross-entropy, Huber loss) by fitting subsequent trees to the negative gradients (pseudo-residuals) of the loss function evaluated at the current ensemble predictions."),
    ("What makes XGBoost faster and more regularized than standard Gradient Boosting?",
     "XGBoost incorporates second-order Taylor expansion (computing both first-order gradients g_i and second-order Hessians h_i), adds explicit L1 (α) and L2 (λ) leaf weight regularization to the objective function, uses histogram-based split finding, handles missing values natively, and parallelizes tree construction across CPU cores."),
    ("Explain LightGBM's Leaf-Wise tree growth and GOSS (Gradient-based One-Side Sampling).",
     "LightGBM uses leaf-wise (best-first) tree growth, splitting the leaf with maximum loss reduction regardless of depth (unlike level-wise growth in traditional trees), achieving lower loss at the risk of overfitting on small data. GOSS retains all instances with large gradients (under-trained) and randomly samples instances with small gradients, accelerating training by up to 10x."),
    ("How does CatBoost handle categorical features natively?",
     "CatBoost computes target encodings on-the-fly using 'Ordered Target Statistics' calculated strictly on preceding rows in random permutations of the data, completely eliminating target leakage and avoiding expensive one-hot encoding."),
    ("What is the Support Vector Machine (SVM) objective and what is the Maximum Margin Hyperplane?",
     "SVM finds a hyperplane w^T x + b = 0 that separates binary classes while maximizing the geometric margin 2 / ||w|| between the hyperplane and the closest training samples (Support Vectors), minimizing 0.5 * ||w||² subject to y_i(w^T x_i + b) >= 1 - ξ_i."),
    ("What are Slack Variables (ξ_i) and the C parameter in Soft-Margin SVM?",
     "Slack variables allow margin violations and misclassifications for non-linearly separable data. The hyperparameter C controls the regularization trade-off: large C penalizes violations heavily, producing a narrow margin with lower bias but higher risk of overfitting; small C allows more violations, producing a wider margin with higher bias and better generalization."),
    ("Explain the Kernel Trick in SVM and name common kernel functions.",
     "The kernel trick computes inner products in a high-dimensional feature space without explicitly computing coordinates in that space: K(x, z) = <φ(x), φ(z)>. Common kernels: Linear, Polynomial K(x, z) = (γ x^T z + r)^d, and Radial Basis Function (RBF / Gaussian) K(x, z) = exp(-γ ||x - z||²)."),
    ("What does the γ (gamma) hyperparameter control in an RBF SVM?",
     "Gamma controls the radius of influence of individual support vectors: γ = 1 / (2σ²). High gamma means support vectors have a tight radius of influence, creating complex, winding decision boundaries that overfit. Low gamma creates broad, smooth, linear-like boundaries that underfit."),
    ("Explain K-Nearest Neighbors (KNN) classification and why it is a 'Lazy Learner'.",
     "KNN is a lazy, instance-based non-parametric classifier: it has no explicit training phase (it stores training data in memory). At prediction time, it computes distances to all training points, identifies the k-nearest neighbors, and performs majority voting. Prediction is computationally heavy (O(N * D)), and vulnerable to the curse of dimensionality."),
    ("What is Naive Bayes classification and why is it called 'Naive'?",
     "Naive Bayes applies Bayes' Theorem: P(y|x) ∝ P(y) prod P(x_i|y). It is 'naive' because it assumes that all predictor features are strictly conditionally independent given the class label: P(x1, x2|y) = P(x1|y) * P(x2|y). Despite this unrealistic assumption, it performs surprisingly well for high-dimensional text classification (spam detection)."),
    ("Explain Laplace Smoothing in Naive Bayes.",
     "If a word or category never appeared in class y in the training data, its conditional probability P(x|y) = 0, which zeroes out the entire multiplicative posterior probability. Laplace smoothing adds a pseudo-count α (typically 1): P(x|y) = (count + α) / (total_count + α * vocabulary_size), preventing zero-probability collapse."),
    ("How do you extend Binary Classifiers to Multi-Class Classification (One-vs-Rest vs One-vs-One)?",
     "One-vs-Rest (OvR): trains K separate binary models, where model k predicts class k vs all other K-1 classes combined; prediction chooses the class with highest confidence. One-vs-One (OvO): trains K*(K-1)/2 binary models for every unique pair of classes; prediction chooses the class winning the most pairwise majority votes."),
    ("What is Softmax Regression (Multinomial Logistic Regression)?",
     "Softmax generalizes logistic regression to K > 2 mutually exclusive classes. It maps linear scores z_k into a normalized probability distribution using the softmax function: P(y = k | x) = e^(z_k) / sum_{j=1}^K e^(z_j). It is trained using Categorical Cross-Entropy loss."),
    ("What are ensemble Stacking (Stacked Generalization) and Blending?",
     "Stacking trains diverse base models (e.g. Random Forest, XGBoost, SVM) on training folds, collects their out-of-fold probability predictions into a new feature matrix, and trains a meta-model (e.g. Logistic Regression) to make final predictions. Blending is similar but uses a simple holdout validation split rather than out-of-fold K-fold cross-validation."),
    ("What is Cost-Sensitive Learning in classification?",
     "Cost-sensitive learning modifies the loss function by assigning asymmetric penalty costs C(actual, predicted) to different misclassification errors (e.g. classifying a fraudulent transaction as legitimate costs $10,000, while flagging a normal transaction costs $5), forcing the model to minimize financial loss rather than 0-1 error."),
    ("How does Voting Classifier work (Hard Voting vs Soft Voting)?",
     "Hard Voting aggregates discrete class predictions from individual models and picks the majority class. Soft Voting averages predicted class probabilities across all models and selects the class with the highest average probability. Soft voting gives higher influence to models that are confident in their predictions, usually yielding superior performance."),
    ("Explain decision tree pruning (Pre-pruning vs Post-pruning / Cost-Complexity Pruning).",
     "Pre-pruning halts tree growth early during training using stopping criteria (max_depth, min_samples_split, min_impurity_decrease). Post-pruning (Cost-Complexity Pruning / Minimal Cost-Complexity Pruning) grows a full unconstrained tree, then prunes back subtrees that minimize cost R_α(T) = R(T) + α |T|, preventing overfitting without heuristic limits."),
    ("What is Feature Importance in tree models: MDI (Mean Decrease Impurity) vs Permutation Importance?",
     "MDI (Gini importance) sums the impurity reduction achieved by splits on a feature across all trees; it is fast, but severely biased toward high-cardinality numerical features. Permutation Importance shuffles a feature's values in the validation set and measures the drop in model metric (e.g. accuracy/AUC); it is computationally heavier but unbiased and model-agnostic."),
    ("How does Linear Discriminant Analysis (LDA) differ from Logistic Regression for classification?",
     "Logistic Regression is discriminative: it models P(y|x) directly without assuming feature distributions. LDA is generative: it models P(x|y) assuming features follow multivariate Gaussian distributions with a shared covariance matrix, applying Bayes' rule to derive linear decision boundaries. LDA is optimal when normality assumptions hold."),
    ("Explain Probability Calibration (Platt Scaling vs Isotonic Regression).",
     "Many models (SVMs, Naive Bayes, boosted trees) produce uncalibrated probabilities (confidence does not reflect true empirical frequency). Platt Scaling fits a logistic regression model on raw model scores. Isotonic Regression fits a non-parametric piecewise constant isotonic function. Calibration ensures that a predicted probability of 0.8 represents an 80% real-world event rate."),
    ("What is the Brier Score and how does it evaluate probability calibration?",
     "The Brier Score is the mean squared difference between predicted probabilities and true binary labels: BS = (1/N) sum (p_i - y_i)². Lower values indicate better calibrated predictions (0 is perfect; 0.25 is random coin flip). It decomposes into Reliability, Resolution, and Uncertainty."),
    ("How do decision boundaries differ between Linear Models, Decision Trees, and RBF SVMs?",
     "Linear models create flat hyperplanes. Decision trees create axis-aligned orthogonal step-like rectangular decision regions. RBF SVMs create smooth, non-linear, flexible closed curved contours capable of isolating complex islands of data."),
    ("What is the difference between Transductive and Inductive learning in classification?",
     "Inductive learning learns a generalized mapping function f(x) from training data that can predict on unseen future instances (e.g. standard supervised ML). Transductive learning predicts labels strictly for a specific, known set of unlabelled test points provided during training (e.g. graph node classification, semi-supervised transductive SVMs) without learning a general function.")
]

C3_04_IMBALANCE = [
    ("Why is Accuracy a dangerously misleading metric on highly imbalanced datasets?",
     "In a dataset with 99% negative (class 0) and 1% positive (class 1) instances, a trivial dummy model that predicts class 0 for every instance achieves 99% accuracy while having a Recall of 0% on the minority class of interest, failing to detect fraud, disease, or system failures."),
    ("Explain the SMOTE (Synthetic Minority Over-sampling Technique) algorithm.",
     "For each minority class sample x, SMOTE computes its k-nearest neighbors among other minority samples, randomly chooses one neighbor x_nn, and creates a synthetic instance along the line segment connecting them: x_syn = x + λ * (x_nn - x), where λ ~ Uniform(0, 1). This expands the minority decision region without exact duplication."),
    ("What are the primary risks and limitations of standard SMOTE?",
     "SMOTE blindly interpolates between minority samples: if a minority sample is an outlier inside the majority class distribution, SMOTE generates synthetic points directly inside majority clusters, aggravating class overlap and increasing false positive rates."),
    ("Explain Borderline-SMOTE and ADASYN.",
     "Borderline-SMOTE applies oversampling ONLY to minority instances near the decision boundary (whose k-nearest neighbors are heavily majority class), ignoring interior points. ADASYN (Adaptive Synthetic) generates synthetic points proportional to the difficulty level: minority samples with more majority neighbors receive higher synthetic point generation weights."),
    ("How does Random Under-Sampling differ from Tomek Links?",
     "Random Under-Sampling randomly discards majority class instances, which speeds up training but discards potentially valuable informative data. Tomek Links identifies pairs of minimally distanced nearest neighbors of opposite classes (x_min, x_maj); removing the majority member of the pair cleans the decision boundary and sharpens separation."),
    ("What is Edited Nearest Neighbors (ENN) and SMOTEENN?",
     "ENN removes majority samples whose class label differs from the majority of its k-nearest neighbors. SMOTEENN combines SMOTE (oversampling minority points) followed by ENN (pruning noisy and overlapping samples from both classes), producing clean, well-defined decision boundaries."),
    ("Explain Cost-Sensitive Learning and Class Weights in 'class_weight=\"balanced\"'.",
     "Cost-sensitive learning modifies the loss function by scaling the penalty for minority class misclassifications: w_j = N / (n_classes * N_j). In binary cross-entropy, misclassifying a minority instance incurs a proportionally larger gradient update, forcing the model to shift its decision boundary toward the majority class."),
    ("What is Focal Loss and how does it address extreme class imbalance?",
     "Focal Loss FL(p_t) = - α_t (1 - p_t)^γ ln(p_t). The modulating factor (1 - p_t)^γ down-weights the loss contribution of easy, well-classified examples (where p_t is large), focusing model gradients on hard, ambiguous, and rare instances (popularized in RetinaNet)."),
    ("Why is the Precision-Recall (PR) Curve preferred over the ROC Curve for severe imbalance?",
     "The False Positive Rate in ROC includes True Negatives in its denominator: FPR = FP / (TN + FP). When the majority class (TN) is vast (e.g. millions), huge increases in false positives (FP) barely change FPR, making the ROC curve look deceptively outstanding. The PR curve plots Precision (TP / (TP + FP)) vs Recall without TNs, exposing drops in precision immediately."),
    ("Explain Threshold Tuning (Threshold Moving) for imbalanced classification.",
     "By default, classifiers predict class 1 if P(y=1|x) >= 0.5. On imbalanced data, 0.5 is arbitrary. Threshold tuning sweeps decision thresholds from 0 to 1, evaluating business metrics (F1-score, F_beta, or total financial cost) on a validation set to select the optimal operating threshold (e.g. threshold = 0.15)."),
    ("What is the F-beta score and when should you choose β = 2 vs β = 0.5?",
     "F_beta = (1 + β²) * (Precision * Recall) / (β² * Precision + Recall). β controls the relative weight of Recall vs Precision. When β = 2, Recall is weighted twice as heavily as Precision (ideal for cancer screening or fraud detection where false negatives are disastrous). When β = 0.5, Precision is weighted twice as heavily (ideal for spam filtering)."),
    ("What is Balanced Random Forest (EasyEnsemble)?",
     "Balanced Random Forest draws a bootstrap sample from the minority class and randomly under-samples the majority class to match the minority size for each individual tree in the ensemble, ensuring every tree is trained on a balanced 50:50 distribution without discarding majority information globally."),
    ("Explain the dangers of applying SMOTE before Train-Test splitting (Data Leakage).",
     "If SMOTE is applied to the entire dataset before splitting, synthetic instances in the test set will be linear interpolations of training points, and training instances will be interpolations of test points. This causes catastrophic data leakage, producing wildly over-optimistic test evaluation metrics."),
    ("What is Stratified K-Fold Cross-Validation and why is it mandatory for imbalanced data?",
     "Standard K-Fold randomly splits data, which can result in some folds receiving zero minority instances. Stratified K-Fold partitions data such that each fold contains the exact same percentage of each class as the complete dataset, ensuring stable evaluation across all splits."),
    ("How does One-Class Classification (e.g. One-Class SVM) handle extreme 1:1,000,000 imbalance?",
     "Instead of learning a boundary between two classes, One-Class SVM fits a tight hypersphere or support vector envelope around the abundant majority class (normal data). Any future instance that falls outside this learned boundary is classified as an anomaly/minority instance."),
    ("What is the Geometric Mean (G-Mean) metric in imbalanced evaluation?",
     "G-Mean = sqrt(Sensitivity * Specificity). It measures the balance between classification performances on both majority and minority classes simultaneously; a low score on either class penalizes the overall G-Mean."),
    ("Explain Balanced Accuracy.",
     "Balanced Accuracy is the unweighted average of Recall obtained on each class: Balanced Accuracy = 0.5 * (TPR + TNR). For a dummy classifier predicting all negatives on a 99:1 dataset, standard accuracy is 99%, but balanced accuracy correctly reports 50% (random guess)."),
    ("How do Ensemble Methods with Downsampling (RUSBoost) work?",
     "RUSBoost integrates Random Under-Sampling (RUS) into AdaBoost: at each boosting iteration, it randomly downsamples the majority class to match minority class weights before fitting the weak learner, combining boosting performance with the speed of undersampling."),
    ("What is the difference between Over-sampling with replacement vs Synthetic Over-sampling?",
     "Over-sampling with replacement simply duplicates existing minority instances, which increases the density of specific points and causes tree models to learn overly specific rules (overfitting). Synthetic over-sampling (SMOTE) generates novel points along feature vectors, expanding the decision space."),
    ("What is Class Overlap and how does it exacerbate class imbalance?",
     "Class overlap occurs when feature distributions of minority and majority classes overlap significantly in feature space. In imbalanced scenarios, majority samples vastly outnumber minority samples in the overlapping region, causing models to predict the majority class for all points in that region."),
    ("How does cost matrix formulation optimize commercial fraud detection?",
     "Define cost matrix: Cost(FP) = customer friction ($5); Cost(FN) = transaction value lost ($2,500); Cost(TP) = investigation fee ($10); Cost(TN) = $0. Total Expected Cost is minimized by picking classification threshold θ* = Cost(FP) / (Cost(FP) + Cost(FN))."),
    ("Explain how Autoencoders are used for extreme class imbalance.",
     "Train an Autoencoder neural network exclusively on normal majority class samples to minimize reconstruction error (MSE). When an anomalous minority instance is fed to the network, the autoencoder fails to reconstruct it accurately, resulting in a high reconstruction error that triggers anomaly detection."),
    ("What is NearMiss undersampling and what are its three variants?",
     "NearMiss-1: selects majority instances with smallest average distance to 3 closest minority instances. NearMiss-2: selects majority instances with smallest average distance to 3 furthest minority instances. NearMiss-3: selects a fixed number of closest majority instances for each minority instance."),
    ("How does temperature scaling or label smoothing interact with imbalanced datasets?",
     "Label smoothing replaces hard 0/1 targets with soft targets (e.g. ε and 1 - ε), preventing overconfidence. On imbalanced data, uniform label smoothing can disproportionately penalize the minority class; class-aware label smoothing adjusts smoothing proportional to class frequencies."),
    ("Explain the role of probability calibration when using under-sampling.",
     "Under-sampling shifts the empirical class distribution (e.g. from 1% positive to 50% positive). As a result, model output probabilities are severely shifted toward 0.5. To recover true population probabilities, apply Bayes' recalibration: p_true = (p_pred * r) / (p_pred * r + (1 - p_pred)) where r is the sampling ratio."),
    ("What is Two-Phase Learning for imbalanced neural networks?",
     "Phase 1: train the neural network on an artificially balanced dataset (via oversampling/undersampling) to learn strong, generalizable feature representations. Phase 2: fine-tune the final classification layer on the true imbalanced dataset to properly calibrate decision thresholds."),
    ("How do you evaluate multi-class imbalanced classification?",
     "Use Macro-Averaged F1-score (unweighted average of F1 across all classes, treating rare classes equally) or Balanced Multi-Class Log-Loss. Avoid Micro-Averaged metrics, which are dominated by performance on the majority class."),
    ("What is Neighborhood Cleaning Rule (NCR)?",
     "NCR is an undersampling technique that combines Edited Nearest Neighbors (ENN) to clean ambiguous majority instances with a secondary rule: if a minority instance is misclassified by its 3 nearest neighbors, the majority neighbors are removed."),
    ("How does Metric Learning (Triplet Loss / Contrastive Loss) assist imbalanced classification?",
     "Metric learning trains neural networks to project samples into an embedding space where instances of the same class are pulled close together and instances of different classes are pushed apart by a margin, creating clustered representations that separate minority points from majority points."),
    ("What are the key production monitoring alerts for models operating on imbalanced data?",
     "Monitor: (1) Prediction Distribution Drift (alert if predicted positive rate shifts from historical baseline), (2) Feature Drift (KS-test / PSI on input features), (3) Operational False Positive Rate, and (4) Delayed True Positive Feedback Loops.")
]

C3_05_EVAL = [
    ("Explain the Confusion Matrix and define TP, FP, TN, and FN.",
     "A Confusion Matrix cross-tabulates actual vs predicted classes: True Positive (TP): correctly predicted positive. False Positive (FP / Type I error): negative incorrectly predicted as positive. True Negative (TN): correctly predicted negative. False Negative (FN / Type II error): positive incorrectly predicted as negative."),
    ("Define Precision, Recall, Specificity, and Fall-out mathematically.",
     "Precision = TP / (TP + FP) (purity of positive predictions). Recall (Sensitivity / TPR) = TP / (TP + FN) (proportion of actual positives identified). Specificity (TNR) = TN / (TN + FP) (proportion of actual negatives identified). Fall-out (FPR) = FP / (TN + FP) = 1 - Specificity."),
    ("What is the mathematical formulation of F1-Score and why does it use Harmonic Mean?",
     "F1 = 2 * (Precision * Recall) / (Precision + Recall). It uses the Harmonic Mean rather than the Arithmetic Mean because the harmonic mean approaches the smaller of the two numbers. If either Precision or Recall is near zero, F1 drops close to zero, preventing models with 100% recall but 1% precision from scoring well."),
    ("Differentiate between Micro-average, Macro-average, and Weighted-average in multi-class metrics.",
     "Macro-average: calculates metric independently for each class and computes unweighted mean; treats all classes equally (ideal for spotting issues in rare classes). Micro-average: pools all TPs, FPs, and FNs globally across all classes; dominated by majority classes. Weighted-average: averages class metrics weighted by the support (frequency) of each class."),
    ("Explain the Receiver Operating Characteristic (ROC) curve and Area Under the Curve (AUC).",
     "The ROC curve plots TPR (Recall) on the y-axis against FPR (1 - Specificity) on the x-axis across all decision thresholds from 1.0 to 0.0. The diagonal line represents random guessing (AUC = 0.5). AUC measures the probability that the model ranks a randomly chosen positive instance higher than a randomly chosen negative instance (AUC = 1.0 is perfect ranking)."),
    ("What are the mathematical properties of ROC-AUC and why is it threshold-independent?",
     "ROC-AUC evaluates ranking quality across ALL possible decision thresholds simultaneously. It is scale-invariant (evaluates rank order rather than absolute probability values) and classification-threshold-invariant."),
    ("When does ROC-AUC give an overly optimistic view compared to PR-AUC?",
     "On datasets with extreme class imbalance (e.g. 99.9% negative), the vast number of True Negatives suppresses the False Positive Rate (FPR = FP / (TN + FP)), keeping FPR tiny even when thousands of false positives occur. PR-AUC excludes TNs, revealing drops in precision immediately."),
    ("What is Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and Mean Absolute Error (MAE)?",
     "MSE = (1/N) sum (y_i - ŷ_i)²; penalizes large errors heavily due to squaring. RMSE = sqrt(MSE); in the same units as target variable. MAE = (1/N) sum |y_i - ŷ_i|; robust to outliers and represents the median regression error."),
    ("When should you choose Mean Absolute Percentage Error (MAPE) and when does it fail?",
     "MAPE = (100%/N) sum |(y_i - ŷ_i) / y_i| expresses error as a percentage of actual values, making it easy to communicate to business executives. It fails completely when actual values y_i = 0 (division by zero) and penalizes positive errors differently from negative errors."),
    ("Explain Mean Squared Logarithmic Error (MSLE) and why it is used in pricing models.",
     "MSLE = (1/N) sum (ln(1 + y_i) - ln(1 + ŷ_i))². It evaluates relative percentage differences rather than absolute values and penalizes under-estimates more heavily than over-estimates, making it ideal for real-estate or product price predictions."),
    ("What is R-squared (Coefficient of Determination) and can it be negative?",
     "R² = 1 - (SS_res / SS_tot) = 1 - sum(y_i - ŷ_i)² / sum(y_i - ȳ)². It measures the proportion of variance in y explained by the model compared to a naive mean baseline. Yes, R² can be negative if the model's predictions are worse than simply predicting the mean of the target variable on out-of-sample test data."),
    ("Explain Adjusted R-squared and its degrees of freedom penalty.",
     "Standard R² increases mechanically with every additional feature added to the model. Adjusted R² = 1 - [(1 - R²)(N - 1) / (N - p - 1)], penalizing the addition of extraneous features p unless they reduce residual error sufficiently to justify the lost degree of freedom."),
    ("What is K-Fold Cross-Validation and what is the optimal choice of K?",
     "K-Fold partitions data into K equal folds, training on K-1 folds and validating on the remaining fold, rotating K times. Standard choice is K = 5 or K = 10, balancing empirical bias (lower at K=10) with variance and computational expense."),
    ("Explain Leave-One-Out Cross-Validation (LOOCV) and its trade-offs.",
     "LOOCV is K-Fold where K = N (trains on N-1 samples, tests on 1, repeated N times). It provides an almost unbiased estimate of true performance, but has high computational cost (O(N) model trainings) and high variance because the N training sets are nearly identical."),
    ("What is TimeSeriesSplit and why must regular K-Fold NEVER be used on temporal data?",
     "Regular K-Fold randomly shuffles data, training on future observations to predict past observations, causing catastrophic temporal look-ahead leakage. TimeSeriesSplit uses expanding rolling windows (walk-forward validation): trains strictly on past data [1 to t] and tests on future window [t+1 to t+k], preserving temporal causality."),
    ("Explain GroupKFold and when it is required.",
     "GroupKFold ensures that all samples originating from the same group (e.g. patient ID, user ID, household ID) are assigned entirely to either the training set or the validation set, never split across both. It prevents data leakage when multiple correlated records belong to the same entity."),
    ("What is Stratified K-Fold and why is it standard for classification?",
     "Stratified K-Fold preserves the percentage of samples for each target class within every individual fold to match the complete dataset distribution, preventing folds from suffering from class starvation."),
    ("Explain the Bias-Variance Tradeoff mathematically.",
     "Expected Prediction Error = Bias(ŷ)² + Var(ŷ) + σ² (Irreducible Noise). Bias measures error from erroneous assumptions in the learning algorithm (underfitting). Variance measures sensitivity to small fluctuations in the training set (overfitting). As model complexity increases, bias decreases while variance increases."),
    ("How do Learning Curves diagnose High Bias (Underfitting) vs High Variance (Overfitting)?",
     "High Bias: training score and validation score converge quickly to a low, unacceptable plateau; adding more training data does not improve performance. High Variance: large gap between high training score and substantially lower validation score; adding more training data helps close the generalization gap."),
    ("What is a Calibration Curve (Reliability Diagram)?",
     "A calibration curve bins predicted probabilities (e.g. [0-0.1, 0.1-0.2...]) on the x-axis and plots the true fraction of positive outcomes on the y-axis. A perfectly calibrated model follows the 45-degree diagonal line y = x. S-shaped curves indicate under-confidence; inverted S-curves indicate over-confidence."),
    ("What is the Cumulative Gains Chart and Lift Chart?",
     "Cumulative Gains plots the percentage of total positive targets identified on the y-axis against the percentage of population contacted on the x-axis (sorted by predicted probability). The Lift Chart plots the ratio of model gain to random baseline gain (Lift = Gain / Random). High initial lift (e.g. 5x lift in top decile) proves model efficiency in marketing campaigns."),
    ("Explain Normalized Discounted Cumulative Gain (NDCG) in ranking and recommendation systems.",
     "DCG = sum_{i=1}^p (2^(rel_i) - 1) / log2(i + 1). NDCG = DCG / IDCG, where IDCG is the Ideal DCG achieved by perfect ranking. It rewards relevant items appearing at top ranks and heavily penalizes relevant items pushed down the ranked list, scaled between 0 and 1."),
    ("What is Mean Reciprocal Rank (MRR)?",
     "MRR = (1/|Q|) sum_{i=1}^{|Q|} (1 / rank_i), where rank_i is the position of the FIRST relevant item found for query i. It evaluates systems where only the top successful retrieval matters (e.g. search engines, QA systems)."),
    ("Explain Top-K Accuracy (Hit Rate@K).",
     "Top-K Accuracy measures the proportion of test instances where the true target label is included within the model's top K highest-confidence predicted classes (common in ImageNet top-5 evaluation and recommender candidate generation)."),
    ("What is Cohen's Kappa statistic?",
     "Kappa = (p_o - p_e) / (1 - p_e), where p_o is observed agreement and p_e is expected agreement by chance. It evaluates inter-rater agreement or classification performance adjusted for chance agreement, bounded in [-1, 1]."),
    ("Explain Matthew's Correlation Coefficient (MCC).",
     "MCC = (TP*TN - FP*FN) / sqrt((TP+FP)(TP+FN)(TN+FP)(TN+FN)). It evaluates binary classification using all four confusion matrix quadrants, producing values in [-1, 1]. It remains reliable even on heavily imbalanced datasets where F1 and accuracy fail."),
    ("What is Population Stability Index (PSI) and how does it detect production model drift?",
     "PSI = sum ((Actual% - Expected%) * ln(Actual% / Expected%)). It measures shift in feature or prediction distributions between training (expected) and production (actual). PSI < 0.1 indicates stability; 0.1 <= PSI <= 0.2 indicates moderate shift; PSI > 0.2 signals significant distribution drift requiring retraining."),
    ("Explain Cross-Entropy (Log-Loss) as an evaluation metric.",
     "Log-Loss = - (1/N) sum [y_i ln(p_i) + (1 - y_i) ln(1 - p_i)]. Unlike accuracy or F1 which evaluate hard binary decisions, Log-Loss penalizes overconfident wrong predictions exponentially (e.g. predicting p = 0.99 when true y = 0 incurs huge loss), measuring true probabilistic confidence."),
    ("What is the difference between Data Drift and Concept Drift in evaluation pipelines?",
     "Data drift (covariate shift) occurs when the input distribution P(X) changes over time while P(Y|X) remains unchanged. Concept drift occurs when the conditional relationship P(Y|X) changes (the underlying definition of the target changes), causing a model to degrade even if input distributions appear stable."),
    ("What are Golden Evaluation Sets and Shadow Deployments in enterprise production ML?",
     "A Golden Set is a curated, human-verified, static benchmark test dataset representing critical edge cases and core business logic that every candidate model must pass before release. A Shadow Deployment runs the new model in production alongside the active legacy model on live traffic without serving predictions to users, comparing latency, throughput, and predictions in real time.")
]

print("Course 3 banks loaded successfully.")
