"""
Course 4 Q&A Bank: 4 Subtopics x 30 High-Yield Interview Questions
"""

C4_01_NN_BASICS = [
    ("Explain the mathematical model of a single Perceptron and its limitations.",
     "A Perceptron computes a linear combination of inputs: z = sum(w_i * x_i) + b = w^T x + b, followed by a step threshold activation function f(z) = 1 if z >= 0 else 0. As proven by Minsky & Papert (1969), a single-layer perceptron can only learn linearly separable functions and fails on non-linear logic gates like XOR."),
    ("What is a Multi-Layer Perceptron (MLP) and how does it overcome Perceptron limitations?",
     "An MLP consists of an input layer, one or more hidden layers with non-linear activation functions, and an output layer. Non-linear activations introduce non-linear decision boundaries, enabling MLPs to solve non-linear problems like XOR and act as Universal Function Approximators."),
    ("State the Universal Approximation Theorem and its practical implications.",
     "The theorem (Cybenko, 1989; Hornik, 1991) states that a feedforward network with a single hidden layer containing a finite number of neurons and non-linear activation functions can approximate any continuous function on compact subsets of R^n to arbitrary precision. In practice, deeper networks with fewer total neurons learn hierarchical representations much more efficiently than a single excessively wide layer."),
    ("Explain the Backpropagation algorithm step-by-step.",
     "1. Forward Pass: compute activations layer-by-layer up to output predictions ŷ, then calculate loss L(y, ŷ). 2. Backward Pass: compute error gradient at output layer ∂L/∂ŷ, then apply the multivariable Chain Rule of calculus backward through each layer to compute gradients of the loss with respect to weights ∂L/∂W and biases ∂L/∂b. 3. Optimization Step: update parameters using an optimizer (e.g. W = W - η * ∂L/∂W)."),
    ("Derive the gradient update using the Chain Rule for a 2-layer network.",
     "For loss L, activation a^[2] = σ(z^[2]) where z^[2] = W^[2] a^[1] + b^[2]: ∂L/∂W^[2] = (∂L/∂a^[2]) * (∂a^[2]/∂z^[2]) * (∂z^[2]/∂W^[2]) = δ^[2] * (a^[1])^T, where δ^[2] = (∂L/∂z^[2]). The error propagates backward: δ^[1] = (W^[2])^T δ^[2] * σ'(z^[1]), and ∂L/∂W^[1] = δ^[1] * (x)^T."),
    ("What is the Vanishing Gradient problem and what causes it?",
     "During backpropagation in deep networks, gradients are multiplied across layers via the chain rule. Saturating activation functions like Sigmoid and Tanh have maximum derivatives of 0.25 and 1.0 respectively. In deep architectures, repeatedly multiplying fractions << 1 causes gradients in earlier layers to shrink exponentially toward zero, preventing early layers from updating their weights."),
    ("What is the Exploding Gradient problem and how is it mitigated?",
     "Exploding gradients occur when large weights or derivatives compound across deep networks, causing gradient norms to grow exponentially, resulting in numerical overflow (NaNs) and unstable weight updates. Mitigated via: (1) Gradient Clipping (clipping gradient norm to a maximum threshold), (2) proper weight initialization (He/Glorot), and (3) Batch Normalization."),
    ("Compare Sigmoid, Tanh, ReLU, Leaky ReLU, and GELU activation functions.",
     "Sigmoid: σ(z) = 1/(1+e^-z); outputs [0, 1], non-zero-centered, suffers from severe vanishing gradients. Tanh: zero-centered [-1, 1], but still saturates at tails. ReLU: max(0, z); computationally cheap, does not saturate for z > 0, but suffers from 'Dying ReLU'. Leaky ReLU: max(αz, z) with α ≈ 0.01; allows small gradient when z < 0. GELU: x * Φ(x); smooth, probabilistic gating standard in modern Transformers (BERT, GPT)."),
    ("What is the 'Dying ReLU' problem and how can it be prevented?",
     "Dying ReLU occurs when a large gradient pushes neuron weights such that the neuron outputs z <= 0 for all training examples. Because ReLU's derivative is 0 for negative inputs, gradient flow halts completely, rendering the neuron permanently inactive ('dead'). Prevented by using Leaky ReLU, Parametric ReLU (PReLU), ELU, or reducing the learning rate."),
    ("Explain Weight Initialization: Xavier/Glorot vs He/Kaiming initialization.",
     "Initializing weights to zeros makes all neurons compute identical gradients (symmetry problem). Xavier/Glorot draws from variance Var(W) = 2 / (fan_in + fan_out), designed to preserve activation and gradient variance for Sigmoid/Tanh. He/Kaiming draws from Var(W) = 2 / fan_in, specifically derived to account for ReLU zeroing out half of the activations."),
    ("What is the loss surface of a neural network and what are Saddle Points?",
     "The loss surface is a high-dimensional landscape mapping network weights to loss values. In high dimensions, local minima are rare; most critical points (where gradient = 0) are Saddle Points (minima along some dimensions, maxima along others). First-order gradient descent can slow down severely near saddle points, but stochastic noise and momentum help escape them."),
    ("Explain the difference between Batch Gradient Descent, Stochastic Gradient Descent (SGD), and Mini-Batch SGD.",
     "Batch GD computes gradients across the ENTIRE dataset before updating weights (exact gradient, but slow and memory-prohibitive). Pure SGD updates weights after EVERY single sample (fast, but noisy and cannot leverage GPU vectorization). Mini-Batch SGD computes gradients over small batches (e.g. 32 to 256 samples), balancing gradient stability with GPU SIMD parallelism."),
    ("What does Momentum do in gradient descent?",
     "Momentum adds a fraction γ of the previous update vector to the current gradient update: v_t = γ v_{t-1} + η ∇L(W). It accelerates gradient descent along persistent directional trajectories while dampening wild oscillations perpendicular to ravines, speeding up convergence."),
    ("Explain Nesterov Accelerated Gradient (NAG).",
     "Standard momentum computes the gradient at the current position, then takes a momentum step. Nesterov 'looks ahead' by computing the gradient at the anticipated future position: ∇L(W - γ v_{t-1}), applying a proactive course correction that prevents overshooting sharp turns."),
    ("How does the learning rate hyperparameter affect optimization?",
     "If learning rate η is too small, training converges at an agonizingly slow pace and gets trapped in flat plateaus. If η is too large, optimization oscillates wildly, overshoots minima, and can diverge toward infinite loss (NaNs). Learning rate schedules (warmup, cosine decay) adapt η dynamically."),
    ("What is Learning Rate Warmup and why is it standard in deep learning?",
     "Warmup starts training with a very small learning rate for the first few epochs/steps, gradually ramping up to the base learning rate. Early in training, network weights are randomized and gradients are huge and unstable; warmup prevents catastrophic early updates that destabilize representations."),
    ("Explain Cosine Annealing learning rate schedule.",
     "Cosine annealing decays the learning rate following a half-cosine curve: η_t = η_min + 0.5 * (η_max - η_min) * (1 + cos(t * π / T_max)). It decays gradually initially, drops rapidly through intermediate epochs, and smoothly flattens near zero, enabling fine convergence into deep minima."),
    ("What is an Epoch vs an Iteration vs a Batch Size?",
     "Batch Size: number of training samples processed in one forward/backward pass. Iteration (Step): one parameter update pass over a single mini-batch. Epoch: one complete pass through the entire training dataset (Iterations per epoch = Total Samples / Batch Size)."),
    ("Why is Shuffle=True critical during training mini-batches?",
     "If data is not shuffled between epochs, mini-batches contain identical samples in identical order, introducing cyclical bias into gradient paths and potentially clustering identical labels together, which causes optimization instability. Shuffling breaks correlations and ensures stochastic gradient variance."),
    ("Explain the Softmax function and how temperature scaling works.",
     "Softmax maps raw logits z into a probability distribution: P(y=k) = e^(z_k / T) / sum_j e^(z_j / T). Temperature T modulates output entropy: T = 1 is standard softmax; T > 1 smooths probabilities toward uniform distribution (higher exploration); T < 1 sharpens probabilities toward argmax (higher confidence)."),
    ("What is Categorical Cross-Entropy loss mathematically?",
     "L = - sum_{k=1}^K y_k ln(p_k), where y is a one-hot vector and p is the predicted probability distribution. For the true class c, the loss simplifies to -ln(p_c). Minimizing cross-entropy is mathematically equivalent to minimizing the Kullback-Leibler (KL) divergence between empirical and predicted distributions."),
    ("What is Sparse Categorical Cross-Entropy and when is it preferred over Categorical Cross-Entropy?",
     "Categorical Cross-Entropy expects one-hot encoded targets of shape (N, K), consuming O(N*K) memory. Sparse Categorical Cross-Entropy accepts integer class labels (0 to K-1) of shape (N, 1) and computes cross-entropy directly without one-hot expansion, saving significant RAM on large vocabularies (e.g. 50,000 classes)."),
    ("Explain computational graphs and automatic differentiation (Autograd).",
     "A computational graph represents mathematical operations as directed acyclic graphs (DAGs) where nodes are operations and edges are tensors. Automatic differentiation traverses the graph using the chain rule, decomposing complex matrix equations into primitive operations with known analytic derivatives, tracking intermediate variables dynamically during the forward pass."),
    ("What is the difference between Reverse-Mode and Forward-Mode automatic differentiation?",
     "Forward-mode computes derivatives alongside the forward pass; efficient when outputs >> inputs. Reverse-mode (backpropagation) performs a forward pass to store intermediate activations, then sweeps backward from outputs to inputs. Reverse-mode is vastly more efficient for neural networks where inputs (millions of weights) >> outputs (single scalar loss)."),
    ("What are residual skip connections (ResNet) and why do they solve degradation?",
     "Skip connections add the input of a layer directly to its output: y = F(x, {W}) + x. Instead of forcing layers to fit an underlying mapping H(x), they fit the residual mapping F(x) = H(x) - x. During backpropagation, the identity term (+x) creates a direct gradient highway where gradients propagate backward unaltered (∂y/∂x = ∂F/∂x + 1), completely bypassing vanishing gradients."),
    ("Explain the Forward Pass computational complexity of a Fully Connected layer.",
     "For an input vector of dimension d_in and output dimension d_out, the matrix multiplication W * x requires d_in * d_out multiplications and additions, yielding O(d_in * d_out) FLOPs per sample, and storing W requires d_in * d_out parameters."),
    ("What is Gradient Checking (Grad Check) and how does it verify backprop implementations?",
     "Grad check compares analytic gradients ∂L/∂W computed by backprop against numerical two-sided finite difference approximations: (L(W + ε) - L(W - ε)) / (2ε). A relative error <= 1e-7 verifies that backpropagation is mathematically bug-free."),
    ("What is inductive bias in neural network architectures?",
     "Inductive bias is the set of architectural assumptions a model relies on to predict outputs on unseen data. MLPs have weak inductive bias (assuming only smoothness). CNNs have strong inductive bias (spatial locality and translation equivariance). RNNs assume sequential temporal causality. Strong inductive bias requires less training data to learn specific domain patterns."),
    ("What is catastrophic forgetting in neural networks?",
     "Catastrophic forgetting occurs when a neural network trained on Task A is subsequently trained on Task B: gradient updates overwrite the weight representations established for Task A, causing performance on Task A to abruptly collapse."),
    ("Explain the difference between Parameter and Hyperparameter in deep learning.",
     "Parameters are internal configuration variables learned automatically from data during training (weights W, biases b). Hyperparameters are external configuration choices set by the practitioner prior to training that govern the learning process (learning rate, batch size, number of layers, activation functions, dropout rate).")
]

C4_02_KERAS_TF = [
    ("Compare Keras Sequential API, Functional API, and Model Subclassing.",
     "Sequential API: linear stack of layers with single input and single output; simple but cannot handle shared layers, multi-inputs, or residual skips. Functional API: treats layers as callable functions on tensors ('y = Dense()(x)'); supports arbitrary DAGs, multiple inputs/outputs, and skip connections. Model Subclassing: inherit from 'tf.keras.Model' and implement '__init__' and 'call()'; provides complete dynamic imperative control in Python, but loses serialization and static graph inspection."),
    ("Explain Eager Execution vs Graph Execution ('@tf.function') in TensorFlow 2.",
     "Eager execution evaluates operations imperatively and immediately in Python, enabling intuitive debugging and line-by-line inspection. Graph execution ('@tf.function') parses Python code into an optimized, language-independent computational C++ graph (AutoGraph), performing constant folding, subexpression elimination, and parallel kernel execution across GPUs."),
    ("How does 'tf.data.Dataset' optimize data pipeline throughput?",
     "It constructs asynchronous, multi-threaded ETL pipelines. Key optimizations: '.prefetch(tf.data.AUTOTUNE)' overlaps GPU training with CPU data loading; '.interleave()' parallelizes disk reads across files; '.map(num_parallel_calls=AUTOTUNE)' parallelizes batch preprocessing; '.cache()' caches processed data in memory."),
    ("Explain the Adam optimizer and why it combines AdaGrad and RMSprop.",
     "Adam (Adaptive Moment Estimation) maintains exponentially decaying averages of past gradients (first moment m_t, momentum) and past squared gradients (second moment v_t, RMSprop adaptive learning rate): m_t = β1 m_{t-1} + (1 - β1) g_t; v_t = β2 v_{t-1} + (1 - β2) g_t². It applies bias corrections m̂_t and v̂_t to account for initialization at zero, updating weights via W = W - η * m̂_t / (sqrt(v̂_t) + ε)."),
    ("What is AdamW and why is it preferred over Adam with L2 regularization?",
     "In Adam, standard L2 regularization adds λW to the gradient, which gets scaled by the adaptive second moment sqrt(v_t), effectively weakening the regularization penalty on weights with large historical gradients. AdamW decouples weight decay from the gradient update, subtracting λW directly from the weight after the adaptive step, restoring true weight decay generalization."),
    ("Explain the role of Keras Callbacks and name four essential built-in callbacks.",
     "Callbacks inject custom logic at specific stages of training (epoch start/end, batch start/end). Key callbacks: (1) 'EarlyStopping' halts training when validation loss stops improving, preventing overfitting. (2) 'ModelCheckpoint' saves model weights periodically when validation metric hits a new record. (3) 'ReduceLROnPlateau' halves learning rate when plateauing. (4) 'TensorBoard' logs metrics and histograms for live visualization."),
    ("How does 'tf.GradientTape' compute custom gradients in custom training loops?",
     "'with tf.GradientTape() as tape:' records forward operations executed on watched tensors in memory. Calling 'grads = tape.gradient(loss, model.trainable_variables)' uses reverse-mode automatic differentiation to compute gradients, which are then applied to weights using 'optimizer.apply_gradients(zip(grads, vars))'."),
    ("What is the difference between 'model.compile()' parameters: optimizer, loss, and metrics?",
     "Optimizer specifies the gradient update algorithm (e.g. Adam). Loss is the scalar objective function minimized during backpropagation. Metrics (e.g. accuracy, AUC) are tracked and displayed for human evaluation but do NOT directly contribute to backpropagation gradients."),
    ("How do you save and serialize Keras models (.keras vs SavedModel format)?",
     "The native '.keras' format is a zip archive containing model architecture (JSON), weights (HDF5/binary), and training/optimizer configuration, standard in Keras 3. 'SavedModel' is TensorFlow's native directory format containing computational graphs and variables, standard for serving via TensorFlow Serving and TFLite conversion."),
    ("Explain Mixed Precision Training ('tf.keras.mixed_precision').",
     "Mixed precision executes forward and backward tensor operations in 16-bit floating point (FP16 or BF16) while storing master weights and loss scaling in 32-bit (FP32). This doubles GPU tensor core throughput, halves VRAM consumption, and prevents gradient underflow via dynamic loss scaling."),
    ("What is Distributed Training in TensorFlow and how does 'tf.distribute.MirroredStrategy' work?",
     "MirroredStrategy performs synchronous data parallelism across multiple GPUs on a single machine: it replicates the model on each GPU, splits each mini-batch across GPUs, executes forward and backward passes independently, and aggregates gradients across GPUs using hardware AllReduce (NVLink/NCCL) before updating master weights synchronously."),
    ("What is MultiWorkerMirroredStrategy and parameter server strategy?",
     "MultiWorkerMirroredStrategy extends synchronous data-parallel mirrored training across multiple separate physical machines connected via network. Parameter Server strategy delegates asynchronous parameter storage and updates to dedicated CPU parameter servers while worker machines compute gradients."),
    ("How do custom Keras Layers and custom Models differ in implementation?",
     "Inherit from 'tf.keras.layers.Layer' to create reusable computation blocks (implement '__init__', 'build(input_shape)' to define weights, and 'call(inputs)'). Inherit from 'tf.keras.Model' when the component represents the complete network container requiring training loop orchestration ('fit()', 'evaluate()', 'save()')."),
    ("What is Custom Loss Function in Keras and how do you write Huber Loss?",
     "A custom loss can be a Python function 'def custom_loss(y_true, y_pred): return tf.reduce_mean(...)' or subclass 'tf.keras.losses.Loss'. Huber loss transitions smoothly from quadratic MSE for small errors (|e| <= δ) to linear MAE for large errors (|e| > δ), providing robustness against extreme outliers."),
    ("Explain the difference between Huber loss and Mean Squared Error.",
     "MSE penalizes errors quadratically ((y - ŷ)²), which forces models to bend excessively to accommodate rare extreme outliers. Huber loss penalizes large errors linearly (δ * |e| - 0.5 * δ²), bounding outlier influence while retaining smooth MSE differentiability near zero."),
    ("What are Keras Functional API shared layers and multi-input architectures?",
     "The Functional API allows a single instantiated layer to be called on multiple distinct tensors, sharing its exact weights across different pathways (e.g. Siamese networks). Multi-input models accept disparate data types (e.g. tabular features and image inputs) and concatenate intermediate embeddings before prediction."),
    ("How does 'tf.RaggedTensor' handle variable-length sequential inputs?",
     "Standard tensors require rectangular dimensions, requiring padding with zeros for variable-length text or time-series. 'tf.RaggedTensor' represents nested arrays with non-uniform slice lengths without zero-padding overhead, saving memory and compute in NLP pipelines."),
    ("What is the purpose of 'tf.stop_gradient()'?",
     "'tf.stop_gradient(t)' treats tensor t as a constant during backpropagation, preventing error gradients from flowing backward past that point in the computational graph (essential in target networks for DQN Reinforcement Learning and self-supervised SimSiam)."),
    ("Explain Learning Rate Schedulers in Keras ('tf.keras.callbacks.LearningRateScheduler').",
     "It updates the learning rate at the start of each epoch according to a deterministic schedule function 'lr = schedule(epoch, lr)'. It differs from ReduceLROnPlateau because it updates based on epoch count rather than monitoring validation loss."),
    ("How do you extract intermediate layer activations for feature visualization or Grad-CAM?",
     "Build a multi-output functional model: 'extractor = tf.keras.Model(inputs=base_model.input, outputs=[base_model.get_layer('conv_target').output, base_model.output])'. Passing an image yields both the final classification and the intermediate spatial feature map tensor."),
    ("What is Transfer Learning and Fine-Tuning in Keras?",
     "Transfer learning initializes a network with weights pre-trained on a massive dataset (e.g. ImageNet), freezes all convolutional base layers ('layer.trainable = False'), and trains a newly added classification head. Fine-tuning subsequently unfreezes top convolutional layers and trains them with a very small learning rate (e.g. 1e-5)."),
    ("Why must you re-compile a Keras model after toggling 'layer.trainable = True'?",
     "'layer.trainable' changes which weight tensors are included in 'model.trainable_variables'. Calling 'model.compile()' is mandatory to rebuild the underlying computational graph and update the optimizer's parameter list."),
    ("What is the difference between 'training=True' and 'training=False' in 'model(inputs, training=...)'?",
     "Certain layers behave differently during training vs inference. During training ('training=True'), Dropout randomly zeroes neuron activations, and Batch Normalization computes batch statistics. During inference ('training=False'), Dropout is disabled, and Batch Normalization uses frozen running mean and variance."),
    ("How does TensorFlow Profiler identify GPU bottlenecks?",
     "TensorFlow Profiler captures execution traces on CPUs and GPUs, identifying whether the GPU is underutilized due to CPU data loading bottlenecks ('InputPipelineAnalyzer'), host-device memory copying latency, or sub-optimal kernel memory bandwidth."),
    ("What is TensorFlow Lite (TFLite) and Quantization?",
     "TFLite converts trained TensorFlow models into lightweight, compact flatbuffer formats (.tflite) for edge and mobile devices. Quantization converts 32-bit floating point weights (FP32) to 8-bit integers (INT8), shrinking model size by 75% and accelerating inference on mobile NPUs with negligible accuracy loss."),
    ("What is TensorFlow Serving and how does it achieve high-throughput microservices?",
     "TensorFlow Serving is a high-performance C++ server designed for production ML environments. It exposes gRPC and REST endpoints, loads new model versions dynamically without downtime, supports batching requests across concurrent clients, and executes directly on GPUs."),
    ("How do you implement custom training metrics in Keras?",
     "Subclass 'tf.keras.metrics.Metric' and implement: '__init__' (allocate state variables via add_weight), 'update_state(y_true, y_pred)' (accumulate metric values over batches), 'result()' (compute final metric), and 'reset_state()' (clear accumulators at epoch boundaries)."),
    ("What is Keras Tuner and what search strategies does it support?",
     "Keras Tuner automates hyperparameter optimization for deep networks. It supports: Random Search, Grid Search, Hyperband (uses early stopping on poor trials to evaluate more configurations), and Bayesian Optimization (Gaussian processes)."),
    ("Explain the difference between 'tf.constant' and 'tf.Variable'.",
     "'tf.constant' creates an immutable tensor whose values cannot be altered. 'tf.Variable' creates a mutable tensor backed by a persistent memory buffer whose values are modified in-place via '.assign()' and '.assign_add()', which is how trainable weights are stored."),
    ("What is Keras 3 and how does it achieve multi-backend support?",
     "Keras 3 is a complete ground-up rewrite that decouples the Keras API from TensorFlow, allowing models to run interchangeably on top of TensorFlow, PyTorch, or JAX backends with identical Python code, enabling dynamic framework switching.")
]

C4_03_DL_PREPROC_IMBALANCE = [
    ("How does Dropout prevent overfitting in deep neural networks?",
     "During training, Dropout randomly deactivates each neuron with probability p, zeroing its activation. This prevents neurons from co-adapting and relying on specific neighboring features, forcing the network to learn robust, redundant representations. At inference time, all neurons remain active, scaling weights by (1 - p) to preserve expected activation magnitude."),
    ("What is Inverted Dropout and why is it standard in modern implementations?",
     "Instead of scaling activations down by (1 - p) during inference, Inverted Dropout scales activations UP by 1 / (1 - p) during the training phase. This leaves inference completely untouched, saving computation during production deployment."),
    ("Explain Monte Carlo Dropout (MC Dropout) and how it estimates model uncertainty.",
     "MC Dropout leaves Dropout layers ACTIVE during inference ('training=True') and runs T forward passes (e.g. T = 100) for a single input. The mean of the predictions represents the final prediction; the variance across the T stochastic passes quantifies epistemic (model) uncertainty."),
    ("Compare Batch Normalization and Layer Normalization.",
     "Batch Normalization normalizes activations across the mini-batch dimension for each individual feature channel; dependent on batch size and fails on mini-batches < 16 or variable-length sequences. Layer Normalization normalizes across all feature channels for each individual sample independently; invariant to batch size, making it standard for RNNs and Transformers."),
    ("How does Batch Normalization accelerate neural network training?",
     "It normalizes layer inputs to zero mean and unit variance, then scales and shifts via learnable parameters γ and β. This stabilizes internal activation distributions, smooths the optimization loss landscape, allows substantially higher learning rates, and provides mild regularization."),
    ("What are the learnable parameters in Batch Normalization and why are they needed?",
     "The learnable parameters are γ (scale) and β (shift): y = γ * x̂ + β. They allow the network to learn to undo the normalization if the optimal representation requires unnormalized activations, preserving representational capacity."),
    ("How does Batch Normalization behave differently during Training vs Inference?",
     "During training, it computes mean μ_B and variance σ_B² directly from the current mini-batch and updates exponential moving averages. During inference, batch statistics are unavailable (e.g. single-sample prediction); it normalizes using the frozen historical running mean and running variance accumulated during training."),
    ("Explain Group Normalization and Instance Normalization.",
     "Instance Normalization normalizes across spatial dimensions for each channel individually (widely used in style transfer and GANs). Group Normalization divides channels into groups (e.g. 32 channels per group) and normalizes across channels within each group, providing batch-size-independent normalization for high-resolution computer vision."),
    ("What is Weight Decay in deep learning and how is it related to L2 Regularization?",
     "In standard SGD, L2 regularization (adding 0.5 * λ ||W||² to loss) and Weight Decay (multiplying weights by (1 - ηλ) during updates) are mathematically identical. However, in adaptive optimizers like Adam, they diverge; true weight decay (AdamW) subtracts weight decay directly rather than corrupting adaptive second moment gradients."),
    ("What is Data Augmentation in Computer Vision and name 5 essential techniques.",
     "Data augmentation synthetically expands training datasets by applying label-preserving transformations to images. Techniques: random horizontal/vertical flips, random cropping, affine rotations/shearing, color jittering (brightness, contrast, saturation), and Gaussian blur/noise."),
    ("Explain CutMix and Mixup data augmentation.",
     "Mixup blends two random images and their labels linearly: x̃ = λ x_i + (1 - λ) x_j, ỹ = λ y_i + (1 - λ) y_j. CutMix cuts a rectangular patch from image B and pastes it onto image A, blending labels proportional to the bounding box area. Both prevent overconfidence and enforce linear behavior between classes."),
    ("How do you handle severe class imbalance in deep learning using Class Weights?",
     "Pass 'class_weight' dictionary to 'model.fit()': weights scale the contribution of each sample to the cross-entropy loss based on class rarity: w_j = N / (n_classes * N_j). Minority class gradients are amplified proportionally, penalizing minority misclassifications more heavily."),
    ("Explain Focal Loss and derive its gradient behavior.",
     "Focal Loss FL(p_t) = - α_t (1 - p_t)^γ ln(p_t). For well-classified easy samples (p_t ≈ 0.9), (1 - p_t)^γ is tiny (e.g. 0.1² = 0.01 for γ = 2), suppressing their gradient contributions. For hard, misclassified minority samples (p_t <= 0.5), the modulating factor remains large, focusing backpropagation updates on difficult minority instances."),
    ("What is Label Smoothing and how does it prevent neural network overconfidence?",
     "Standard one-hot targets force logits toward infinity (producing overconfident, poorly calibrated predictions). Label smoothing replaces hard targets with soft targets: y_smooth = (1 - ε) * y + ε / K. This bounds logit magnitudes, provides regularization, and improves probability calibration."),
    ("What are Entity Embeddings for high-cardinality categorical variables in tabular neural networks?",
     "Entity embeddings map discrete categorical values (e.g. 10,000 retail store IDs) to dense, continuous low-dimensional vectors via an Embedding layer ('tf.keras.layers.Embedding'). During backpropagation, the network learns semantic representations where stores with similar customer behavior cluster together in vector space."),
    ("How do you size the embedding dimension for categorical features?",
     "A widely used rule of thumb (popularized by FastAI and Google) is: embedding_dim = min(50, (cardinality + 1) // 2) or embedding_dim = int(cardinality ** 0.25 * 1.6)."),
    ("Explain Contrastive Learning (SimCLR / InfoNCE loss) for self-supervised representation learning.",
     "SimCLR applies two random augmentations to an image to create positive pairs (x_i, x_j), while other images in the mini-batch act as negative pairs. InfoNCE loss maximizes cosine similarity between positive pairs while minimizing similarity with negatives, learning invariant feature representations without human labels."),
    ("What is Triplet Loss and how does it handle face verification and extreme metric learning?",
     "Triplet loss trains on triplets: Anchor (A), Positive (P, same identity), and Negative (N, different identity). Loss L = max(0, ||f(A) - f(P)||² - ||f(A) - f(N)||² + α). It forces the embedding distance between Anchor and Negative to exceed the distance to Positive by at least margin α."),
    ("Explain Hard Negative Mining in metric learning.",
     "Random negative samples are often trivially easy (distance >> margin), contributing zero loss and zero gradients. Hard Negative Mining searches the mini-batch for negatives that violate the margin (||f(A) - f(N)|| < ||f(A) - f(P)|| + α), ensuring every training step provides informative gradients."),
    ("How does Gradient Accumulation enable large batch training on small GPUs?",
     "If a GPU can only fit batch size 16 into VRAM, gradient accumulation processes 4 sequential forward/backward passes of size 16, accumulating (summing) gradients without updating weights. On the 4th step, it updates weights with the accumulated gradient, simulating an effective batch size of 64."),
    ("What is Early Stopping with Model Checkpoint in Keras?",
     "'EarlyStopping(monitor=\"val_loss\", patience=5, restore_best_weights=True)' monitors validation loss, halts training when loss fails to decrease for 5 consecutive epochs, and rolls back model weights to the best recorded epoch, preventing late-epoch overfitting."),
    ("Explain the difference between Pre-activation ResNet and Post-activation ResNet.",
     "Post-activation (original ResNet): Conv -> BN -> ReLU -> Add -> ReLU. Pre-activation (ResNet-v2): BN -> ReLU -> Conv -> Add. In pre-activation, the identity skip path remains completely clean and unobstructed by non-linearities, improving gradient flow in networks exceeding 1000 layers."),
    ("What is Stochastic Depth in deep networks?",
     "Stochastic depth randomly drops entire residual sub-blocks during training with a survival probability p_l, bypassing them via identity skip connections. During inference, all blocks are active. It acts as an ensemble of networks of varying depths, providing powerful regularization."),
    ("Explain Squeeze-and-Excitation (SE) Networks.",
     "SE blocks introduce channel-wise attention: Global Average Pooling compresses spatial features into a channel descriptor vector ('Squeeze'), followed by two FC layers with Sigmoid activation ('Excitation') to learn channel importance weights, dynamically scaling feature maps by their relevance."),
    ("What is Feature Normalization inside deep neural networks (L2 Normalization layer)?",
     "An L2 normalization layer scales embedding vectors to unit length (||x||_2 = 1). In facial recognition (ArcFace, CosFace), unit normalization projects embeddings onto a hypersphere, ensuring classification decisions depend strictly on angular distance rather than vector magnitude."),
    ("Explain how to build balanced data batches using 'tf.data' sampling.",
     "Create two separate datasets (one for positive minority class, one for negative majority class) and use 'tf.data.Dataset.sample_from_datasets([pos_ds, neg_ds], weights=[0.5, 0.5])' to generate dynamically balanced 50:50 mini-batches on-the-fly without duplicate data storage."),
    ("What is Mixstyle in domain generalization?",
     "Mixstyle mixes the feature statistics (mean and variance in Instance Normalization) of images from different domains or styles during training, forcing intermediate layers to learn domain-invariant representations that generalize to unseen environments."),
    ("How do Autoencoders perform unsupervised anomaly detection?",
     "Train an Autoencoder on normal data. The bottleneck forces compression. During inference, normal instances reconstruct with low Mean Squared Error; anomalies cannot be reconstructed accurately because the network never learned their features, producing high reconstruction error."),
    ("What is Spectral Normalization and where is it applied?",
     "Spectral normalization divides layer weight matrices by their largest singular value (spectral norm σ(W)), strictly enforcing a Lipschitz continuity constant of 1. It stabilizes GAN discriminator training and prevents gradient explosion."),
    ("Explain the difference between Aleatoric and Epistemic uncertainty in deep learning.",
     "Aleatoric uncertainty is inherent irreducible noise in data generation (e.g. sensor noise, motion blur); modeled by having the network predict both mean μ(x) and variance σ²(x). Epistemic uncertainty is model ignorance caused by lack of training data in certain regions; estimated via Bayesian Neural Networks or Monte Carlo Dropout.")
]

C4_04_DL_MODEL_EVAL = [
    ("How do you identify Underfitting, Optimal Fitting, and Overfitting from Learning Curves?",
     "Underfitting: Training loss and validation loss both remain high with negligible improvement (high bias). Optimal Fitting: Both training and validation loss decrease steadily and plateau close together with minimal generalization gap. Overfitting: Training loss continues to plummet toward zero while validation loss reverses direction and climbs upward (high variance)."),
    ("Explain the Double Descent phenomenon in modern deep learning.",
     "Traditional statistical theory states that model test error decreases, hits a minimum, and then increases as model capacity grows (U-shaped curve). Deep learning exhibits Double Descent: as model parameters exceed the number of training samples (interpolation threshold), test error initially spikes, but then drops a second time and continues decreasing as over-parameterization increases."),
    ("Why is Accuracy insufficient for evaluating deep tabular and medical models?",
     "Accuracy treats all errors equally and masks minority failure under class imbalance. In cancer detection or fraud prevention, false negatives carry catastrophic financial or life-safety costs. Sensitivity, Specificity, PR-AUC, and Expected Cost are mandatory."),
    ("Explain Area Under the Precision-Recall Curve (PR-AUC / Average Precision) in deep classification.",
     "PR-AUC calculates the area under the curve plotting Precision vs Recall across all thresholds: AP = sum (R_n - R_{n-1}) * P_n. It evaluates ranking quality on positive classes without being inflated by overwhelming true negative counts."),
    ("What is Top-1 vs Top-5 Error Rate in Image Classification?",
     "Top-1 Error: percentage of test images where the model's highest-probability prediction is NOT the ground truth class. Top-5 Error: percentage of images where the true class is not among the model's top 5 highest-probability predictions (standard benchmark for 1000-class ImageNet)."),
    ("Explain Expected Calibration Error (ECE) for assessing neural network calibration.",
     "ECE groups model predictions into M equal-width confidence bins, computing the absolute difference between average confidence and true empirical accuracy per bin weighted by sample count: ECE = sum_{m=1}^M (|B_m| / N) * |acc(B_m) - conf(B_m)|. Lower ECE indicates reliable probabilistic predictions."),
    ("What is Temperature Scaling and why is it effective for post-processing calibration?",
     "Temperature scaling divides raw model logits z by a learned scalar T > 0 before applying Softmax: p̂ = softmax(z / T). Because T is optimized on validation data using negative log-likelihood without changing the argmax, it preserves classification accuracy while adjusting confidence to match empirical reality."),
    ("Explain Grad-CAM (Gradient-weighted Class Activation Mapping) for deep model interpretability.",
     "Grad-CAM computes the gradient of the score for target class c with respect to feature activation maps A^k of the last convolutional layer. Gradients are globally pooled to calculate importance weights α_k^c. A weighted combination of feature maps followed by ReLU yields a coarse 2D heatmap highlighting regions supporting the decision."),
    ("What is Integrated Gradients (Axiomatic Attribution)?",
     "Integrated Gradients calculates feature attributions by integrating the gradients of the model prediction along a straight line path from a neutral baseline x' (e.g. black image or zero embedding) to the input x: Attribution_i = (x_i - x'_i) * int_0^1 (∂F(x' + α(x - x')) / ∂x_i) dα, satisfying Completeness and Implementation Invariance axioms."),
    ("Explain SHAP (SHapley Additive exPlanations) DeepExplainer for neural networks.",
     "DeepExplainer leverages the connection between DeepLIFT and Shapley values from cooperative game theory, recursively passing analytic attribution scores backward through neural network layers based on reference background samples, explaining non-linear feature attributions in real time."),
    ("What is Mean Average Precision (mAP) in Object Detection?",
     "mAP evaluates object detection across all classes. An object detection is a True Positive if Intersection over Union (IoU) with ground truth >= threshold (e.g. 0.5 for mAP@0.5). Average Precision (AP) is the area under the PR curve for a class. mAP is the mean AP averaged across all classes and IoU thresholds (0.50 to 0.95 in COCO)."),
    ("Explain Intersection over Union (IoU / Jaccard Index) for bounding boxes.",
     "IoU = Area of Overlap / Area of Union between predicted bounding box B_p and ground truth box B_gt. An IoU >= 0.5 is standardly accepted as a valid localization."),
    ("What is Dice Coefficient (F1-score) vs IoU in Semantic Image Segmentation?",
     "Dice = 2 * |A ∩ B| / (|A| + |B|) = 2 * TP / (2*TP + FP + FN). IoU = |A ∩ B| / |A ∪ B| = TP / (TP + FP + FN). Mathematically: Dice = 2 * IoU / (1 + IoU). Dice penalizes false positives and false negatives smoothly and is directly differentiable as a loss function (Dice Loss)."),
    ("Explain BLEU score and ROUGE score for generative sequence evaluation.",
     "BLEU (Bilingual Evaluation Understudy) measures n-gram precision between generated text and reference text with a brevity penalty, standard in translation. ROUGE (Recall-Oriented Understudy for Gisting Evaluation) measures n-gram recall, particularly ROUGE-1 (unigram), ROUGE-2 (bigram), and ROUGE-L (Longest Common Subsequence), standard in text summarization."),
    ("What is Perplexity (PPL) in language model evaluation?",
     "Perplexity is the exponentiated average negative log-likelihood per token: PPL = exp(- (1/T) sum_{t=1}^T ln P(w_t | w_{<t})). It measures how surprised the model is by test text; lower perplexity corresponds to a better predictive language model."),
    ("How do you evaluate Inception Score (IS) and Fréchet Inception Distance (FID) for GANs and Diffusion models?",
     "IS evaluates generated images using an Inception-v3 classifier: computes exp(KL(p(y|x) || p(y))), penalizing lack of diversity or realism. FID compares feature activations of real and generated images in Inception-v3 feature space: FID = ||μ_r - μ_g||² + Tr(Σ_r + Σ_g - 2(Σ_r Σ_g)^(1/2)). Lower FID indicates generated images match real distribution statistics."),
    ("What is Adversarial Robustness and how do you test for Fast Gradient Sign Method (FGSM) attacks?",
     "Adversarial examples add imperceptible noise to inputs to induce misclassification: x_adv = x + ε * sign(∇_x L(θ, x, y)). Evaluate robustness by measuring accuracy drop as perturbation magnitude ε increases, and harden models using adversarial training."),
    ("Explain Out-Of-Distribution (OOD) Detection in production neural networks.",
     "OOD detection identifies inputs originating from distributions entirely outside the training domain (e.g. showing a picture of a car to a dermatology classifier). Techniques: Maximum Softmax Probability (MSP), Energy-Based Out-of-Distribution scoring, and Mahalanobis distance in feature space."),
    ("What is Inference Latency vs Throughput in deep learning production?",
     "Latency (P50, P95, P99) is the elapsed time in milliseconds to compute a single prediction for one request. Throughput is the total volume of requests or samples processed per second (QPS) across all concurrent threads and GPUs."),
    ("How do FLOPs and Parameter Counts determine deep learning computational efficiency?",
     "Parameter count dictates memory footprint (RAM/VRAM storage). FLOPs (Floating-Point Operations) measures the mathematical operations required for one forward pass, governing compute runtime. However, real-world latency is also constrained by memory bandwidth (Arithmetic Intensity = FLOPs / Memory Access Bytes)."),
    ("What is Model Pruning (Structured vs Unstructured) and how is it evaluated?",
     "Pruning removes unneeded weights to compress models. Unstructured pruning zeroes individual weights based on magnitude, creating sparse matrices (requires specialized hardware to accelerate). Structured pruning removes entire channels, attention heads, or layers, producing smaller dense matrices that accelerate natively on standard hardware."),
    ("Explain Knowledge Distillation (Teacher-Student network).",
     "A large, high-capacity Teacher network trains a compact Student network. The student minimizes a combined loss: standard cross-entropy with hard labels plus KL divergence with the Teacher's softened probabilities (computed with temperature T > 1), capturing 'dark knowledge' (inter-class relationships)."),
    ("What is Quantization-Aware Training (QAT) vs Post-Training Quantization (PTQ)?",
     "PTQ quantizes weights and activations of a pre-trained model to INT8 after training, which is fast but can cause accuracy drops. QAT models quantization error during the training forward pass using fake-quantization nodes while computing gradients in FP32, allowing the network to adapt and retain full accuracy."),
    ("How does A/B Testing evaluate deep learning models against live production baselines?",
     "Route a random fraction of live traffic (e.g. 50%) to Model A (baseline) and 50% to Model B (new deep model). Measure statistical lift on business KPIs (conversion, retention, CTR) over 2-4 weeks, verifying with hypothesis tests before full rollout."),
    ("What is Canary Deployment in machine learning?",
     "A Canary deployment rolls out a new model to a tiny subset of users (e.g. 1% to 5%) while routing the remaining 95% to the stable model. It monitors telemetry (latency, error codes, crash rates) for an initial burn-in period before incrementally ramping up traffic to 100%."),
    ("Explain Shadow Mode (Dark Launch) deployment.",
     "Shadow mode sends live production requests in parallel to both the active production model and the new candidate model. The candidate model computes predictions for logging and evaluation without serving responses to users, validating production latency, throughput, and stability risk-free."),
    ("What is Feature Drift vs Concept Drift in computer vision models?",
     "Feature drift: shift in visual image properties (e.g. night-time driving, snowy weather, new camera sensor blur). Concept drift: shift in the semantic meaning or relationship to classes (e.g. fashion trends redefining what constitutes 'business casual')."),
    ("Explain Population Stability Index (PSI) applied to deep feature embeddings.",
     "Compute average cosine distance or maximum mean discrepancy (MMD) between production embedding clusters and baseline training embedding clusters. Drastic drops in similarity indicate feature distribution drift."),
    ("What are Golden Evaluation Sets in continuous integration (CI) for deep learning?",
     "A fixed, hand-curated suite of mission-critical regression test examples and difficult edge cases that every newly trained model checkpoint must satisfy before being promoted to staging or production."),
    ("Explain Algorithmic Bias and Disparate Impact in deep learning models.",
     "Disparate impact occurs when a model produces substantially different positive prediction rates across protected demographic groups (Four-Fifths Rule: selection rate for minority group < 80% of majority group). Evaluate using Equalized Odds, Demographic Parity, and Equality of Opportunity metrics.")
]

print("Course 4 banks loaded successfully.")
