"""
Course 2 Part 3 Q&A Banks: Statistics Fundamentals, Probability Distributions, Advanced Statistics, Pandas, Wrangling, Visualization, Regex/APIs
"""

C2_05_STATS = [
    ("Explain the difference between Mean, Median, and Mode in skewed distributions.",
     "The Mean is the arithmetic average, sensitive to extreme outliers. The Median is the middle value of sorted data, robust to outliers. The Mode is the most frequent value. In a right-skewed (positively skewed) distribution: Mode < Median < Mean. In a left-skewed (negatively skewed) distribution: Mean < Median < Mode."),
    ("Why is sample variance divided by (N - 1) instead of N (Bessel's Correction)?",
     "Dividing by N systematically underestimates the true population variance because sample deviations are measured around the sample mean x̄ rather than the true population mean μ. Bessel's correction (dividing by N - 1) provides an unbiased estimator: E[s²] = σ²."),
    ("State the Central Limit Theorem (CLT) and its practical significance in machine learning.",
     "The CLT states that the sampling distribution of the sample mean approaches a normal distribution as the sample size N grows large (typically N >= 30), regardless of the shape of the underlying population distribution, provided the data has finite variance. This justifies using normal-theory confidence intervals and hypothesis tests on non-normal real-world data."),
    ("What is Chebyshev's Inequality and when is it applied?",
     "Chebyshev's inequality guarantees that for any probability distribution with finite variance, at least 1 - (1/k²) of values fall within k standard deviations of the mean (e.g. at least 75% within 2σ, at least 88.9% within 3σ). It applies universally without requiring normality assumptions."),
    ("Explain Skewness and Kurtosis.",
     "Skewness measures asymmetry around the mean (0 for symmetric, >0 for right-skewed, <0 for left-skewed). Kurtosis measures tail heaviness relative to a normal distribution: Mesokurtic (kurtosis ≈ 3, normal), Leptokurtic (>3, heavy tails, high outlier risk), Platykurtic (<3, light tails)."),
    ("Differentiate between Pearson Correlation and Spearman Rank Correlation.",
     "Pearson correlation evaluates linear relationships between continuous, normally distributed variables: r = Cov(X, Y) / (σ_X σ_Y). Spearman rank correlation evaluates monotonic relationships by computing Pearson on ranked values; it does not assume normality and is robust to extreme outliers."),
    ("What is the difference between Covariance and Correlation?",
     "Covariance measures the joint directional variability of two variables: Cov(X, Y) = E[(X - μ_X)(Y - μ_Y)], but its magnitude depends on the units of measurement. Correlation is covariance standardized by the product of standard deviations: r = Cov(X,Y)/(σ_X σ_Y), producing a dimensionless metric strictly bounded in [-1, 1]."),
    ("What is the 68-95-99.7 Rule (Empirical Rule) for Normal distributions?",
     "For data that is normally distributed: ~68.27% of observations fall within μ ± 1σ, ~95.45% fall within μ ± 2σ, and ~99.73% fall within μ ± 3σ. Any point beyond 3σ is typically flagged as a potential statistical outlier."),
    ("What is a Z-score and how is it calculated?",
     "A Z-score standardizes an individual observation by measuring how many standard deviations it lies from the mean: Z = (x - μ) / σ. It transforms the distribution to have a mean of 0 and standard deviation of 1."),
    ("Explain the Interquartile Range (IQR) and the 1.5 * IQR outlier rule.",
     "IQR = Q3 (75th percentile) - Q1 (25th percentile). Tukey's fence defines outliers as points falling below Q1 - 1.5 * IQR or above Q3 + 1.5 * IQR. Because quartiles are rank-based, IQR is far more robust to extreme anomalies than mean/std."),
    ("What is the difference between standard error (SE) and standard deviation (SD)?",
     "Standard deviation (SD) measures the dispersion of individual data points around the mean in a single dataset. Standard error (SE = SD / sqrt(N)) measures the precision and dispersion of the sample mean estimate across repeated random samples from the population."),
    ("What is a Confidence Interval and how do you interpret a 95% Confidence Interval?",
     "A 95% Confidence Interval [L, U] means that if we repeated the experiment and sampling procedure infinitely many times, 95% of the calculated intervals would contain the true, fixed population parameter. It does NOT mean there is a 95% probability the parameter lies within that specific realized interval."),
    ("Explain the concept of Degrees of Freedom in statistics.",
     "Degrees of freedom (df) is the number of independent values that can vary in an analysis without violating statistical constraints. In estimating variance of N samples, calculating the sample mean imposes 1 constraint, leaving df = N - 1."),
    ("What is a Box Plot (Box-and-Whisker Plot) and what five statistics does it display?",
     "A Box Plot summarizes distributions via the 'Five-Number Summary': Minimum (Q1 - 1.5*IQR), First Quartile (Q1), Median (Q2), Third Quartile (Q3), and Maximum (Q3 + 1.5*IQR). Individual points beyond the whiskers are plotted as individual outlier points."),
    ("Explain the Law of Large Numbers (LLN).",
     "The Weak and Strong Laws of Large Numbers state that as the number of identically distributed, randomly generated trials N increases, the sample average x̄ converges deterministically to the expected value μ: lim_{N->inf} P(|x̄ - μ| > ε) = 0."),
    ("What is Quantile-Quantile (Q-Q) Plot and how is it interpreted?",
     "A Q-Q plot plots the quantiles of sample data against theoretical quantiles of a target distribution (typically standard normal). If the data follows the distribution, points form a straight diagonal line. S-shaped curves indicate heavy or light tails; convex/concave curves indicate skewness."),
    ("What is the difference between point estimation and interval estimation?",
     "A point estimate provides a single best numerical value for a population parameter (e.g. sample mean x̄ = 42.5). An interval estimate specifies a range of plausible values accompanied by a specified degree of confidence (e.g. [40.2, 44.8] with 95% confidence)."),
    ("What is an Unbiased Estimator?",
     "An estimator θ̂ is unbiased if its mathematical expected value equals the true population parameter: E[θ̂] = θ across all possible random samples."),
    ("Explain the Trimmed Mean and Winsorized Mean.",
     "A Trimmed Mean discards a fixed percentage of extreme values from both tails before computing the mean. A Winsorized Mean replaces extreme values with the nearest retained boundary value (e.g. setting all values above the 95th percentile to the 95th percentile value) before computing the mean."),
    ("What is Variance Inflation Factor (VIF) and how does it detect multicollinearity?",
     "VIF measures how much the variance of an estimated regression coefficient is inflated due to collinearity with other predictors: VIF_j = 1 / (1 - R_j²), where R_j² is the R² from regressing feature j on all other features. VIF > 5 or 10 indicates severe multicollinearity."),
    ("Explain the coefficient of variation (CV) and when to use it.",
     "The coefficient of variation CV = (σ / μ) * 100% is a normalized measure of relative dispersion. It enables comparing variability between datasets with completely different units (e.g. comparing volatility of stock prices in USD vs sales volume in units)."),
    ("What is a Bimodal Distribution and what does it typically signify in business data?",
     "A bimodal distribution has two distinct peaks, typically signifying that the dataset is an unsegregated mixture of two distinct sub-populations (e.g. customer heights mixing adult males and females, or purchase amounts mixing retail and wholesale buyers)."),
    ("What is the Geometric Mean and when is it preferred over Arithmetic Mean?",
     "The Geometric Mean (nth root of product of n numbers) is preferred when analyzing multiplicative growth rates, investment returns, compounding ratios, and data spanning multiple orders of magnitude."),
    ("What is the Harmonic Mean and why is it used for F1-Score?",
     "The Harmonic Mean H = 2 / (1/x + 1/y) gives higher weight to smaller values. In classification, F1-Score uses the harmonic mean of Precision and Recall so that a model cannot achieve a high score if either Precision or Recall is terribly low."),
    ("Explain the difference between parametric and non-parametric statistical methods.",
     "Parametric methods assume the data follows a specific theoretical distribution (like Normal) with fixed parameters (mean, variance). Non-parametric methods make no assumptions about probability distributions, operating on ranks or empirical counts (e.g. Mann-Whitney U, Kruskal-Wallis)."),
    ("What is the difference between pooled variance and unpooled variance?",
     "Pooled variance combines the variances of two samples under the assumption that both populations have equal true variances (homoscedasticity). Unpooled variance (used in Welch's t-test) calculates separate sample variances when population variances may differ."),
    ("How does missing data introduce statistical bias if missing not at random (MNAR)?",
     "If data is MNAR, the probability of missingness depends on the unobserved value itself (e.g. high earners refusing to report income). Simple imputation or deletion shifts the sample mean and distorts variance, introducing non-correctable bias unless modeled explicitly."),
    ("What is heteroscedasticity and how does it affect linear models?",
     "Heteroscedasticity occurs when the variance of the residuals is non-constant across levels of an independent variable (e.g. funnel-shaped residual plots). It does not bias regression coefficients, but it invalidates standard error calculations, making t-tests and p-values unreliable."),
    ("Explain Bootstrapping in non-parametric statistics.",
     "Bootstrapping estimates the sampling distribution of almost any statistic by repeatedly resampling the observed dataset with replacement B times (e.g. B = 10,000) and calculating the statistic on each bootstrap sample, generating robust confidence intervals without theoretical distribution assumptions."),
    ("What is the Jackknife resampling method and how does it differ from Bootstrapping?",
     "The Jackknife systematically recalculates the statistic by leaving out one observation at a time (N total resamples of size N-1). Unlike Bootstrapping, which is stochastic and samples with replacement, Jackknife is deterministic.")
]

C2_06_PROB = [
    ("What is the difference between Probability Mass Function (PMF), Probability Density Function (PDF), and Cumulative Distribution Function (CDF)?",
     "PMF P(X = x) assigns discrete probabilities to specific integer outcomes such that sum(P(x)) = 1. PDF f(x) describes continuous probability density where the probability of any single exact point is 0, and probabilities are obtained by integrating over intervals: P(a <= X <= b) = int_a^b f(x) dx. CDF F(x) = P(X <= x) gives the cumulative probability up to value x for both discrete and continuous distributions."),
    ("State Bayes' Theorem mathematically and define prior, likelihood, marginal, and posterior.",
     "P(A|B) = [P(B|A) * P(A)] / P(B). P(A) is the Prior probability of hypothesis A before observing evidence. P(B|A) is the Likelihood of observing evidence B given hypothesis A. P(B) is the Marginal probability (evidence). P(A|B) is the Posterior probability of hypothesis A updated after observing evidence B."),
    ("Explain the difference between Mutually Exclusive events and Independent events.",
     "Mutually exclusive events cannot occur simultaneously: P(A and B) = 0, so P(A or B) = P(A) + P(B). Independent events have no influence on each other's occurrence: P(A|B) = P(A), so P(A and B) = P(A) * P(B). If two events with non-zero probability are mutually exclusive, they CANNOT be independent."),
    ("What is a Bernoulli Trial and how does it relate to the Binomial Distribution?",
     "A Bernoulli trial is a single random experiment with exactly two mutually exclusive outcomes: Success (probability p) and Failure (probability 1 - p). A Binomial distribution Bin(n, p) models the number of successes k observed in n independent and identical Bernoulli trials: P(k) = C(n, k) * p^k * (1 - p)^(n - k)."),
    ("When should you model counts using a Poisson Distribution instead of a Binomial Distribution?",
     "Use a Poisson distribution Po(λ) when modeling the number of rare events occurring in a fixed interval of time or space with a known constant average rate λ, where events occur independently (e.g. server requests per second, website crashes per month). The Poisson is the mathematical limit of the Binomial as n -> inf and p -> 0 with n*p = λ."),
    ("Explain the memoryless property of the Exponential Distribution.",
     "The Exponential distribution models the waiting time between Poisson events. It is memoryless: P(X > s + t | X > s) = P(X > t). The probability that an event occurs in the next t minutes does not depend on how much time s has already elapsed without the event occurring."),
    ("What is the Uniform Distribution and what are its mean and variance?",
     "A continuous Uniform distribution U(a, b) assigns constant probability density f(x) = 1 / (b - a) across the interval [a, b]. Mean = (a + b) / 2. Variance = (b - a)² / 12."),
    ("What is Maximum Likelihood Estimation (MLE)?",
     "MLE is a method of estimating parameters θ of a probability distribution by finding parameter values that maximize the likelihood function L(θ; X) = prod(f(x_i; θ)), typically achieved by maximizing the log-likelihood sum(log f(x_i; θ)) via calculus or gradient descent."),
    ("How does Maximum A Posteriori (MAP) estimation differ from MLE?",
     "MLE finds parameters that maximize likelihood alone: θ_MLE = argmax P(X|θ). MAP incorporates prior beliefs via Bayes' rule: θ_MAP = argmax P(X|θ) P(θ). When a Gaussian prior is placed on weights, MAP is mathematically equivalent to L2 regularization (Ridge); a Laplace prior corresponds to L1 (Lasso)."),
    ("Explain the Law of Total Probability.",
     "If {B1, B2, ..., Bn} forms a partition of the sample space, then for any event A: P(A) = sum_{i=1}^n P(A|B_i) * P(B_i). It allows computing marginal probabilities by conditioning across all mutually exclusive scenarios."),
    ("What is Joint Probability vs Marginal Probability vs Conditional Probability?",
     "Joint probability P(A and B) is the likelihood that both events occur simultaneously. Marginal probability P(A) is the probability of an event irrespective of the outcome of other variables. Conditional probability P(A|B) = P(A and B) / P(B) is the probability of A occurring given that B is known to have occurred."),
    ("What is a Random Variable?",
     "A random variable is a mathematical function that maps outcomes of a random process in a sample space to real numbers. It can be discrete (countable set of values) or continuous (uncountable real continuum)."),
    ("Explain Expectation and Variance of a random variable.",
     "Expected value E[X] is the probability-weighted average: sum(x * P(x)) for discrete, int(x * f(x) dx) for continuous. Variance Var(X) = E[(X - E[X])²] = E[X²] - (E[X])² measures dispersion around the expectation."),
    ("What is the Geometric Distribution and what is its expected value?",
     "The Geometric distribution models the number of Bernoulli trials X required to achieve the first success: P(X = k) = (1 - p)^(k - 1) * p. Its expected value is E[X] = 1 / p."),
    ("What is the Hypergeometric Distribution and how does it differ from the Binomial?",
     "The Binomial distribution models sampling WITH replacement (independent trials, constant p). The Hypergeometric distribution models sampling WITHOUT replacement from a finite population of size N containing K successes, where probabilities change on every draw."),
    ("Explain the Beta Distribution and why it is commonly used as a conjugate prior for Binomial likelihood.",
     "The Beta distribution Beta(α, β) is defined over the interval [0, 1], making it ideal for modeling probabilities and conversion rates. When combined with a Binomial likelihood of k successes and n-k failures, the posterior distribution is analytically Beta(α + k, β + n - k), enabling closed-form Bayesian updating."),
    ("What is the Gamma Distribution?",
     "The Gamma distribution is a two-parameter family of continuous distributions that generalizes the Exponential distribution to model waiting times until α Poisson events occur."),
    ("What is the Chi-Square Distribution and how is it related to the Normal Distribution?",
     "A Chi-Square distribution with k degrees of freedom is the distribution of the sum of squares of k independent standard normal random variables: Q = sum_{i=1}^k Z_i². It is the basis for goodness-of-fit and contingency table tests."),
    ("Explain Student's t-Distribution and why it has heavier tails than the Normal Distribution.",
     "The t-distribution arises when estimating the mean of a normally distributed population when sample size is small and population standard deviation σ is unknown. Because sample variance s² introduces additional estimation uncertainty, the t-distribution has fatter tails than the Gaussian, approaching normal as df -> inf."),
    ("What is the F-Distribution and where is it used in data science?",
     "The F-distribution is the ratio of two independent Chi-Square distributed variables divided by their respective degrees of freedom: F = (U1 / d1) / (U2 / d2). It is the test statistic in ANOVA and tests for equality of variances between two populations."),
    ("What is Covariance of independent random variables?",
     "If two random variables X and Y are independent, their covariance Cov(X, Y) = E[XY] - E[X]E[Y] = 0. However, the converse is not always true: zero covariance only indicates absence of linear relationship; non-linear dependencies may still exist."),
    ("Explain Markov's Inequality.",
     "For any non-negative random variable X and constant a > 0: P(X >= a) <= E[X] / a. It provides an upper bound on the probability that a non-negative variable exceeds a threshold based strictly on its mean."),
    ("What is a Probability Generating Function (PGF) and Moment Generating Function (MGF)?",
     "The MGF M_X(t) = E[e^(tX)] uniquely determines the probability distribution. Taking the nth derivative evaluated at t = 0 yields the nth non-central moment: M_X^(n)(0) = E[X^n]."),
    ("Explain the Monte Carlo method in probabilistic simulations.",
     "Monte Carlo methods use repeated pseudo-random sampling from probability distributions to approximate numerical results that are analytically intractable (e.g. multi-dimensional integration, project burndown risk simulation, option pricing)."),
    ("What is Inverse Transform Sampling?",
     "Inverse transform sampling generates random numbers from any distribution with an invertible CDF F(x): sample u ~ Uniform(0, 1), then x = F^(-1)(u) has the desired distribution."),
    ("What is a Multinomial Distribution?",
     "The Multinomial distribution generalizes the Binomial distribution to outcomes with k > 2 mutually exclusive categories across n independent trials (e.g. rolling a 6-sided die n times)."),
    ("Explain the Dirichlet Distribution and its application in Latent Dirichlet Allocation (LDA).",
     "The Dirichlet distribution is a multivariate generalization of the Beta distribution over probability simplices (vectors summing to 1). In topic modeling (LDA), it serves as the conjugate prior for multinomial document-topic and topic-word distributions."),
    ("What is the difference between Frequentist and Bayesian probability interpretations?",
     "Frequentists view probability as the long-run relative frequency of repeatable events under identical conditions; parameters are fixed, unknown constants. Bayesians view probability as a subjective degree of belief quantified using probability theory, updating prior distributions using evidence into posterior distributions."),
    ("Explain the Monty Hall Problem and its counter-intuitive probabilistic solution.",
     "In a 3-door game with 1 car and 2 goats, you pick Door 1 (P = 1/3). Host opens Door 3 showing a goat. Switching to Door 2 doubles your win probability to 2/3 because the host's action is constrained: the 2/3 probability that the car was behind an unchosen door collapses entirely onto the remaining unopened door."),
    ("What is the Birthday Paradox and what is the underlying probabilistic formula?",
     "The probability that in a group of n people, at least two share a birthday exceeds 50% with just n = 23 people. It is computed via the complement: P(at least 1 match) = 1 - P(no matches) = 1 - prod_{i=0}^{n-1} (365 - i) / 365.")
]

print("Course 2 Part 3 banks loaded successfully.")
