"""
Course 2 Part 4 Q&A Banks: Advanced Statistics, Pandas, Data Wrangling, Visualization, Regex/JSON/APIs
"""

C2_07_ADVSTATS = [
    ("Explain the Null Hypothesis (H0) and Alternative Hypothesis (H1).",
     "The Null Hypothesis (H0) assumes no effect, no difference, or no relationship exists (default status quo). The Alternative Hypothesis (H1 or Ha) contradicts H0, asserting that an observed difference is real, statistically significant, or driven by an underlying effect."),
    ("Differentiate between Type I Error (α) and Type II Error (β).",
     "Type I error (α) is a False Positive: rejecting a true null hypothesis (e.g. concluding a drug is effective when it is not). Type II error (β) is a False Negative: failing to reject a false null hypothesis (e.g. concluding a drug is ineffective when it actually works). Power = 1 - β."),
    ("Define the p-value rigorously and refute common misinterpretations.",
     "The p-value is the probability, assuming the null hypothesis is true, of observing a test statistic as extreme as, or more extreme than, the observed data. It is NOT the probability that the null hypothesis is true, nor is it the probability that results were produced by random chance alone."),
    ("What is significance level (alpha) and how is it chosen?",
     "Alpha (α) is the maximum acceptable threshold for committing a Type I error (commonly set to 0.05 or 0.01). If p-value <= α, we reject H0. In high-consequence applications (clinical trials, fraud detection), α is set lower (e.g. 0.001) to protect against false positives."),
    ("Explain the difference between a One-Tailed test and a Two-Tailed test.",
     "A two-tailed test evaluates for any directional difference (H1: μ != μ0), dividing α equally across both tails (α/2 each). A one-tailed test tests for an effect in a single specific direction (H1: μ > μ0 or μ < μ0), concentrating the entire α in that tail and providing higher statistical power."),
    ("When should you use a Student's t-test vs a Z-test?",
     "Use a Z-test when the population standard deviation σ is known and sample size N is large (N >= 30). Use a Student's t-test when the population standard deviation σ is unknown and must be estimated from the sample standard deviation s, especially for small samples (N < 30)."),
    ("Differentiate between One-Sample, Two-Sample Independent, and Paired t-tests.",
     "One-Sample: compares sample mean to a known benchmark value. Two-Sample Independent: compares means of two unrelated groups (e.g. control vs treatment group in A/B test). Paired t-test: compares means from the same subjects measured twice (e.g. blood pressure before and after medication), controlling for subject-specific baseline variability."),
    ("What are the core assumptions of an independent two-sample t-test?",
     "Assumptions: (1) Independence of observations, (2) Continuous outcome variable, (3) Normal distribution of data within each group (or N >= 30 by CLT), and (4) Homogeneity of variance (homoscedasticity across groups; if violated, use Welch's t-test)."),
    ("Explain Welch's t-test and why it is preferred over Student's t-test in production.",
     "Welch's t-test does not assume equal population variances between the two groups. It adjusts degrees of freedom using the Welch-Satterthwaite equation, maintaining robust Type I error rates even when sample sizes and variances differ greatly."),
    ("What is ANOVA (Analysis of Variance) and why shouldn't you run multiple t-tests instead?",
     "ANOVA tests whether the means of three or more groups are statistically different by comparing between-group variance to within-group variance. Running multiple pairwise t-tests causes Family-Wise Error Rate inflation: for 5 groups (10 pairwise tests at α = 0.05), overall false positive risk jumps to 1 - (1 - 0.05)^10 ≈ 40%."),
    ("How does One-Way ANOVA calculate the F-statistic?",
     "F = MS_between / MS_within, where MS_between = SS_between / (k - 1) and MS_within = SS_within / (N - k). If group means differ significantly, MS_between exceeds random within-group variance MS_within, producing a large F-ratio (F >> 1) and small p-value."),
    ("What is a Post-Hoc test (e.g. Tukey's HSD) following ANOVA?",
     "If ANOVA rejects H0, it proves that at least two group means differ, but does not identify which specific pairs differ. Post-hoc tests like Tukey's Honestly Significant Difference (HSD) test all pairwise comparisons while controlling the Family-Wise Error Rate."),
    ("Explain Two-Way ANOVA and interaction effects.",
     "Two-Way ANOVA evaluates the impact of two independent categorical factors on a continuous outcome simultaneously. An interaction effect occurs when the effect of Factor A depends on the level of Factor B (e.g. medicine dosage effectiveness depends on patient age group)."),
    ("What is the Chi-Square (χ²) Test of Independence?",
     "The Chi-Square test evaluates whether two categorical variables are statistically independent. It computes the test statistic χ² = sum((O - E)² / E), where O is observed cell frequency and E is expected frequency under the assumption of independence. df = (rows - 1) * (cols - 1)."),
    ("Explain the Chi-Square Goodness-of-Fit test.",
     "Goodness-of-fit evaluates whether an observed categorical sample distribution matches a hypothesized theoretical distribution (e.g. testing whether dice rolls follow a uniform distribution or gene frequencies match Mendelian ratios)."),
    ("What is Fisher's Exact Test and when is it preferred over Chi-Square?",
     "Fisher's Exact Test calculates exact hypergeometric probabilities for 2x2 contingency tables. It is preferred when sample sizes are small or expected frequencies in any cell drop below 5, where Chi-Square large-sample approximations break down."),
    ("What are non-parametric alternatives to the t-test and ANOVA?",
     "For independent two-sample t-test: Mann-Whitney U test (Wilcoxon rank-sum). For paired t-test: Wilcoxon signed-rank test. For One-Way ANOVA: Kruskal-Wallis test. These operate on ranked data and do not require normality."),
    ("Explain multiple testing corrections: Bonferroni vs False Discovery Rate (Benjamini-Hochberg).",
     "Bonferroni controls Family-Wise Error Rate (FWER) by setting α_new = α / m (where m is the number of hypotheses), but it is overly conservative and inflates Type II errors. Benjamini-Hochberg controls the False Discovery Rate (FDR = expected proportion of false positives among rejected hypotheses), providing significantly higher statistical power for high-throughput testing (e.g. thousands of A/B test metrics or genomic loci)."),
    ("What is Cohen's d and why is Effect Size important alongside p-values?",
     "Cohen's d = (μ1 - μ2) / s_pooled measures the standardized magnitude of the difference between groups. With massive datasets (N = 1,000,000), trivial, meaningless differences achieve tiny p-values (p < 0.0001); effect size quantifies whether the difference has practical, real-world business significance."),
    ("Explain statistical Power Analysis and how to determine required sample size for an A/B test.",
     "Power analysis relates four variables: Alpha (α), Power (1 - β), Effect Size (minimum detectable effect MDE), and Sample Size (N). Given α = 0.05, power = 0.80, and target MDE, power formulas determine the exact minimum sample size required before running an experiment to avoid underpowered tests."),
    ("What is Sample Ratio Mismatch (SRM) in A/B testing and why is it dangerous?",
     "SRM occurs when the observed ratio of visitors in Treatment vs Control deviates significantly from the intended design (e.g. expecting 50:50, but observing 52:48 with χ² p < 0.001). SRM indicates severe underlying execution bugs (broken redirect bots, user filtering, browser caching) that invalidate all experimental conclusions."),
    ("What is the difference between Fixed Effects and Random Effects models?",
     "Fixed effects models assume observed levels of a factor are fixed and of direct interest, estimating specific parameters for each group. Random effects models treat levels as random draws from a broader population distribution, modeling variance components (common in hierarchical/multilevel modeling)."),
    ("Explain the difference between R-squared and Adjusted R-squared in regression.",
     "R² measures the proportion of variance in the dependent variable explained by independent features. However, R² mechanically increases with every added feature, even random noise. Adjusted R² penalizes the addition of non-informative predictors: Adj R² = 1 - [(1 - R²)(N - 1) / (N - p - 1)]."),
    ("What is the Durbin-Watson statistic and what does it detect?",
     "The Durbin-Watson statistic tests for first-order autocorrelation in regression residuals (common in time-series data). Values range from 0 to 4: a value around 2 indicates zero autocorrelation, values < 2 indicate positive autocorrelation, and values > 2 indicate negative autocorrelation."),
    ("Explain Cook's Distance and Leverage in regression diagnostics.",
     "Leverage measures how far an observation's feature values are from the mean of all predictors. Cook's Distance measures the overall influence of an observation by calculating how much all fitted values change when that observation is omitted. Points with Cook's distance > 1 or 4/N exert outsized leverage and skew model coefficients."),
    ("What is Logistic Regression and why is the Logit (log-odds) link function used?",
     "Logistic regression models binary outcomes P(y = 1|x) by mapping linear combinations of features w^T x to probabilities using the sigmoid function σ(z) = 1 / (1 + e^(-z)). The logit link function log(p / (1 - p)) = w^T x transforms probabilities bounded in [0, 1] to unbounded log-odds in (-inf, +inf), making linear modeling mathematically valid."),
    ("How do you interpret coefficients in Logistic Regression?",
     "For a continuous feature x, a one-unit increase multiplies the odds of the positive outcome by e^(w_i) (the Odds Ratio). If w = 0.693, e^(0.693) ≈ 2.0, meaning odds of the outcome double for every unit increase in x."),
    ("What is the AIC (Akaike Information Criterion) and BIC (Bayesian Information Criterion)?",
     "AIC = 2k - 2ln(L) and BIC = k ln(N) - 2ln(L) evaluate model quality by balancing goodness of fit (log-likelihood L) with model complexity (number of parameters k). Lower values indicate better models. BIC penalizes extra parameters more heavily than AIC as sample size N grows."),
    ("Explain the Kolmogorov-Smirnov (K-S) test.",
     "The K-S test evaluates whether a sample distribution matches a reference distribution (one-sample) or whether two independent sample distributions differ (two-sample). The test statistic D is the maximum vertical distance between the empirical cumulative distribution functions (ECDFs)."),
    ("What is Survival Analysis and how does the Kaplan-Meier estimator handle censored data?",
     "Survival analysis models the expected duration of time until an event occurs (e.g. customer churn, machine failure). Right-censored data occurs when subjects leave the study without experiencing the event. The Kaplan-Meier estimator calculates step-wise survival probabilities at each event time, correctly factoring in censored subjects up to their last observation.")
]

C2_08_PANDAS = [
    ("Explain the internal memory layout of a Pandas DataFrame.",
     "A Pandas DataFrame is organized into a 2D tabular structure backed by a BlockManager (or PyArrow Array in Pandas 2.0+). The BlockManager groups columns of identical datatypes (e.g. all float64 columns) into contiguous 2D NumPy arrays, while Series are 1D arrays with labeled indices."),
    ("What is the difference between 'loc' and 'iloc' in Pandas?",
     "'loc' is label-based indexing: it selects rows and columns using index labels and column names (inclusive of both start and end endpoints). 'iloc' is integer-position-based indexing: it selects elements using 0-based integer coordinates (exclusive of the stop endpoint, following Python slice conventions)."),
    ("What are 'at' and 'iat' accessors and when should you use them?",
     "'at[row_label, col_label]' and 'iat[row_idx, col_idx]' provide ultra-fast scalar access to a single element. Because they bypass Series construction and overhead checks in loc/iloc, scalar access is up to 10x faster inside performance-critical loops."),
    ("Explain the 'Split-Apply-Combine' strategy in Pandas 'groupby()'.",
     "Split: the DataFrame is partitioned into groups based on key columns. Apply: an aggregation (e.g. sum, mean), transformation (e.g. z-score per group), or filter is applied to each independent group. Combine: the individual group results are concatenated back into a single aligned DataFrame/Series."),
    ("What is the difference between 'df.groupby().aggregate()', 'transform()', and 'filter()'?",
     "'aggregate()' reduces each group to a single summary row per group. 'transform()' returns an object of the EXACT SAME row count as the original DataFrame, broadcasting group statistics back to individual rows. 'filter()' discards entire groups that fail a boolean predicate."),
    ("How does 'pd.merge()' perform inner, outer, left, and right joins?",
     "Inner: retains only rows with matching keys in both DataFrames. Left: retains all rows from the left DataFrame, filling unmatched right columns with NaN. Right: retains all rows from the right DataFrame. Outer: retains all rows from both DataFrames, filling missing values with NaN on either side."),
    ("What is MultiIndex (hierarchical index) and how do you unstack it?",
     "A MultiIndex allows indexing along multiple hierarchical dimensions (levels). 'df.unstack(level=-1)' pivots an inner row index level into columns; 'df.stack()' pivots column headers into the innermost row index."),
    ("How does 'pivot_table()' differ from 'pivot()' in Pandas?",
     "'pivot()' reshapes data without aggregation; it throws a ValueError if duplicate key combinations exist. 'pivot_table()' handles duplicates by applying an aggregation function ('aggfunc='mean'' by default) and supports margins (subtotals)."),
    ("Explain 'pd.melt()' and why it is essential for tidying wide data.",
     "'pd.melt()' unpivots a DataFrame from wide format (many columns) to long format (few columns with identifier variables and value-variable pairs), which is the standard format required for tidy data analysis, Seaborn plotting, and relational modeling."),
    ("What is the difference between 'df.dropna(how=\"any\")' and 'df.dropna(how=\"all\")'?",
     "'how=\"any\"' drops a row/column if even a single NaN value is present. 'how=\"all\"' drops a row/column ONLY if every single value along that axis is NaN. The 'subset' parameter restricts checks to designated columns."),
    ("How does 'df.fillna(method=\"ffill\")' differ from 'bfill'?",
     "'ffill' (forward-fill) propagates the last known valid observation forward until the next valid value is found (essential for non-stationary time series). 'bfill' (backward-fill) propagates the next valid value backward."),
    ("What is interpolation in Pandas and when is it preferred over simple fillna?",
     "'df.interpolate(method=\"linear\" or \"spline\")' estimates missing values by fitting continuous mathematical curves between surrounding points, preserving smooth trends in continuous time-series sensor or financial data."),
    ("Explain Categorical dtypes and how they conserve RAM.",
     "Categorical columns store data as an integer array of codes (0, 1, 2) pointing to a small index of unique categories. For low-cardinality string columns repeated across millions of rows, memory drops by up to 90% and grouping speed increases significantly."),
    ("What is the difference between 'df.isin()' and 'df.query()'?",
     "'df[col.isin([val1, val2])]' filters for membership using a list. 'df.query(\"col in [val1, val2]\")' evaluates expressions using NumExpr, avoiding intermediate memory allocations and offering cleaner syntax for complex compound filters."),
    ("Why should you avoid using Python's 'for index, row in df.iterrows():'?",
     "'iterrows()' converts every row into a new Pandas Series object, which discards dtypes (casting mixed columns to object) and incurs massive Python function overhead. Instead, use vectorized operations, list comprehensions, or 'itertuples()'."),
    ("What does 'df.itertuples(index=False, name=\"Row\")' return and why is it faster?",
     "'itertuples()' generates lightweight namedtuples directly in C, preserving native column data types and running ~50x to 100x faster than iterrows()."),
    ("Explain how to downcast numerical data types to optimize memory.",
     "Use 'pd.to_numeric(col, downcast=\"integer\")' or 'downcast=\"float\"'. It automatically downcasts 64-bit types (int64, float64) to the smallest lossless integer (int8, int16, int32) or float (float32), dramatically reducing memory footprint."),
    ("What is the purpose of 'df.memory_usage(deep=True)'?",
     "Standard memory_usage() reports only pointers for object columns. 'deep=True' inspects the system heap recursively to measure the exact byte size of underlying string and Python objects, providing true RAM metrics."),
    ("How do window functions work in Pandas (rolling, expanding, exponential)?",
     "'df.rolling(window=7).mean()' computes moving averages over fixed sliding windows. 'df.expanding().sum()' computes cumulative metrics from the start of data. 'df.ewm(span=20).mean()' computes exponential moving averages with decay weights."),
    ("What is the difference between 'df.corr()' methods ('pearson', 'spearman', 'kendall')?",
     "'pearson' evaluates linear correlation on continuous data. 'spearman' evaluates monotonic relationships on ranked values. 'kendall' (Kendall's tau) evaluates concordance based on pairwise ranks, offering superior robustness for small datasets with ties."),
    ("Explain the difference between 'pd.concat(axis=0)' and 'pd.concat(axis=1)'.",
     "'axis=0' appends rows vertically, aligning columns by name and filling missing columns with NaN. 'axis=1' concatenates columns horizontally, aligning rows by index labels."),
    ("What is 'df.duplicated(keep=\"first\")' vs 'keep=False'?",
     "'keep=\"first\"' flags duplicates as True starting from the second occurrence onward. 'keep=False' flags ALL occurrences of duplicated rows as True, enabling complete extraction or deletion of all ambiguous non-unique records."),
    ("How does 'pd.crosstab()' differ from 'pivot_table()'?",
     "'pd.crosstab()' calculates frequency count contingency tables between two or more categorical factors by default, optimized for categorical interactions and Chi-Square preparation. 'pivot_table()' is designed for general numeric aggregations."),
    ("Explain how string operations work via the '.str' accessor.",
     "The '.str' accessor provides vectorized string operations that handle NaNs safely: '.str.strip()', '.str.lower()', '.str.extract(r'(\\d+)')', and '.str.contains(regex)'. It executes without manual Python string iteration."),
    ("How do datetime accessors work via the '.dt' accessor?",
     "When a column is datetime64, '.dt' exposes vectorized calendar operations: '.dt.year', '.dt.month', '.dt.day_name()', '.dt.quarter', and '.dt.hour', enabling rapid feature engineering for seasonal trends."),
    ("What is 'pd.DateOffset' and how does it support business calendar arithmetic?",
     "DateOffset allows adding/subtracting semantic business intervals (e.g. 'df[\"Date\"] + pd.DateOffset(months=3)' or 'pd.offsets.BDay(5)' for 5 business days, skipping weekends and holidays automatically)."),
    ("What is the difference between 'df.eval()' and 'df.query()'?",
     "'df.query()' filters rows using string boolean expressions. 'df.eval()' executes column arithmetic (e.g. 'df.eval(\"C = A + B * 2\")') using NumExpr, accelerating matrix math on large DataFrames by computing directly in CPU cache."),
    ("How does 'df.replace()' differ from 'df.fillna()'?",
     "'fillna()' replaces ONLY NaN/null values. 'replace(to_replace, value)' replaces arbitrary specific values, regex patterns, or lists of values throughout the DataFrame."),
    ("What is 'pd.get_dummies()' and what is the purpose of 'drop_first=True'?",
     "'pd.get_dummies()' one-hot encodes categorical variables into binary indicator columns. 'drop_first=True' removes the first category column, preventing the 'Dummy Variable Trap' (perfect multicollinearity where the dropped category is represented when all other indicators are 0)."),
    ("What is the Arrow engine in Pandas 2.0 and what are its advantages?",
     "Pandas 2.0 allows DataFrames to be backed by Apache Arrow memory buffers instead of NumPy. Arrow provides native support for missing data without type coercion, high-performance string manipulation, PyCapsule zero-copy data sharing with DuckDB/Polars, and multithreaded I/O.")
]

print("Course 2 Part 4 banks loaded successfully.")
